#import "fontawesome.typ": *

#let title = "Typst-FontAwesome"

#set page(
    paper: "a4",
      header: [
        #set text(6pt)
      ],
    numbering: "1"
)
#set heading(
  level: 2,
  numbering: "1.",
)
#set par(
  first-line-indent: 2em,
  justify: true,
  leading: 1em,
  linebreaks: "optimized"
)
#set block(above: 1em, below: 1em)

#align(center, text(18pt)[
      *#title*
])

#outline(
   title: [],
   indent: auto
)

#pagebreak()

= Brands

== A-H

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faAdn], [#icons.faAdn],
    [faAdversal], [#icons.faAdversal],
    [faAirbnb], [#icons.faAirbnb],
    [faAlgolia], [#icons.faAlgolia],
    [faAlipay], [#icons.faAlipay],
    [faAmazon], [#icons.faAmazon],
    [faAmazonPay], [#icons.faAmazonPay],
    [faAmazonPayCc], [#icons.faAmazonPayCc],
    [faAndroid], [#icons.faAndroid],
    [faAngular], [#icons.faAngular],
    [faApple], [#icons.faApple],
    [faApplePay], [#icons.faApplePay],
    [faApplePayCc], [#icons.faApplePayCc],
    [faAppStore], [#icons.faAppStore],
    [faAppStoreIos], [#icons.faAppStoreIos],
    [faAtlassian], [#icons.faAtlassian],
    [faAudible], [#icons.faAudible],
    [faAws], [#icons.faAws],
    [faBehance], [#icons.faBehance],
    [faBehanceSquare], [#icons.faBehanceSquare],
    [faBilibili], [#icons.faBilibili],
    [faBitbucket], [#icons.faBitbucket],
    [faBitcoin], [#icons.faBitcoin],
    [faBlackberry], [#icons.faBlackberry],
    [faBluetooth], [#icons.faBluetooth],
    [faBluetoothB], [#icons.faBluetoothB],
    [faBootstrap], [#icons.faBootstrap],
    [faBuffer], [#icons.faBuffer],
    [faCentos], [#icons.faCentos],
    [faChrome], [#icons.faChrome],
    [faChromecast], [#icons.faChromecast],
    [faCloudflare], [#icons.faCloudflare],
    [faCss3], [#icons.faCss3],
    [faCss3Alt], [#icons.faCss3Alt],
    [faDev], [#icons.faDev],
    [faDHL], [#icons.faDHL],
    [faDiscord], [#icons.faDiscord],
    [faDiscordBots], [#icons.faDiscordBots],
    [faDiscourse], [#icons.faDiscourse],
    [faDocker], [#icons.faDocker],
    [faDropbox], [#icons.faDropbox],
    [faDrupal], [#icons.faDrupal],
    [faEarlybirds], [#icons.faEarlybirds],
    [faEbay], [#icons.faEbay],
    [faEdge], [#icons.faEdge],
    [faEdgeLegacy], [#icons.faEdgeLegacy],
    [faErlang], [#icons.faErlang],
    [faEthereum], [#icons.faEthereum],
    [faEvernote], [#icons.faEvernote],
    [faFacebook], [#icons.faFacebook],
    [faFacebookF], [#icons.faFacebookF],
    [faFacebookMessenger], [#icons.faFacebookMessenger],
    [faFacebookSquare], [#icons.faFacebookSquare],
    [faFedex], [#icons.faFedex],
    [faFedora], [#icons.faFedora],
    [faFigma], [#icons.faFigma],
    [faFirefox], [#icons.faFirefox],
    [faFirefoxBrowser], [#icons.faFirefoxBrowser],
    [faFlickr], [#icons.faFlickr],
    [faFontAwesome], [#icons.faFontAwesome],
    [faFontAwesomeSquare], [#icons.faFontAwesomeSquare],
    [faFontAwesomeSquareStroke], [#icons.faFontAwesomeSquareStroke],
    [faFreebsd], [#icons.faFreebsd],
    [faGetPocket], [#icons.faGetPocket],
    [faGit], [#icons.faGit],
    [faGitAlt], [#icons.faGitAlt],
    [faGithub], [#icons.faGithub],
    [faGithubAlt], [#icons.faGithubAlt],
    [faGithubSquare], [#icons.faGithubSquare],
    [faGitkraken], [#icons.faGitkraken],
    [faGitlab], [#icons.faGitlab],
    [faGitlabSquare], [#icons.faGitlabSquare],
    [faGitSquare], [#icons.faGitSquare],
    [faGitter], [#icons.faGitter],
    [faGolang], [#icons.faGolang],
    [faGoogle], [#icons.faGoogle],
    [faGoogleDrive], [#icons.faGoogleDrive],
    [faGooglePay], [#icons.faGooglePay],
    [faGooglePlay], [#icons.faGooglePlay],
    [faGooglePlus], [#icons.faGooglePlus],
    [faGooglePlusG], [#icons.faGooglePlusG],
    [faGooglePlusSquare], [#icons.faGooglePlusSquare],
    [faGoogleWallet], [#icons.faGoogleWallet],
    [faGrunt], [#icons.faGrunt],
    [faGulp], [#icons.faGulp],
    [faHive], [#icons.faHive],
    [faHtml5], [#icons.faHtml5],
)])

#pagebreak()

== I-Z

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faInstagram], [#icons.faInstagram],
    [faInstagramSquare], [#icons.faInstagramSquare],
    [faInternetExplorer], [#icons.faInternetExplorer],
    [faItunes], [#icons.faItunes],
    [faItunesNote], [#icons.faItunesNote],
    [faJava], [#icons.faJava],
    [faJenkins], [#icons.faJenkins],
    [faJira], [#icons.faJira],
    [faJoomla], [#icons.faJoomla],
    [faJs], [#icons.faJs],
    [faJsSquare], [#icons.faJsSquare],
    [faKaggle], [#icons.faKaggle],
    [faLaravel], [#icons.faLaravel],
    [faLastfm], [#icons.faLastfm],
    [faLastfmSquare], [#icons.faLastfmSquare],
    [faLeanpub], [#icons.faLeanpub],
    [faLess], [#icons.faLess],
    [faLine], [#icons.faLine],
    [faLinkedin], [#icons.faLinkedin],
    [faLinkedinIn], [#icons.faLinkedinIn],
    [faLinux], [#icons.faLinux],
    [faMarkdown], [#icons.faMarkdown],
    [faMastercardCc], [#icons.faMastercardCc],
    [faMastodon], [#icons.faMastodon],
    [faMdb], [#icons.faMdb],
    [faMedium], [#icons.faMedium],
    [faMendeley], [#icons.faMendeley],
    [faMeta], [#icons.faMeta],
    [faMicrosoft], [#icons.faMicrosoft],
    [faNode], [#icons.faNode],
    [faNodeJS], [#icons.faNodeJS],
    [faNpm], [#icons.faNpm],
    [faOpera], [#icons.faOpera],
    [faOsi], [#icons.faOsi],
    [faPatreon], [#icons.faPatreon],
    [faPaypal], [#icons.faPaypal],
    [faPaypalCc], [#icons.faPaypalCc],
    [faPhp], [#icons.faPhp],
    [faPinterest], [#icons.faPinterest],
    [faPinterestP], [#icons.faPinterestP],
    [faPinterestSquare], [#icons.faPinterestSquare],
    [faProductHunt], [#icons.faProductHunt],
    [faPython], [#icons.faPython],
    [faQq], [#icons.faQq],
    [faQuora], [#icons.faQuora],
    [faRaspberryPi], [#icons.faRaspberryPi],
    [faReact], [#icons.faReact],
    [faReadme], [#icons.faReadme],
    [faReddit], [#icons.faReddit],
    [faRedditAlien], [#icons.faRedditAlien],
    [faRedditSquare], [#icons.faRedditSquare],
    [faRedhat], [#icons.faRedhat],
    [faRenren], [#icons.faRenren],
    [faResearchgate], [#icons.faResearchgate],
    [faRProject], [#icons.faRProject],
    [faRust], [#icons.faRust],
    [faSafari], [#icons.faSafari],
    [faSalesforce], [#icons.faSalesforce],
    [faSass], [#icons.faSass],
    [faScribd], [#icons.faScribd],
    [faShopify], [#icons.faShopify],
    [faSketch], [#icons.faSketch],
    [faSkype], [#icons.faSkype],
    [faSlack], [#icons.faSlack],
    [faSnapchat], [#icons.faSnapchat],
    [faSnapchatSquare], [#icons.faSnapchatSquare],
    [faSpotify], [#icons.faSpotify],
    [faSteamSquare], [#icons.faSteamSquare],
    [faStripeCc], [#icons.faStripeCc],
    [faSuse], [#icons.faSuse],
    [faSwift], [#icons.faSwift],
    [faSymfony], [#icons.faSymfony],
    [faTelegram], [#icons.faTelegram],
    [faTencentWeibo], [#icons.faTencentWeibo],
    [faTiktok], [#icons.faTiktok],
    [faTrello], [#icons.faTrello],
    [faTumblr], [#icons.faTumblr],
    [faTumblrSquare], [#icons.faTumblrSquare],
    [faTwitch], [#icons.faTwitch],
    [faTwitter], [#icons.faTwitter],
    [faTwitterSquare], [#icons.faTwitterSquare],
    [faUber], [#icons.faUber],
    [faUbuntu], [#icons.faUbuntu],
    [faUnity], [#icons.faUnity],
    [faUsb], [#icons.faUsb],
    [faViadeoSquare], [#icons.faViadeoSquare],
    [faViber], [#icons.faViber],
    [faVimeo], [#icons.faVimeo],
    [faVimeoSquare], [#icons.faVimeoSquare],
    [faVimeoV], [#icons.faVimeoV],
    [faVisa], [#icons.faVisa],
    [faVk], [#icons.faVk],
    [faVuejs], [#icons.faVuejs],
    [faWeibo], [#icons.faWeibo],
    [faWeixin], [#icons.faWeixin],
    [faWhatsapp], [#icons.faWhatsapp],
    [faWhatsappSquare], [#icons.faWhatsappSquare],
    [faWikipedia], [#icons.faWikipedia],
    [faWindows], [#icons.faWindows],
    [faWordpress], [#icons.faWordpress],
    [faWordpressSimple], [#icons.faWordpressSimple],
    [faXbox], [#icons.faXbox],
    [faYahoo], [#icons.faYahoo],
    [faYandex], [#icons.faYandex],
    [faYarn], [#icons.faYarn],
    [faYCombinator], [#icons.faYCombinator],
    [faYoutube], [#icons.faYoutube],
    [faYoutubeSquare], [#icons.faYoutubeSquare],
    [faZhihu], [#icons.faZhihu]
)])

#pagebreak()

= Regular

== A-E

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faAddressBook], [#icons.faAddressBook],
    [faAddressCard], [#icons.faAddressCard],
    [faBellSlash], [#icons.faBellSlash],
    [faBell], [#icons.faBell],
    [faBookmark], [#icons.faBookmark],
    [faBuilding], [#icons.faBuilding],
    [faCalendarCheck], [#icons.faCalendarCheck],
    [faCalendarDays], [#icons.faCalendarDays],
    [faCalendarMinus], [#icons.faCalendarMinus],
    [faCalendarPlus], [#icons.faCalendarPlus],
    [faCalendarXmark], [#icons.faCalendarXmark],
    [faCalendar], [#icons.faCalendar],
    [faChartBar], [#icons.faChartBar],
    [faChessBishop], [#icons.faChessBishop],
    [faChessKing], [#icons.faChessKing],
    [faChessKnight], [#icons.faChessKnight],
    [faChessPawn], [#icons.faChessPawn],
    [faChessQueen], [#icons.faChessQueen],
    [faChessRook], [#icons.faChessRook],
    [faCircleCheck], [#icons.faCircleCheck],
    [faCircleDot], [#icons.faCircleDot],
    [faCircleDown], [#icons.faCircleDown],
    [faCircleLeft], [#icons.faCircleLeft],
    [faCirclePause], [#icons.faCirclePause],
    [faCirclePlay], [#icons.faCirclePlay],
    [faCircleQuestion], [#icons.faCircleQuestion],
    [faCircleRight], [#icons.faCircleRight],
    [faCircleStop], [#icons.faCircleStop],
    [faCircleUp], [#icons.faCircleUp],
    [faCircleUser], [#icons.faCircleUser],
    [faCircleXmark], [#icons.faCircleXmark],
    [faCircle], [#icons.faCircle],
    [faClipboard], [#icons.faClipboard],
    [faClock], [#icons.faClock],
    [faClone], [#icons.faClone],
    [faClosedCaptioning], [#icons.faClosedCaptioning],
    [faCommentDots], [#icons.faCommentDots],
    [faComment], [#icons.faComment],
    [faComments], [#icons.faComments],
    [faCompass], [#icons.faCompass],
    [faCopy], [#icons.faCopy],
    [faCopyright], [#icons.faCopyright],
    [faCreditCard], [#icons.faCreditCard],
    [faEnvelopeOpen], [#icons.faEnvelopeOpen],
    [faEnvelope], [#icons.faEnvelope],
    [faEyeSlash], [#icons.faEyeSlash],
    [faEye], [#icons.faEye],
)])

#pagebreak()

== F

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFaceAngry], [#icons.faFaceAngry],
    [faFaceDizzy], [#icons.faFaceDizzy],
    [faFaceFlushed], [#icons.faFaceFlushed],
    [faFaceFrownOpen], [#icons.faFaceFrownOpen],
    [faFaceFrown], [#icons.faFaceFrown],
    [faFaceGrimace], [#icons.faFaceGrimace],
    [faFaceGrinBeamSweat], [#icons.faFaceGrinBeamSweat],
    [faFaceGrinBeam], [#icons.faFaceGrinBeam],
    [faFaceGrinHearts], [#icons.faFaceGrinHearts],
    [faFaceGrinSquintTears], [#icons.faFaceGrinSquintTears],
    [faFaceGrinSquint], [#icons.faFaceGrinSquint],
    [faFaceGrinStars], [#icons.faFaceGrinStars],
    [faFaceGrinTears], [#icons.faFaceGrinTears],
    [faFaceGrinTongueSquint], [#icons.faFaceGrinTongueSquint],
    [faFaceGrinTongueWink], [#icons.faFaceGrinTongueWink],
    [faFaceGrinTongue], [#icons.faFaceGrinTongue],
    [faFaceGrinWide], [#icons.faFaceGrinWide],
    [faFaceGrinWink], [#icons.faFaceGrinWink],
    [faFaceGrin], [#icons.faFaceGrin],
    [faFaceKissBeam], [#icons.faFaceKissBeam],
    [faFaceKissWinkHeart], [#icons.faFaceKissWinkHeart],
    [faFaceKiss], [#icons.faFaceKiss],
    [faFaceLaughBeam], [#icons.faFaceLaughBeam],
    [faFaceLaughSquint], [#icons.faFaceLaughSquint],
    [faFaceLaughWink], [#icons.faFaceLaughWink],
    [faFaceLaugh], [#icons.faFaceLaugh],
    [faFaceMehBlank], [#icons.faFaceMehBlank],
    [faFaceMeh], [#icons.faFaceMeh],
    [faFaceRollingEyes], [#icons.faFaceRollingEyes],
    [faFaceSadCry], [#icons.faFaceSadCry],
    [faFaceSadTear], [#icons.faFaceSadTear],
    [faFaceSmileBeam], [#icons.faFaceSmileBeam],
    [faFaceSmileWink], [#icons.faFaceSmileWink],
    [faFaceSmile], [#icons.faFaceSmile],
    [faFaceSurprise], [#icons.faFaceSurprise],
    [faFaceTired], [#icons.faFaceTired],
    [faFileAudio], [#icons.faFileAudio],
    [faFileCode], [#icons.faFileCode],
    [faFileExcel], [#icons.faFileExcel],
    [faFileImage], [#icons.faFileImage],
    [faFileLines], [#icons.faFileLines],
    [faFilePdf], [#icons.faFilePdf],
    [faFilePowerpoint], [#icons.faFilePowerpoint],
    [faFileVideo], [#icons.faFileVideo],
    [faFileWord], [#icons.faFileWord],
    [faFileZipper], [#icons.faFileZipper],
    [faFile], [#icons.faFile],
    [faFlag], [#icons.faFlag],
    [faFloppyDisk], [#icons.faFloppyDisk],
    [faFolderClosed], [#icons.faFolderClosed],
    [faFolderOpen], [#icons.faFolderOpen],
    [faFolder], [#icons.faFolder],
    [faFontAwesome], [#icons.faFontAwesome],
    [faFutbol], [#icons.faFutbol],
)])

#pagebreak()

== G-W

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faGem], [#icons.faGem],
    [faHandBackFist], [#icons.faHandBackFist],
    [faHandLizard], [#icons.faHandLizard],
    [faHandPeace], [#icons.faHandPeace],
    [faHandPointDown], [#icons.faHandPointDown],
    [faHandPointLeft], [#icons.faHandPointLeft],
    [faHandPointRight], [#icons.faHandPointRight],
    [faHandPointUp], [#icons.faHandPointUp],
    [faHandPointer], [#icons.faHandPointer],
    [faHandScissors], [#icons.faHandScissors],
    [faHandSpock], [#icons.faHandSpock],
    [faHand], [#icons.faHand],
    [faHandshake], [#icons.faHandshake],
    [faHardDrive], [#icons.faHardDrive],
    [faHeart], [#icons.faHeart],
    [faHospital], [#icons.faHospital],
    [faHourglassHalf], [#icons.faHourglassHalf],
    [faHourglass], [#icons.faHourglass],
    [faIdBadge], [#icons.faIdBadge],
    [faIdCard], [#icons.faIdCard],
    [faImage], [#icons.faImage],
    [faImages], [#icons.faImages],
    [faKeyboard], [#icons.faKeyboard],
    [faLemon], [#icons.faLemon],
    [faLifeRing], [#icons.faLifeRing],
    [faLightbulb], [#icons.faLightbulb],
    [faMap], [#icons.faMap],
    [faMessage], [#icons.faMessage],
    [faMoneyBill1], [#icons.faMoneyBill1],
    [faMoon], [#icons.faMoon],
    [faNewspaper], [#icons.faNewspaper],
    [faNoteSticky], [#icons.faNoteSticky],
    [faObjectGroup], [#icons.faObjectGroup],
    [faObjectUngroup], [#icons.faObjectUngroup],
    [faPaperPlane], [#icons.faPaperPlane],
    [faPaste], [#icons.faPaste],
    [faPenToSquare], [#icons.faPenToSquare],
    [faRectangleList], [#icons.faRectangleList],
    [faRectangleXmark], [#icons.faRectangleXmark],
    [faRegistered], [#icons.faRegistered],
    [faShareFromSquare], [#icons.faShareFromSquare],
    [faSnowflake], [#icons.faSnowflake],
    [faSquareCaretDown], [#icons.faSquareCaretDown],
    [faSquareCaretLeft], [#icons.faSquareCaretLeft],
    [faSquareCaretRight], [#icons.faSquareCaretRight],
    [faSquareCaretUp], [#icons.faSquareCaretUp],
    [faSquareCheck], [#icons.faSquareCheck],
    [faSquareFull], [#icons.faSquareFull],
    [faSquareMinus], [#icons.faSquareMinus],
    [faSquarePlus], [#icons.faSquarePlus],
    [faSquare], [#icons.faSquare],
    [faStarHalfStroke], [#icons.faStarHalfStroke],
    [faStarHalf], [#icons.faStarHalf],
    [faStar], [#icons.faStar],
    [faSun], [#icons.faSun],
    [faThumbsDown], [#icons.faThumbsDown],
    [faThumbsUp], [#icons.faThumbsUp],
    [faTrashCan], [#icons.faTrashCan],
    [faUser], [#icons.faUser],
    [faWindowMaximize], [#icons.faWindowMaximize],
    [faWindowMinimize], [#icons.faWindowMinimize],
    [faWindowRestore], [#icons.faWindowRestore],
)])

#pagebreak()

= Solid

== A

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faAS], [#icons.faAS],
    [faAddressBookS], [#icons.faAddressBookS],
    [faAddressCardS], [#icons.faAddressCardS],
    [faAlignCenterS], [#icons.faAlignCenterS],
    [faAlignJustifyS], [#icons.faAlignJustifyS],
    [faAlignLeftS], [#icons.faAlignLeftS],
    [faAlignRightS], [#icons.faAlignRightS],
    [faAnchorCircleCheckS], [#icons.faAnchorCircleCheckS],
    [faAnchorCircleExclamationS], [#icons.faAnchorCircleExclamationS],
    [faAnchorCircleXmarkS], [#icons.faAnchorCircleXmarkS],
    [faAnchorLockS], [#icons.faAnchorLockS],
    [faAnchorS], [#icons.faAnchorS],
    [faAngleDownS], [#icons.faAngleDownS],
    [faAngleLeftS], [#icons.faAngleLeftS],
    [faAngleRightS], [#icons.faAngleRightS],
    [faAngleUpS], [#icons.faAngleUpS],
    [faAnglesDownS], [#icons.faAnglesDownS],
    [faAnglesLeftS], [#icons.faAnglesLeftS],
    [faAnglesRightS], [#icons.faAnglesRightS],
    [faAnglesUpS], [#icons.faAnglesUpS],
    [faAnkhS], [#icons.faAnkhS],
    [faAppleWholeS], [#icons.faAppleWholeS],
    [faArchwayS], [#icons.faArchwayS],
    [faArrowDown19S], [#icons.faArrowDown19S],
    [faArrowDown91S], [#icons.faArrowDown91S],
    [faArrowDownAZS], [#icons.faArrowDownAZS],
    [faArrowDownLongS], [#icons.faArrowDownLongS],
    [faArrowDownShortWideS], [#icons.faArrowDownShortWideS],
    [faArrowDownUpAcrossLineS], [#icons.faArrowDownUpAcrossLineS],
    [faArrowDownUpLockS], [#icons.faArrowDownUpLockS],
    [faArrowDownWideShortS], [#icons.faArrowDownWideShortS],
    [faArrowDownZAS], [#icons.faArrowDownZAS],
    [faArrowDownS], [#icons.faArrowDownS],
    [faArrowLeftLongS], [#icons.faArrowLeftLongS],
    [faArrowLeftS], [#icons.faArrowLeftS],
    [faArrowPointerS], [#icons.faArrowPointerS],
    [faArrowRightArrowLeftS], [#icons.faArrowRightArrowLeftS],
    [faArrowRightFromBracketS], [#icons.faArrowRightFromBracketS],
    [faArrowRightLongS], [#icons.faArrowRightLongS],
    [faArrowRightToBracketS], [#icons.faArrowRightToBracketS],
    [faArrowRightToCityS], [#icons.faArrowRightToCityS],
    [faArrowRightS], [#icons.faArrowRightS],
    [faArrowRotateLeftS], [#icons.faArrowRotateLeftS],
    [faArrowRotateRightS], [#icons.faArrowRotateRightS],
    [faArrowTrendDownS], [#icons.faArrowTrendDownS],
    [faArrowTrendUpS], [#icons.faArrowTrendUpS],
    [faArrowTurnDownS], [#icons.faArrowTurnDownS],
    [faArrowTurnUpS], [#icons.faArrowTurnUpS],
    [faArrowUp19S], [#icons.faArrowUp19S],
    [faArrowUp91S], [#icons.faArrowUp91S],
    [faArrowUpAZS], [#icons.faArrowUpAZS],
    [faArrowUpFromBracketS], [#icons.faArrowUpFromBracketS],
    [faArrowUpFromGroundWaterS], [#icons.faArrowUpFromGroundWaterS],
    [faArrowUpFromWaterPumpS], [#icons.faArrowUpFromWaterPumpS],
    [faArrowUpLongS], [#icons.faArrowUpLongS],
    [faArrowUpRightDotsS], [#icons.faArrowUpRightDotsS],
    [faArrowUpRightFromSquareS], [#icons.faArrowUpRightFromSquareS],
    [faArrowUpShortWideS], [#icons.faArrowUpShortWideS],
    [faArrowUpWideShortS], [#icons.faArrowUpWideShortS],
    [faArrowUpZAS], [#icons.faArrowUpZAS],
    [faArrowUpS], [#icons.faArrowUpS],
    [faArrowsDownToLineS], [#icons.faArrowsDownToLineS],
    [faArrowsDownToPeopleS], [#icons.faArrowsDownToPeopleS],
    [faArrowsLeftRightToLineS], [#icons.faArrowsLeftRightToLineS],
    [faArrowsLeftRightS], [#icons.faArrowsLeftRightS],
    [faArrowsRotateS], [#icons.faArrowsRotateS],
    [faArrowsSpinS], [#icons.faArrowsSpinS],
    [faArrowsSplitUpAndLeftS], [#icons.faArrowsSplitUpAndLeftS],
    [faArrowsToCircleS], [#icons.faArrowsToCircleS],
    [faArrowsToDotS], [#icons.faArrowsToDotS],
    [faArrowsToEyeS], [#icons.faArrowsToEyeS],
    [faArrowsTurnRightS], [#icons.faArrowsTurnRightS],
    [faArrowsTurnToDotsS], [#icons.faArrowsTurnToDotsS],
    [faArrowsUpDownLeftRightS], [#icons.faArrowsUpDownLeftRightS],
    [faArrowsUpDownS], [#icons.faArrowsUpDownS],
    [faArrowsUpToLineS], [#icons.faArrowsUpToLineS],
    [faAsteriskS], [#icons.faAsteriskS],
    [faAtS], [#icons.faAtS],
    [faAtomS], [#icons.faAtomS],
    [faAudioDescriptionS], [#icons.faAudioDescriptionS],
    [faAustralSignS], [#icons.faAustralSignS],
    [faAwardS], [#icons.faAwardS],
)])

#pagebreak()

== B-Br

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faBS], [#icons.faBS],
    [faBabyCarriageS], [#icons.faBabyCarriageS],
    [faBabyS], [#icons.faBabyS],
    [faBackwardFastS], [#icons.faBackwardFastS],
    [faBackwardStepS], [#icons.faBackwardStepS],
    [faBackwardS], [#icons.faBackwardS],
    [faBaconS], [#icons.faBaconS],
    [faBacteriaS], [#icons.faBacteriaS],
    [faBacteriumS], [#icons.faBacteriumS],
    [faBagShoppingS], [#icons.faBagShoppingS],
    [faBahaiS], [#icons.faBahaiS],
    [faBahtSignS], [#icons.faBahtSignS],
    [faBanSmokingS], [#icons.faBanSmokingS],
    [faBanS], [#icons.faBanS],
    [faBandageS], [#icons.faBandageS],
    [faSbangladeshiTakaSignS], [#icons.faSbangladeshiTakaSignS],
    [faBarcodeS], [#icons.faBarcodeS],
    [faBarsProgressS], [#icons.faBarsProgressS],
    [faBarsStaggeredS], [#icons.faBarsStaggeredS],
    [faBarsS], [#icons.faBarsS],
    [faBaseballBatBallS], [#icons.faBaseballBatBallS],
    [faBaseballS], [#icons.faBaseballS],
    [faBasketShoppingS], [#icons.faBasketShoppingS],
    [faBasketballS], [#icons.faBasketballS],
    [faBathS], [#icons.faBathS],
    [faBatteryEmptyS], [#icons.faBatteryEmptyS],
    [faBatteryFullS], [#icons.faBatteryFullS],
    [faBatteryHalfS], [#icons.faBatteryHalfS],
    [faBatteryQuarterS], [#icons.faBatteryQuarterS],
    [faBatteryThreeQuartersS], [#icons.faBatteryThreeQuartersS],
    [faBedPulseS], [#icons.faBedPulseS],
    [faBedS], [#icons.faBedS],
    [faBeerMugEmptyS], [#icons.faBeerMugEmptyS],
    [faBellConciergeS], [#icons.faBellConciergeS],
    [faBellSlashS], [#icons.faBellSlashS],
    [faBellS], [#icons.faBellS],
    [faBezierCurveS], [#icons.faBezierCurveS],
    [faBicycleS], [#icons.faBicycleS],
    [faBinocularsS], [#icons.faBinocularsS],
    [faBiohazardS], [#icons.faBiohazardS],
    [faBitcoinSignS], [#icons.faBitcoinSignS],
    [faBlenderPhoneS], [#icons.faBlenderPhoneS],
    [faBlenderS], [#icons.faBlenderS],
    [faBlogS], [#icons.faBlogS],
    [faBoldS], [#icons.faBoldS],
    [faBoltLightningS], [#icons.faBoltLightningS],
    [faBoltS], [#icons.faBoltS],
    [faBombS], [#icons.faBombS],
    [faBoneS], [#icons.faBoneS],
    [faBongS], [#icons.faBongS],
    [faBookAtlasS], [#icons.faBookAtlasS],
    [faBookBibleS], [#icons.faBookBibleS],
    [faBookBookmarkS], [#icons.faBookBookmarkS],
    [faBookJournalWhillsS], [#icons.faBookJournalWhillsS],
    [faBookMedicalS], [#icons.faBookMedicalS],
    [faBookOpenReaderS], [#icons.faBookOpenReaderS],
    [faBookOpenS], [#icons.faBookOpenS],
    [faBookQuranS], [#icons.faBookQuranS],
    [faBookSkullS], [#icons.faBookSkullS],
    [faBookTanakhS], [#icons.faBookTanakhS],
    [faBookS], [#icons.faBookS],
    [faBookmarkS], [#icons.faBookmarkS],
    [faBorderAllS], [#icons.faBorderAllS],
    [faBorderNoneS], [#icons.faBorderNoneS],
    [faBorderTopLeftS], [#icons.faBorderTopLeftS],
    [faBoreHoleS], [#icons.faBoreHoleS],
    [faBottleDropletS], [#icons.faBottleDropletS],
    [faBottleWaterS], [#icons.faBottleWaterS],
    [faBowlFoodS], [#icons.faBowlFoodS],
    [faBowlRiceS], [#icons.faBowlRiceS],
    [faBowlingBallS], [#icons.faBowlingBallS],
    [faBoxArchiveS], [#icons.faBoxArchiveS],
    [faBoxOpenS], [#icons.faBoxOpenS],
    [faBoxTissueS], [#icons.faBoxTissueS],
    [faBoxS], [#icons.faBoxS],
    [faBoxesPackingS], [#icons.faBoxesPackingS],
    [faBoxesStackedS], [#icons.faBoxesStackedS],
    [faBrailleS], [#icons.faBrailleS],
    [faBrainS], [#icons.faBrainS],
    [faBrazilianRealSignS], [#icons.faBrazilianRealSignS],
    [faBreadSliceS], [#icons.faBreadSliceS],
    [faBridgeCircleCheckS], [#icons.faBridgeCircleCheckS],
    [faBridgeCircleExclamationS], [#icons.faBridgeCircleExclamationS],
    [faBridgeCircleXmarkS], [#icons.faBridgeCircleXmarkS],
    [faBridgeLockS], [#icons.faBridgeLockS],
    [faBridgeWaterS], [#icons.faBridgeWaterS],
    [faBridgeS], [#icons.faBridgeS],
    [faBriefcaseMedicalS], [#icons.faBriefcaseMedicalS],
    [faBriefcaseS], [#icons.faBriefcaseS],
    [faBroomBallS], [#icons.faBroomBallS],
    [faBroomS], [#icons.faBroomS],
    [faBrushS], [#icons.faBrushS],
)])

#pagebreak()

== Bu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faBucketS], [#icons.faBucketS],
    [faBugSlashS], [#icons.faBugSlashS],
    [faBugS], [#icons.faBugS],
    [faBugsS], [#icons.faBugsS],
    [faBuildingCircleArrowRightS], [#icons.faBuildingCircleArrowRightS],
    [faBuildingCircleCheckS], [#icons.faBuildingCircleCheckS],
    [faBuildingCircleExclamationS], [#icons.faBuildingCircleExclamationS],
    [faBuildingCircleXmarkS], [#icons.faBuildingCircleXmarkS],
    [faBuildingColumnsS], [#icons.faBuildingColumnsS],
    [faBuildingFlagS], [#icons.faBuildingFlagS],
    [faBuildingLockS], [#icons.faBuildingLockS],
    [faBuildingNgoS], [#icons.faBuildingNgoS],
    [faBuildingShieldS], [#icons.faBuildingShieldS],
    [faBuildingUnS], [#icons.faBuildingUnS],
    [faBuildingUserS], [#icons.faBuildingUserS],
    [faBuildingWheatS], [#icons.faBuildingWheatS],
    [faBuildingS], [#icons.faBuildingS],
    [faBullhornS], [#icons.faBullhornS],
    [faBullseyeS], [#icons.faBullseyeS],
    [faBurgerS], [#icons.faBurgerS],
    [faBurstS], [#icons.faBurstS],
    [faBusSimpleS], [#icons.faBusSimpleS],
    [faBusS], [#icons.faBusS],
    [faBusinessTimeS], [#icons.faBusinessTimeS],
)])

== C-Ce

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faCS], [#icons.faCS],
    [faCableCarS], [#icons.faCableCarS],
    [faCakeCandlesS], [#icons.faCakeCandlesS],
    [faCalculatorS], [#icons.faCalculatorS],
    [faCalendarCheckS], [#icons.faCalendarCheckS],
    [faCalendarDayS], [#icons.faCalendarDayS],
    [faCalendarDaysS], [#icons.faCalendarDaysS],
    [faCalendarMinusS], [#icons.faCalendarMinusS],
    [faCalendarPlusS], [#icons.faCalendarPlusS],
    [faCalendarWeekS], [#icons.faCalendarWeekS],
    [faCalendarXmarkS], [#icons.faCalendarXmarkS],
    [faCalendarS], [#icons.faCalendarS],
    [faCameraRetroS], [#icons.faCameraRetroS],
    [faCameraRotateS], [#icons.faCameraRotateS],
    [faCameraS], [#icons.faCameraS],
    [faCampgroundS], [#icons.faCampgroundS],
    [faCandyCaneS], [#icons.faCandyCaneS],
    [faCannabisS], [#icons.faCannabisS],
    [faCapsulesS], [#icons.faCapsulesS],
    [faCarBatteryS], [#icons.faCarBatteryS],
    [faCarBurstS], [#icons.faCarBurstS],
    [faCarOnS], [#icons.faCarOnS],
    [faCarRearS], [#icons.faCarRearS],
    [faCarSideS], [#icons.faCarSideS],
    [faCarTunnelS], [#icons.faCarTunnelS],
    [faCarS], [#icons.faCarS],
    [faCaravanS], [#icons.faCaravanS],
    [faCaretDownS], [#icons.faCaretDownS],
    [faCaretLeftS], [#icons.faCaretLeftS],
    [faCaretRightS], [#icons.faCaretRightS],
    [faCaretUpS], [#icons.faCaretUpS],
    [faCarrotS], [#icons.faCarrotS],
    [faCartArrowDownS], [#icons.faCartArrowDownS],
    [faCartFlatbedSuitcaseS], [#icons.faCartFlatbedSuitcaseS],
    [faCartFlatbedS], [#icons.faCartFlatbedS],
    [faCartPlusS], [#icons.faCartPlusS],
    [faCartShoppingS], [#icons.faCartShoppingS],
    [faCashRegisterS], [#icons.faCashRegisterS],
    [faCatS], [#icons.faCatS],
    [faCediSignS], [#icons.faCediSignS],
    [faCentSignS], [#icons.faCentSignS],
    [faCertificateS], [#icons.faCertificateS],
)])

#pagebreak()

== Ch-Cl

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faChairS], [#icons.faChairS],
    [faChalkboardUserS], [#icons.faChalkboardUserS],
    [faChalkboardS], [#icons.faChalkboardS],
    [faChampagneGlassesS], [#icons.faChampagneGlassesS],
    [faChargingStationS], [#icons.faChargingStationS],
    [faChartAreaS], [#icons.faChartAreaS],
    [faChartBarS], [#icons.faChartBarS],
    [faChartColumnS], [#icons.faChartColumnS],
    [faChartGanttS], [#icons.faChartGanttS],
    [faChartLineS], [#icons.faChartLineS],
    [faChartPieS], [#icons.faChartPieS],
    [faChartSimpleS], [#icons.faChartSimpleS],
    [faCheckDoubleS], [#icons.faCheckDoubleS],
    [faCheckToSlotS], [#icons.faCheckToSlotS],
    [faCheckS], [#icons.faCheckS],
    [faCheeseS], [#icons.faCheeseS],
    [faChessBishopS], [#icons.faChessBishopS],
    [faChessBoardS], [#icons.faChessBoardS],
    [faChessKingS], [#icons.faChessKingS],
    [faChessKnightS], [#icons.faChessKnightS],
    [faChessPawnS], [#icons.faChessPawnS],
    [faChessQueenS], [#icons.faChessQueenS],
    [faChessRookS], [#icons.faChessRookS],
    [faChessS], [#icons.faChessS],
    [faChevronDownS], [#icons.faChevronDownS],
    [faChevronLeftS], [#icons.faChevronLeftS],
    [faChevronRightS], [#icons.faChevronRightS],
    [faChevronUpS], [#icons.faChevronUpS],
    [faChildCombatantS], [#icons.faChildCombatantS],
    [faChildDressS], [#icons.faChildDressS],
    [faChildReachingS], [#icons.faChildReachingS],
    [faChildS], [#icons.faChildS],
    [faChildrenS], [#icons.faChildrenS],
    [faChurchS], [#icons.faChurchS],
    [faCircleArrowDownS], [#icons.faCircleArrowDownS],
    [faCircleArrowLeftS], [#icons.faCircleArrowLeftS],
    [faCircleArrowRightS], [#icons.faCircleArrowRightS],
    [faCircleArrowUpS], [#icons.faCircleArrowUpS],
    [faCircleCheckS], [#icons.faCircleCheckS],
    [faCircleChevronDownS], [#icons.faCircleChevronDownS],
    [faCircleChevronLeftS], [#icons.faCircleChevronLeftS],
    [faCircleChevronRightS], [#icons.faCircleChevronRightS],
    [faCircleChevronUpS], [#icons.faCircleChevronUpS],
    [faCircleDollarToSlotS], [#icons.faCircleDollarToSlotS],
    [faCircleDotS], [#icons.faCircleDotS],
    [faCircleDownS], [#icons.faCircleDownS],
    [faCircleExclamationS], [#icons.faCircleExclamationS],
    [faCircleHS], [#icons.faCircleHS],
    [faCircleHalfStrokeS], [#icons.faCircleHalfStrokeS],
    [faCircleInfoS], [#icons.faCircleInfoS],
    [faCircleLeftS], [#icons.faCircleLeftS],
    [faCircleMinusS], [#icons.faCircleMinusS],
    [faCircleNodesS], [#icons.faCircleNodesS],
    [faCircleNotchS], [#icons.faCircleNotchS],
    [faCirclePauseS], [#icons.faCirclePauseS],
    [faCirclePlayS], [#icons.faCirclePlayS],
    [faCirclePlusS], [#icons.faCirclePlusS],
    [faCircleQuestionS], [#icons.faCircleQuestionS],
    [faCircleRadiationS], [#icons.faCircleRadiationS],
    [faCircleRightS], [#icons.faCircleRightS],
    [faCircleStopS], [#icons.faCircleStopS],
    [faCircleUpS], [#icons.faCircleUpS],
    [faCircleUserS], [#icons.faCircleUserS],
    [faCircleXmarkS], [#icons.faCircleXmarkS],
    [faCircleS], [#icons.faCircleS],
    [faCityS], [#icons.faCityS],
    [faClapperboardS], [#icons.faClapperboardS],
    [faClipboardCheckS], [#icons.faClipboardCheckS],
    [faClipboardListS], [#icons.faClipboardListS],
    [faClipboardQuestionS], [#icons.faClipboardQuestionS],
    [faClipboardUserS], [#icons.faClipboardUserS],
    [faClipboardS], [#icons.faClipboardS],
    [faClockRotateLeftS], [#icons.faClockRotateLeftS],
    [faClockS], [#icons.faClockS],
    [faCloneS], [#icons.faCloneS],
    [faClosedCaptioningS], [#icons.faClosedCaptioningS],
    [faCloudArrowDownS], [#icons.faCloudArrowDownS],
    [faCloudArrowUpS], [#icons.faCloudArrowUpS],
    [faCloudBoltS], [#icons.faCloudBoltS],
    [faCloudMeatballS], [#icons.faCloudMeatballS],
    [faCloudMoonRainS], [#icons.faCloudMoonRainS],
    [faCloudMoonS], [#icons.faCloudMoonS],
    [faCloudRainS], [#icons.faCloudRainS],
    [faCloudShowersHeavyS], [#icons.faCloudShowersHeavyS],
    [faCloudShowersWaterS], [#icons.faCloudShowersWaterS],
    [faCloudSunRainS], [#icons.faCloudSunRainS],
    [faCloudSunS], [#icons.faCloudSunS],
    [faCloudS], [#icons.faCloudS],
    [faCloverS], [#icons.faCloverS],
)])

#pagebreak()

== Co-Cu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faCodeBranchS], [#icons.faCodeBranchS],
    [faCodeCommitS], [#icons.faCodeCommitS],
    [faCodeCompareS], [#icons.faCodeCompareS],
    [faCodeForkS], [#icons.faCodeForkS],
    [faCodeMergeS], [#icons.faCodeMergeS],
    [faCodePullRequestS], [#icons.faCodePullRequestS],
    [faCodeS], [#icons.faCodeS],
    [faCoinsS], [#icons.faCoinsS],
    [faColonSignS], [#icons.faColonSignS],
    [faCommentDollarS], [#icons.faCommentDollarS],
    [faCommentDotsS], [#icons.faCommentDotsS],
    [faCommentMedicalS], [#icons.faCommentMedicalS],
    [faCommentSlashS], [#icons.faCommentSlashS],
    [faCommentSmsS], [#icons.faCommentSmsS],
    [faCommentS], [#icons.faCommentS],
    [faCommentsDollarS], [#icons.faCommentsDollarS],
    [faCommentsS], [#icons.faCommentsS],
    [faCompactDiscS], [#icons.faCompactDiscS],
    [faCompassDraftingS], [#icons.faCompassDraftingS],
    [faCompassS], [#icons.faCompassS],
    [faCompressS], [#icons.faCompressS],
    [faComputerMouseS], [#icons.faComputerMouseS],
    [faComputerS], [#icons.faComputerS],
    [faCookieBiteS], [#icons.faCookieBiteS],
    [faCookieS], [#icons.faCookieS],
    [faCopyS], [#icons.faCopyS],
    [faCopyrightS], [#icons.faCopyrightS],
    [faCouchS], [#icons.faCouchS],
    [faCowS], [#icons.faCowS],
    [faCreditCardS], [#icons.faCreditCardS],
    [faCropSimpleS], [#icons.faCropSimpleS],
    [faCropS], [#icons.faCropS],
    [faCrossS], [#icons.faCrossS],
    [faCrosshairsS], [#icons.faCrosshairsS],
    [faCrowS], [#icons.faCrowS],
    [faCrownS], [#icons.faCrownS],
    [faCrutchS], [#icons.faCrutchS],
    [faCruzeiroSignS], [#icons.faCruzeiroSignS],
    [faCubeS], [#icons.faCubeS],
    [faCubesStackedS], [#icons.faCubesStackedS],
    [faCubesS], [#icons.faCubesS],
)])

#pagebreak()

== D-E

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faDS], [#icons.faDS],
    [faDatabaseS], [#icons.faDatabaseS],
    [faDeleteLeftS], [#icons.faDeleteLeftS],
    [faDemocratS], [#icons.faDemocratS],
    [faDesktopS], [#icons.faDesktopS],
    [faDharmachakraS], [#icons.faDharmachakraS],
    [faDiagramNextS], [#icons.faDiagramNextS],
    [faDiagramPredecessorS], [#icons.faDiagramPredecessorS],
    [faDiagramProjectS], [#icons.faDiagramProjectS],
    [faDiagramSuccessorS], [#icons.faDiagramSuccessorS],
    [faDiamondTurnRightS], [#icons.faDiamondTurnRightS],
    [faDiamondS], [#icons.faDiamondS],
    [faDiceD6S], [#icons.faDiceD6S],
    [faDiceD20S], [#icons.faDiceD20S],
    [faDiceFiveS], [#icons.faDiceFiveS],
    [faDiceFourS], [#icons.faDiceFourS],
    [faDiceOneS], [#icons.faDiceOneS],
    [faDiceSixS], [#icons.faDiceSixS],
    [faDiceThreeS], [#icons.faDiceThreeS],
    [faDiceTwoS], [#icons.faDiceTwoS],
    [faDiceS], [#icons.faDiceS],
    [faDiseaseS], [#icons.faDiseaseS],
    [faDisplayS], [#icons.faDisplayS],
    [faDivideS], [#icons.faDivideS],
    [faDnaS], [#icons.faDnaS],
    [faDogS], [#icons.faDogS],
    [faDollarSignS], [#icons.faDollarSignS],
    [faDollyS], [#icons.faDollyS],
    [faDongSignS], [#icons.faDongSignS],
    [faDoorClosedS], [#icons.faDoorClosedS],
    [faDoorOpenS], [#icons.faDoorOpenS],
    [faDoveS], [#icons.faDoveS],
    [faDownLeftAndUpRightToCenterS], [#icons.faDownLeftAndUpRightToCenterS],
    [faDownLongS], [#icons.faDownLongS],
    [faDownloadS], [#icons.faDownloadS],
    [faDragonS], [#icons.faDragonS],
    [faDrawPolygonS], [#icons.faDrawPolygonS],
    [faDropletSlashS], [#icons.faDropletSlashS],
    [faDropletS], [#icons.faDropletS],
    [faDrumSteelpanS], [#icons.faDrumSteelpanS],
    [faDrumS], [#icons.faDrumS],
    [faDrumstickBiteS], [#icons.faDrumstickBiteS],
    [faDumbbellS], [#icons.faDumbbellS],
    [faDumpsterFireS], [#icons.faDumpsterFireS],
    [faDumpsterS], [#icons.faDumpsterS],
    [faDungeonS], [#icons.faDungeonS],
    [faES], [#icons.faES],
    [faEarDeafS], [#icons.faEarDeafS],
    [faEarListenS], [#icons.faEarListenS],
    [faEarthAfricaS], [#icons.faEarthAfricaS],
    [faEarthAmericasS], [#icons.faEarthAmericasS],
    [faEarthAsiaS], [#icons.faEarthAsiaS],
    [faEarthEuropeS], [#icons.faEarthEuropeS],
    [faEarthOceaniaS], [#icons.faEarthOceaniaS],
    [faEggS], [#icons.faEggS],
    [faEjectS], [#icons.faEjectS],
    [faElevatorS], [#icons.faElevatorS],
    [faEllipsisVerticalS], [#icons.faEllipsisVerticalS],
    [faEllipsisS], [#icons.faEllipsisS],
    [faEnvelopeCircleCheckS], [#icons.faEnvelopeCircleCheckS],
    [faEnvelopeOpenTextS], [#icons.faEnvelopeOpenTextS],
    [faEnvelopeOpenS], [#icons.faEnvelopeOpenS],
    [faEnvelopeS], [#icons.faEnvelopeS],
    [faEnvelopesBulkS], [#icons.faEnvelopesBulkS],
    [faEqualsS], [#icons.faEqualsS],
    [faEraserS], [#icons.faEraserS],
    [faEthernetS], [#icons.faEthernetS],
    [faEuroSignS], [#icons.faEuroSignS],
    [faExclamationS], [#icons.faExclamationS],
    [faExpandS], [#icons.faExpandS],
    [faExplosionS], [#icons.faExplosionS],
    [faEyeDropperS], [#icons.faEyeDropperS],
    [faEyeLowVisionS], [#icons.faEyeLowVisionS],
    [faEyeSlashS], [#icons.faEyeSlashS],
    [faEyeS], [#icons.faEyeS],
)])

#pagebreak()

== F-Fl

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFS], [#icons.faFS],
    [faFaceAngryS], [#icons.faFaceAngryS],
    [faFaceDizzyS], [#icons.faFaceDizzyS],
    [faFaceFlushedS], [#icons.faFaceFlushedS],
    [faFaceFrownOpenS], [#icons.faFaceFrownOpenS],
    [faFaceFrownS], [#icons.faFaceFrownS],
    [faFaceGrimaceS], [#icons.faFaceGrimaceS],
    [faFaceGrinBeamSweatS], [#icons.faFaceGrinBeamSweatS],
    [faFaceGrinBeamS], [#icons.faFaceGrinBeamS],
    [faFaceGrinHeartsS], [#icons.faFaceGrinHeartsS],
    [faFaceGrinSquintTearsS], [#icons.faFaceGrinSquintTearsS],
    [faFaceGrinSquintS], [#icons.faFaceGrinSquintS],
    [faFaceGrinStarsS], [#icons.faFaceGrinStarsS],
    [faFaceGrinTearsS], [#icons.faFaceGrinTearsS],
    [faFaceGrinTongueSquintS], [#icons.faFaceGrinTongueSquintS],
    [faFaceGrinTongueWinkS], [#icons.faFaceGrinTongueWinkS],
    [faFaceGrinTongueS], [#icons.faFaceGrinTongueS],
    [faFaceGrinWideS], [#icons.faFaceGrinWideS],
    [faFaceGrinWinkS], [#icons.faFaceGrinWinkS],
    [faFaceGrinS], [#icons.faFaceGrinS],
    [faFaceKissBeamS], [#icons.faFaceKissBeamS],
    [faFaceKissWinkHeartS], [#icons.faFaceKissWinkHeartS],
    [faFaceKissS], [#icons.faFaceKissS],
    [faFaceLaughBeamS], [#icons.faFaceLaughBeamS],
    [faFaceLaughSquintS], [#icons.faFaceLaughSquintS],
    [faFaceLaughWinkS], [#icons.faFaceLaughWinkS],
    [faFaceLaughS], [#icons.faFaceLaughS],
    [faFaceMehBlankS], [#icons.faFaceMehBlankS],
    [faFaceMehS], [#icons.faFaceMehS],
    [faFaceRollingEyesS], [#icons.faFaceRollingEyesS],
    [faFaceSadCryS], [#icons.faFaceSadCryS],
    [faFaceSadTearS], [#icons.faFaceSadTearS],
    [faFaceSmileBeamS], [#icons.faFaceSmileBeamS],
    [faFaceSmileWinkS], [#icons.faFaceSmileWinkS],
    [faFaceSmileS], [#icons.faFaceSmileS],
    [faFaceSurpriseS], [#icons.faFaceSurpriseS],
    [faFaceTiredS], [#icons.faFaceTiredS],
    [faFanS], [#icons.faFanS],
    [faFaucetDripS], [#icons.faFaucetDripS],
    [faFaucetS], [#icons.faFaucetS],
    [faFaxS], [#icons.faFaxS],
    [faFeatherPointedS], [#icons.faFeatherPointedS],
    [faFeatherS], [#icons.faFeatherS],
    [faFerryS], [#icons.faFerryS],
    [faFileArrowDownS], [#icons.faFileArrowDownS],
    [faFileArrowUpS], [#icons.faFileArrowUpS],
    [faFileAudioS], [#icons.faFileAudioS],
    [faFileCircleCheckS], [#icons.faFileCircleCheckS],
    [faFileCircleExclamationS], [#icons.faFileCircleExclamationS],
    [faFileCircleMinusS], [#icons.faFileCircleMinusS],
    [faFileCirclePlusS], [#icons.faFileCirclePlusS],
    [faFileCircleQuestionS], [#icons.faFileCircleQuestionS],
    [faFileCircleXmarkS], [#icons.faFileCircleXmarkS],
    [faFileCodeS], [#icons.faFileCodeS],
    [faFileContractS], [#icons.faFileContractS],
    [faFileCsvS], [#icons.faFileCsvS],
    [faFileExcelS], [#icons.faFileExcelS],
    [faFileExportS], [#icons.faFileExportS],
    [faFileImageS], [#icons.faFileImageS],
    [faFileImportS], [#icons.faFileImportS],
    [faFileInvoiceDollarS], [#icons.faFileInvoiceDollarS],
    [faFileInvoiceS], [#icons.faFileInvoiceS],
    [faFileLinesS], [#icons.faFileLinesS],
    [faFileMedicalS], [#icons.faFileMedicalS],
    [faFilePdfS], [#icons.faFilePdfS],
    [faFilePenS], [#icons.faFilePenS],
    [faFilePowerpointS], [#icons.faFilePowerpointS],
    [faFilePrescriptionS], [#icons.faFilePrescriptionS],
    [faFileShieldS], [#icons.faFileShieldS],
    [faFileSignatureS], [#icons.faFileSignatureS],
    [faFileVideoS], [#icons.faFileVideoS],
    [faFileWaveformS], [#icons.faFileWaveformS],
    [faFileWordS], [#icons.faFileWordS],
    [faFileZipperS], [#icons.faFileZipperS],
    [faFileS], [#icons.faFileS],
    [faFillDripS], [#icons.faFillDripS],
    [faFillS], [#icons.faFillS],
    [faFilmS], [#icons.faFilmS],
    [faFilterCircleDollarS], [#icons.faFilterCircleDollarS],
    [faFilterCircleXmarkS], [#icons.faFilterCircleXmarkS],
    [faFilterS], [#icons.faFilterS],
    [faFingerprintS], [#icons.faFingerprintS],
    [faFireBurnerS], [#icons.faFireBurnerS],
    [faFireExtinguisherS], [#icons.faFireExtinguisherS],
    [faFireFlameCurvedS], [#icons.faFireFlameCurvedS],
    [faFireFlameSimpleS], [#icons.faFireFlameSimpleS],
    [faFireS], [#icons.faFireS],
    [faFishFinsS], [#icons.faFishFinsS],
    [faFishS], [#icons.faFishS],
    [faFlagCheckeredS], [#icons.faFlagCheckeredS],
    [faFlagUsaS], [#icons.faFlagUsaS],
    [faFlagS], [#icons.faFlagS],
    [faFlaskVialS], [#icons.faFlaskVialS],
    [faFlaskS], [#icons.faFlaskS],
    [faFloppyDiskS], [#icons.faFloppyDiskS],
    [faFlorinSignS], [#icons.faFlorinSignS],
)])

#pagebreak()

== Fo-Fu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFolderClosedS], [#icons.faFolderClosedS],
    [faFolderMinusS], [#icons.faFolderMinusS],
    [faFolderOpenS], [#icons.faFolderOpenS],
    [faFolderPlusS], [#icons.faFolderPlusS],
    [faFolderTreeS], [#icons.faFolderTreeS],
    [faFolderS], [#icons.faFolderS],
    [faFontAwesomeS], [#icons.faFontAwesomeS],
    [faFontS], [#icons.faFontS],
    [faFootballS], [#icons.faFootballS],
    [faForwardFastS], [#icons.faForwardFastS],
    [faForwardStepS], [#icons.faForwardStepS],
    [faForwardS], [#icons.faForwardS],
    [faFrancSignS], [#icons.faFrancSignS],
    [faFrogS], [#icons.faFrogS],
    [faFutbolS], [#icons.faFutbolS],
)])

== G

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faGS], [#icons.faGS],
    [faGamepadS], [#icons.faGamepadS],
    [faGasPumpS], [#icons.faGasPumpS],
    [faGaugeHighS], [#icons.faGaugeHighS],
    [faGaugeSimpleHighS], [#icons.faGaugeSimpleHighS],
    [faGaugeSimpleS], [#icons.faGaugeSimpleS],
    [faGaugeS], [#icons.faGaugeS],
    [faGavelS], [#icons.faGavelS],
    [faGearS], [#icons.faGearS],
    [faGearsS], [#icons.faGearsS],
    [faGemS], [#icons.faGemS],
    [faGenderlessS], [#icons.faGenderlessS],
    [faGhostS], [#icons.faGhostS],
    [faGiftS], [#icons.faGiftS],
    [faGiftsS], [#icons.faGiftsS],
    [faGlassWaterDropletS], [#icons.faGlassWaterDropletS],
    [faGlassWaterS], [#icons.faGlassWaterS],
    [faGlassesS], [#icons.faGlassesS],
    [faGlobeS], [#icons.faGlobeS],
    [faGolfBallTeeS], [#icons.faGolfBallTeeS],
    [faGopuramS], [#icons.faGopuramS],
    [faGraduationCapS], [#icons.faGraduationCapS],
    [faGreaterThanEqualS], [#icons.faGreaterThanEqualS],
    [faGreaterThanS], [#icons.faGreaterThanS],
    [faGripLinesVerticalS], [#icons.faGripLinesVerticalS],
    [faGripLinesS], [#icons.faGripLinesS],
    [faGripVerticalS], [#icons.faGripVerticalS],
    [faGripS], [#icons.faGripS],
    [faGroupArrowsRotateS], [#icons.faGroupArrowsRotateS],
    [faGuaraniSignS], [#icons.faGuaraniSignS],
    [faGuitarS], [#icons.faGuitarS],
    [faGunS], [#icons.faGunS],
)])

#pagebreak()

== H-Hi

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faHS], [#icons.faHS],
    [faHammerS], [#icons.faHammerS],
    [faHamsaS], [#icons.faHamsaS],
    [faHandBackFistS], [#icons.faHandBackFistS],
    [faHandDotsS], [#icons.faHandDotsS],
    [faHandFistS], [#icons.faHandFistS],
    [faHandHoldingDollarS], [#icons.faHandHoldingDollarS],
    [faHandHoldingDropletS], [#icons.faHandHoldingDropletS],
    [faHandHoldingHandS], [#icons.faHandHoldingHandS],
    [faHandHoldingHeartS], [#icons.faHandHoldingHeartS],
    [faHandHoldingMedicalS], [#icons.faHandHoldingMedicalS],
    [faHandHoldingS], [#icons.faHandHoldingS],
    [faHandLizardS], [#icons.faHandLizardS],
    [faHandMiddleFingerS], [#icons.faHandMiddleFingerS],
    [faHandPeaceS], [#icons.faHandPeaceS],
    [faHandPointDownS], [#icons.faHandPointDownS],
    [faHandPointLeftS], [#icons.faHandPointLeftS],
    [faHandPointRightS], [#icons.faHandPointRightS],
    [faHandPointUpS], [#icons.faHandPointUpS],
    [faHandPointerS], [#icons.faHandPointerS],
    [faHandScissorsS], [#icons.faHandScissorsS],
    [faHandSparklesS], [#icons.faHandSparklesS],
    [faHandSpockS], [#icons.faHandSpockS],
    [faHandS], [#icons.faHandS],
    [faHandcuffsS], [#icons.faHandcuffsS],
    [faHandsAslInterpretingS], [#icons.faHandsAslInterpretingS],
    [faHandsBoundS], [#icons.faHandsBoundS],
    [faHandsBubblesS], [#icons.faHandsBubblesS],
    [faHandsClappingS], [#icons.faHandsClappingS],
    [faHandsHoldingChildS], [#icons.faHandsHoldingChildS],
    [faHandsHoldingCircleS], [#icons.faHandsHoldingCircleS],
    [faHandsHoldingS], [#icons.faHandsHoldingS],
    [faHandsPrayingS], [#icons.faHandsPrayingS],
    [faHandsS], [#icons.faHandsS],
    [faHandshakeAngleS], [#icons.faHandshakeAngleS],
    [faHandshakeSimpleSlashS], [#icons.faHandshakeSimpleSlashS],
    [faHandshakeSimpleS], [#icons.faHandshakeSimpleS],
    [faHandshakeSlashS], [#icons.faHandshakeSlashS],
    [faHandshakeS], [#icons.faHandshakeS],
    [faHanukiahS], [#icons.faHanukiahS],
    [faHardDriveS], [#icons.faHardDriveS],
    [faHashtagS], [#icons.faHashtagS],
    [faHatCowboySideS], [#icons.faHatCowboySideS],
    [faHatCowboyS], [#icons.faHatCowboyS],
    [faHatWizardS], [#icons.faHatWizardS],
    [faHeadSideCoughSlashS], [#icons.faHeadSideCoughSlashS],
    [faHeadSideCoughS], [#icons.faHeadSideCoughS],
    [faHeadSideMaskS], [#icons.faHeadSideMaskS],
    [faHeadSideVirusS], [#icons.faHeadSideVirusS],
    [faHeadingS], [#icons.faHeadingS],
    [faHeadphonesSimpleS], [#icons.faHeadphonesSimpleS],
    [faHeadphonesS], [#icons.faHeadphonesS],
    [faHeadsetS], [#icons.faHeadsetS],
    [faHeartCircleBoltS], [#icons.faHeartCircleBoltS],
    [faHeartCircleCheckS], [#icons.faHeartCircleCheckS],
    [faHeartCircleExclamationS], [#icons.faHeartCircleExclamationS],
    [faHeartCircleMinusS], [#icons.faHeartCircleMinusS],
    [faHeartCirclePlusS], [#icons.faHeartCirclePlusS],
    [faHeartCircleXmarkS], [#icons.faHeartCircleXmarkS],
    [faHeartCrackS], [#icons.faHeartCrackS],
    [faHeartPulseS], [#icons.faHeartPulseS],
    [faHeartS], [#icons.faHeartS],
    [faHelicopterSymbolS], [#icons.faHelicopterSymbolS],
    [faHelicopterS], [#icons.faHelicopterS],
    [faHelmetSafetyS], [#icons.faHelmetSafetyS],
    [faHelmetUnS], [#icons.faHelmetUnS],
    [faHighlighterS], [#icons.faHighlighterS],
    [faHillAvalancheS], [#icons.faHillAvalancheS],
    [faHillRockslideS], [#icons.faHillRockslideS],
    [faHippoS], [#icons.faHippoS],
)])

#pagebreak()

== Ho

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faHockeyPuckS], [#icons.faHockeyPuckS],
    [faHollyBerryS], [#icons.faHollyBerryS],
    [faHorseHeadS], [#icons.faHorseHeadS],
    [faHorseS], [#icons.faHorseS],
    [faHospitalUserS], [#icons.faHospitalUserS],
    [faHospitalS], [#icons.faHospitalS],
    [faHotTubPersonS], [#icons.faHotTubPersonS],
    [faHotdogS], [#icons.faHotdogS],
    [faHotelS], [#icons.faHotelS],
    [faHourglassEndS], [#icons.faHourglassEndS],
    [faHourglassHalfS], [#icons.faHourglassHalfS],
    [faHourglassStartS], [#icons.faHourglassStartS],
    [faHourglassS], [#icons.faHourglassS],
    [faHouseChimneyCrackS], [#icons.faHouseChimneyCrackS],
    [faHouseChimneyMedicalS], [#icons.faHouseChimneyMedicalS],
    [faHouseChimneyUserS], [#icons.faHouseChimneyUserS],
    [faHouseChimneyWindowS], [#icons.faHouseChimneyWindowS],
    [faHouseChimneyS], [#icons.faHouseChimneyS],
    [faHouseCircleCheckS], [#icons.faHouseCircleCheckS],
    [faHouseCircleExclamationS], [#icons.faHouseCircleExclamationS],
    [faHouseCircleXmarkS], [#icons.faHouseCircleXmarkS],
    [faHouseCrackS], [#icons.faHouseCrackS],
    [faHouseFireS], [#icons.faHouseFireS],
    [faHouseFlagS], [#icons.faHouseFlagS],
    [faHouseFloodWaterCircleArrowRightS], [#icons.faHouseFloodWaterCircleArrowRightS],
    [faHouseFloodWaterS], [#icons.faHouseFloodWaterS],
    [faHouseLaptopS], [#icons.faHouseLaptopS],
    [faHouseLockS], [#icons.faHouseLockS],
    [faHouseMedicalCircleCheckS], [#icons.faHouseMedicalCircleCheckS],
    [faHouseMedicalCircleExclamationS], [#icons.faHouseMedicalCircleExclamationS],
    [faHouseMedicalCircleXmarkS], [#icons.faHouseMedicalCircleXmarkS],
    [faHouseMedicalFlagS], [#icons.faHouseMedicalFlagS],
    [faHouseMedicalS], [#icons.faHouseMedicalS],
    [faHouseSignalS], [#icons.faHouseSignalS],
    [faHouseTsunamiS], [#icons.faHouseTsunamiS],
    [faHouseUserS], [#icons.faHouseUserS],
    [faHouseS], [#icons.faHouseS],
    [faHryvniaSignS], [#icons.faHryvniaSignS],
    [faHurricaneS], [#icons.faHurricaneS],
    [faICursorS], [#icons.faICursorS],
)])

== I-J

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faIS], [#icons.faIS],
    [faIceCreamS], [#icons.faIceCreamS],
    [faIciclesS], [#icons.faIciclesS],
    [faIconsS], [#icons.faIconsS],
    [faIdBadgeS], [#icons.faIdBadgeS],
    [faIdCardClipS], [#icons.faIdCardClipS],
    [faIdCardS], [#icons.faIdCardS],
    [faIglooS], [#icons.faIglooS],
    [faImagePortraitS], [#icons.faImagePortraitS],
    [faImageS], [#icons.faImageS],
    [faImagesS], [#icons.faImagesS],
    [faInboxS], [#icons.faInboxS],
    [faIndentS], [#icons.faIndentS],
    [faIndianRupeeSignS], [#icons.faIndianRupeeSignS],
    [faIndustryS], [#icons.faIndustryS],
    [faInfinityS], [#icons.faInfinityS],
    [faInfoS], [#icons.faInfoS],
    [faItalicS], [#icons.faItalicS],
    [faJS], [#icons.faJS],
    [faJarWheatS], [#icons.faJarWheatS],
    [faJarS], [#icons.faJarS],
    [faJediS], [#icons.faJediS],
    [faJetFighterUpS], [#icons.faJetFighterUpS],
    [faJetFighterS], [#icons.faJetFighterS],
    [faJointS], [#icons.faJointS],
    [faJugDetergentS], [#icons.faJugDetergentS],
    [faKS], [#icons.faKS],
    [faKaabaS], [#icons.faKaabaS],
    [faKeyS], [#icons.faKeyS],
    [faKeyboardS], [#icons.faKeyboardS],
    [faKhandaS], [#icons.faKhandaS],
    [faKipSignS], [#icons.faKipSignS],
    [faKitMedicalS], [#icons.faKitMedicalS],
    [faKitchenSetS], [#icons.faKitchenSetS],
    [faKiwiBirdS], [#icons.faKiwiBirdS],
)])

#pagebreak()

== L

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faLS], [#icons.faLS],
    [faLandMineOnS], [#icons.faLandMineOnS],
    [faLandmarkDomeS], [#icons.faLandmarkDomeS],
    [faLandmarkFlagS], [#icons.faLandmarkFlagS],
    [faLandmarkS], [#icons.faLandmarkS],
    [faLanguageS], [#icons.faLanguageS],
    [faLaptopCodeS], [#icons.faLaptopCodeS],
    [faLaptopFileS], [#icons.faLaptopFileS],
    [faLaptopMedicalS], [#icons.faLaptopMedicalS],
    [faLaptopS], [#icons.faLaptopS],
    [faLariSignS], [#icons.faLariSignS],
    [faLayerGroupS], [#icons.faLayerGroupS],
    [faLeafS], [#icons.faLeafS],
    [faLeftLongS], [#icons.faLeftLongS],
    [faLeftRightS], [#icons.faLeftRightS],
    [faLemonS], [#icons.faLemonS],
    [faLessThanEqualS], [#icons.faLessThanEqualS],
    [faLessThanS], [#icons.faLessThanS],
    [faLifeRingS], [#icons.faLifeRingS],
    [faLightbulbS], [#icons.faLightbulbS],
    [faLinesLeaningS], [#icons.faLinesLeaningS],
    [faLinkSlashS], [#icons.faLinkSlashS],
    [faLinkS], [#icons.faLinkS],
    [faLiraSignS], [#icons.faLiraSignS],
    [faListCheckS], [#icons.faListCheckS],
    [faListOlS], [#icons.faListOlS],
    [faListUlS], [#icons.faListUlS],
    [faListS], [#icons.faListS],
    [faLitecoinSignS], [#icons.faLitecoinSignS],
    [faLocationArrowS], [#icons.faLocationArrowS],
    [faLocationCrosshairsS], [#icons.faLocationCrosshairsS],
    [faLocationDotS], [#icons.faLocationDotS],
    [faLocationPinLockS], [#icons.faLocationPinLockS],
    [faLocationPinS], [#icons.faLocationPinS],
    [faLockOpenS], [#icons.faLockOpenS],
    [faLockS], [#icons.faLockS],
    [faLocustS], [#icons.faLocustS],
    [faLungsVirusS], [#icons.faLungsVirusS],
    [faLungsS], [#icons.faLungsS],
)])

== M-Mi

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faMS], [#icons.faMS],
    [faMagnetS], [#icons.faMagnetS],
    [faMagnifyingGlassArrowRightS], [#icons.faMagnifyingGlassArrowRightS],
    [faMagnifyingGlassChartS], [#icons.faMagnifyingGlassChartS],
    [faMagnifyingGlassDollarS], [#icons.faMagnifyingGlassDollarS],
    [faMagnifyingGlassLocationS], [#icons.faMagnifyingGlassLocationS],
    [faMagnifyingGlassMinusS], [#icons.faMagnifyingGlassMinusS],
    [faMagnifyingGlassPlusS], [#icons.faMagnifyingGlassPlusS],
    [faMagnifyingGlassS], [#icons.faMagnifyingGlassS],
    [faManatSignS], [#icons.faManatSignS],
    [faMapLocationDotS], [#icons.faMapLocationDotS],
    [faMapLocationS], [#icons.faMapLocationS],
    [faMapPinS], [#icons.faMapPinS],
    [faMapS], [#icons.faMapS],
    [faMarkerS], [#icons.faMarkerS],
    [faMarsAndVenusBurstS], [#icons.faMarsAndVenusBurstS],
    [faMarsAndVenusS], [#icons.faMarsAndVenusS],
    [faMarsDoubleS], [#icons.faMarsDoubleS],
    [faMarsStrokeRightS], [#icons.faMarsStrokeRightS],
    [faMarsStrokeUpS], [#icons.faMarsStrokeUpS],
    [faMarsStrokeS], [#icons.faMarsStrokeS],
    [faMarsS], [#icons.faMarsS],
    [faMartiniGlassCitrusS], [#icons.faMartiniGlassCitrusS],
    [faMartiniGlassEmptyS], [#icons.faMartiniGlassEmptyS],
    [faMartiniGlassS], [#icons.faMartiniGlassS],
    [faMaskFaceS], [#icons.faMaskFaceS],
    [faMaskVentilatorS], [#icons.faMaskVentilatorS],
    [faMaskS], [#icons.faMaskS],
    [faMasksTheaterS], [#icons.faMasksTheaterS],
    [faMattressPillowS], [#icons.faMattressPillowS],
    [faMaximizeS], [#icons.faMaximizeS],
    [faMedalS], [#icons.faMedalS],
    [faMemoryS], [#icons.faMemoryS],
    [faMenorahS], [#icons.faMenorahS],
    [faMercuryS], [#icons.faMercuryS],
    [faMessageS], [#icons.faMessageS],
    [faMeteorS], [#icons.faMeteorS],
    [faMicrochipS], [#icons.faMicrochipS],
    [faMicrophoneLinesSlashS], [#icons.faMicrophoneLinesSlashS],
    [faMicrophoneLinesS], [#icons.faMicrophoneLinesS],
    [faMicrophoneSlashS], [#icons.faMicrophoneSlashS],
    [faMicrophoneS], [#icons.faMicrophoneS],
    [faMicroscopeS], [#icons.faMicroscopeS],
    [faMillSignS], [#icons.faMillSignS],
    [faMinimizeS], [#icons.faMinimizeS],
    [faMinusS], [#icons.faMinusS],
    [faMittenS], [#icons.faMittenS],
)])

#pagebreak()

== Mo-Mu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faMobileButtonS], [#icons.faMobileButtonS],
    [faMobileRetroS], [#icons.faMobileRetroS],
    [faMobileScreenButtonS], [#icons.faMobileScreenButtonS],
    [faMobileScreenS], [#icons.faMobileScreenS],
    [faMobileS], [#icons.faMobileS],
    [faMoneyBill1WaveS], [#icons.faMoneyBill1WaveS],
    [faMoneyBill1S], [#icons.faMoneyBill1S],
    [faMoneyBillTransferS], [#icons.faMoneyBillTransferS],
    [faMoneyBillTrendUpS], [#icons.faMoneyBillTrendUpS],
    [faMoneyBillWaveS], [#icons.faMoneyBillWaveS],
    [faMoneyBillWheatS], [#icons.faMoneyBillWheatS],
    [faMoneyBillS], [#icons.faMoneyBillS],
    [faMoneyBillsS], [#icons.faMoneyBillsS],
    [faMoneyCheckDollarS], [#icons.faMoneyCheckDollarS],
    [faMoneyCheckS], [#icons.faMoneyCheckS],
    [faMonumentS], [#icons.faMonumentS],
    [faMoonS], [#icons.faMoonS],
    [faMortarPestleS], [#icons.faMortarPestleS],
    [faMosqueS], [#icons.faMosqueS],
    [faMosquitoNetS], [#icons.faMosquitoNetS],
    [faMosquitoS], [#icons.faMosquitoS],
    [faMotorcycleS], [#icons.faMotorcycleS],
    [faMoundS], [#icons.faMoundS],
    [faMountainCityS], [#icons.faMountainCityS],
    [faMountainSunS], [#icons.faMountainSunS],
    [faMountainS], [#icons.faMountainS],
    [faMugHotS], [#icons.faMugHotS],
    [faMugSaucerS], [#icons.faMugSaucerS],
    [faMusicS], [#icons.faMusicS],
)])

== N

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faNS], [#icons.faNS],
    [faNairaSignS], [#icons.faNairaSignS],
    [faNetworkWiredS], [#icons.faNetworkWiredS],
    [faNeuterS], [#icons.faNeuterS],
    [faNewspaperS], [#icons.faNewspaperS],
    [faNotEqualS], [#icons.faNotEqualS],
    [faNotdefS], [#icons.faNotdefS],
    [faNoteStickyS], [#icons.faNoteStickyS],
    [faNotesMedicalS], [#icons.faNotesMedicalS],
    [faOS], [#icons.faOS],
    [faObjectGroupS], [#icons.faObjectGroupS],
    [faObjectUngroupS], [#icons.faObjectUngroupS],
    [faOilCanS], [#icons.faOilCanS],
    [faOilWellS], [#icons.faOilWellS],
    [faOmS], [#icons.faOmS],
    [faOtterS], [#icons.faOtterS],
    [faOutdentS], [#icons.faOutdentS],
)])

== P-Pep

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faPS], [#icons.faPS],
    [faPagerS], [#icons.faPagerS],
    [faPaintRollerS], [#icons.faPaintRollerS],
    [faPaintbrushS], [#icons.faPaintbrushS],
    [faPaletteS], [#icons.faPaletteS],
    [faPalletS], [#icons.faPalletS],
    [faPanoramaS], [#icons.faPanoramaS],
    [faPaperPlaneS], [#icons.faPaperPlaneS],
    [faPaperclipS], [#icons.faPaperclipS],
    [faParachuteBoxS], [#icons.faParachuteBoxS],
    [faParagraphS], [#icons.faParagraphS],
    [faPassportS], [#icons.faPassportS],
    [faPasteS], [#icons.faPasteS],
    [faPauseS], [#icons.faPauseS],
    [faPawS], [#icons.faPawS],
    [faPeaceS], [#icons.faPeaceS],
    [faPenClipS], [#icons.faPenClipS],
    [faPenFancyS], [#icons.faPenFancyS],
    [faPenNibS], [#icons.faPenNibS],
    [faPenRulerS], [#icons.faPenRulerS],
    [faPenToSquareS], [#icons.faPenToSquareS],
    [faPenS], [#icons.faPenS],
    [faPencilS], [#icons.faPencilS],
    [faPeopleArrowsS], [#icons.faPeopleArrowsS],
    [faPeopleCarryBoxS], [#icons.faPeopleCarryBoxS],
    [faPeopleGroupS], [#icons.faPeopleGroupS],
    [faPeopleLineS], [#icons.faPeopleLineS],
    [faPeoplePullingS], [#icons.faPeoplePullingS],
    [faPeopleRobberyS], [#icons.faPeopleRobberyS],
    [faPeopleRoofS], [#icons.faPeopleRoofS],
    [faPepperHotS], [#icons.faPepperHotS],
)])

#pagebreak()

== Per-Pu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faPercentS], [#icons.faPercentS],
    [faPersonArrowDownToLineS], [#icons.faPersonArrowDownToLineS],
    [faPersonArrowUpFromLineS], [#icons.faPersonArrowUpFromLineS],
    [faPersonBikingS], [#icons.faPersonBikingS],
    [faPersonBoothS], [#icons.faPersonBoothS],
    [faPersonBreastfeedingS], [#icons.faPersonBreastfeedingS],
    [faPersonBurstS], [#icons.faPersonBurstS],
    [faPersonCaneS], [#icons.faPersonCaneS],
    [faPersonChalkboardS], [#icons.faPersonChalkboardS],
    [faPersonCircleCheckS], [#icons.faPersonCircleCheckS],
    [faPersonCircleExclamationS], [#icons.faPersonCircleExclamationS],
    [faPersonCircleMinusS], [#icons.faPersonCircleMinusS],
    [faPersonCirclePlusS], [#icons.faPersonCirclePlusS],
    [faPersonCircleQuestionS], [#icons.faPersonCircleQuestionS],
    [faPersonCircleXmarkS], [#icons.faPersonCircleXmarkS],
    [faPersonDiggingS], [#icons.faPersonDiggingS],
    [faPersonDotsFromLineS], [#icons.faPersonDotsFromLineS],
    [faPersonDressBurstS], [#icons.faPersonDressBurstS],
    [faPersonDressS], [#icons.faPersonDressS],
    [faPersonDrowningS], [#icons.faPersonDrowningS],
    [faPersonFallingBurstS], [#icons.faPersonFallingBurstS],
    [faPersonFallingS], [#icons.faPersonFallingS],
    [faPersonHalfDressS], [#icons.faPersonHalfDressS],
    [faPersonHarassingS], [#icons.faPersonHarassingS],
    [faPersonHikingS], [#icons.faPersonHikingS],
    [faPersonMilitaryPointingS], [#icons.faPersonMilitaryPointingS],
    [faPersonMilitaryRifleS], [#icons.faPersonMilitaryRifleS],
    [faPersonMilitaryToPersonS], [#icons.faPersonMilitaryToPersonS],
    [faPersonPrayingS], [#icons.faPersonPrayingS],
    [faPersonPregnantS], [#icons.faPersonPregnantS],
    [faPersonRaysS], [#icons.faPersonRaysS],
    [faPersonRifleS], [#icons.faPersonRifleS],
    [faPersonRunningS], [#icons.faPersonRunningS],
    [faPersonShelterS], [#icons.faPersonShelterS],
    [faPersonSkatingS], [#icons.faPersonSkatingS],
    [faPersonSkiingNordicS], [#icons.faPersonSkiingNordicS],
    [faPersonSkiingS], [#icons.faPersonSkiingS],
    [faPersonSnowboardingS], [#icons.faPersonSnowboardingS],
    [faPersonSwimmingS], [#icons.faPersonSwimmingS],
    [faPersonThroughWindowS], [#icons.faPersonThroughWindowS],
    [faPersonWalkingArrowLoopLeftS], [#icons.faPersonWalkingArrowLoopLeftS],
    [faPersonWalkingArrowRightS], [#icons.faPersonWalkingArrowRightS],
    [faPersonWalkingDashedLineArrowRightS], [#icons.faPersonWalkingDashedLineArrowRightS],
    [faPersonWalkingLuggageS], [#icons.faPersonWalkingLuggageS],
    [faPersonWalkingWithCaneS], [#icons.faPersonWalkingWithCaneS],
    [faPersonWalkingS], [#icons.faPersonWalkingS],
    [faPersonS], [#icons.faPersonS],
    [faPesetaSignS], [#icons.faPesetaSignS],
    [faPesoSignS], [#icons.faPesoSignS],
    [faPhoneFlipS], [#icons.faPhoneFlipS],
    [faPhoneSlashS], [#icons.faPhoneSlashS],
    [faPhoneVolumeS], [#icons.faPhoneVolumeS],
    [faPhoneS], [#icons.faPhoneS],
    [faPhotoFilmS], [#icons.faPhotoFilmS],
    [faPiggyBankS], [#icons.faPiggyBankS],
    [faPillsS], [#icons.faPillsS],
    [faPizzaSliceS], [#icons.faPizzaSliceS],
    [faPlaceOfWorshipS], [#icons.faPlaceOfWorshipS],
    [faPlaneArrivalS], [#icons.faPlaneArrivalS],
    [faPlaneCircleCheckS], [#icons.faPlaneCircleCheckS],
    [faPlaneCircleExclamationS], [#icons.faPlaneCircleExclamationS],
    [faPlaneCircleXmarkS], [#icons.faPlaneCircleXmarkS],
    [faPlaneDepartureS], [#icons.faPlaneDepartureS],
    [faPlaneLockS], [#icons.faPlaneLockS],
    [faPlaneSlashS], [#icons.faPlaneSlashS],
    [faPlaneUpS], [#icons.faPlaneUpS],
    [faPlaneS], [#icons.faPlaneS],
    [faPlantWiltS], [#icons.faPlantWiltS],
    [faPlateWheatS], [#icons.faPlateWheatS],
    [faPlayS], [#icons.faPlayS],
    [faPlugCircleBoltS], [#icons.faPlugCircleBoltS],
    [faPlugCircleCheckS], [#icons.faPlugCircleCheckS],
    [faPlugCircleExclamationS], [#icons.faPlugCircleExclamationS],
    [faPlugCircleMinusS], [#icons.faPlugCircleMinusS],
    [faPlugCirclePlusS], [#icons.faPlugCirclePlusS],
    [faPlugCircleXmarkS], [#icons.faPlugCircleXmarkS],
    [faPlugS], [#icons.faPlugS],
    [faPlusMinusS], [#icons.faPlusMinusS],
    [faPlusS], [#icons.faPlusS],
    [faPodcastS], [#icons.faPodcastS],
    [faPooStormS], [#icons.faPooStormS],
    [faPooS], [#icons.faPooS],
    [faPoopS], [#icons.faPoopS],
    [faPowerOffS], [#icons.faPowerOffS],
    [faPrescriptionBottleMedicalS], [#icons.faPrescriptionBottleMedicalS],
    [faPrescriptionBottleS], [#icons.faPrescriptionBottleS],
    [faPrescriptionS], [#icons.faPrescriptionS],
    [faPrintS], [#icons.faPrintS],
    [faPumpMedicalS], [#icons.faPumpMedicalS],
    [faPumpSoapS], [#icons.faPumpSoapS],
    [faPuzzlePieceS], [#icons.faPuzzlePieceS],
)])

== Q-R

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faQS], [#icons.faQS],
    [faQrcodeS], [#icons.faQrcodeS],
    [faQuestionS], [#icons.faQuestionS],
    [faQuoteLeftS], [#icons.faQuoteLeftS],
    [faQuoteRightS], [#icons.faQuoteRightS],
    [faRS], [#icons.faRS],
    [faRadiationS], [#icons.faRadiationS],
    [faRadioS], [#icons.faRadioS],
    [faRainbowS], [#icons.faRainbowS],
    [faRankingStarS], [#icons.faRankingStarS],
    [faReceiptS], [#icons.faReceiptS],
    [faRecordVinylS], [#icons.faRecordVinylS],
    [faRectangleAdS], [#icons.faRectangleAdS],
    [faRectangleListS], [#icons.faRectangleListS],
    [faRectangleXmarkS], [#icons.faRectangleXmarkS],
    [faRecycleS], [#icons.faRecycleS],
    [faRegisteredS], [#icons.faRegisteredS],
    [faRepeatS], [#icons.faRepeatS],
    [faReplyAllS], [#icons.faReplyAllS],
    [faReplyS], [#icons.faReplyS],
    [faRepublicanS], [#icons.faRepublicanS],
    [faRestroomS], [#icons.faRestroomS],
    [faRetweetS], [#icons.faRetweetS],
    [faRibbonS], [#icons.faRibbonS],
    [faRightFromBracketS], [#icons.faRightFromBracketS],
    [faRightLeftS], [#icons.faRightLeftS],
    [faRightLongS], [#icons.faRightLongS],
    [faRightToBracketS], [#icons.faRightToBracketS],
    [faRingS], [#icons.faRingS],
    [faRoadBarrierS], [#icons.faRoadBarrierS],
    [faRoadBridgeS], [#icons.faRoadBridgeS],
    [faRoadCircleCheckS], [#icons.faRoadCircleCheckS],
    [faRoadCircleExclamationS], [#icons.faRoadCircleExclamationS],
    [faRoadCircleXmarkS], [#icons.faRoadCircleXmarkS],
    [faRoadLockS], [#icons.faRoadLockS],
    [faRoadSpikesS], [#icons.faRoadSpikesS],
    [faRoadS], [#icons.faRoadS],
    [faRobotS], [#icons.faRobotS],
    [faRocketS], [#icons.faRocketS],
    [faRotateLeftS], [#icons.faRotateLeftS],
    [faRotateRightS], [#icons.faRotateRightS],
    [faRotateS], [#icons.faRotateS],
    [faRouteS], [#icons.faRouteS],
    [faRssS], [#icons.faRssS],
    [faRubleSignS], [#icons.faRubleSignS],
    [faRugS], [#icons.faRugS],
    [faRulerCombinedS], [#icons.faRulerCombinedS],
    [faRulerHorizontalS], [#icons.faRulerHorizontalS],
    [faRulerVerticalS], [#icons.faRulerVerticalS],
    [faRulerS], [#icons.faRulerS],
    [faRupeeSignS], [#icons.faRupeeSignS],
    [faRupiahSignS], [#icons.faRupiahSignS],
)])

== S-Se

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faSS], [#icons.faSS],
    [faSackDollarS], [#icons.faSackDollarS],
    [faSackXmarkS], [#icons.faSackXmarkS],
    [faSailboatS], [#icons.faSailboatS],
    [faSatelliteDishS], [#icons.faSatelliteDishS],
    [faSatelliteS], [#icons.faSatelliteS],
    [faScaleBalancedS], [#icons.faScaleBalancedS],
    [faScaleUnbalancedFlipS], [#icons.faScaleUnbalancedFlipS],
    [faScaleUnbalancedS], [#icons.faScaleUnbalancedS],
    [faSchoolCircleCheckS], [#icons.faSchoolCircleCheckS],
    [faSchoolCircleExclamationS], [#icons.faSchoolCircleExclamationS],
    [faSchoolCircleXmarkS], [#icons.faSchoolCircleXmarkS],
    [faSchoolFlagS], [#icons.faSchoolFlagS],
    [faSchoolLockS], [#icons.faSchoolLockS],
    [faSchoolS], [#icons.faSchoolS],
    [faScissorsS], [#icons.faScissorsS],
    [faScrewdriverWrenchS], [#icons.faScrewdriverWrenchS],
    [faScrewdriverS], [#icons.faScrewdriverS],
    [faScrollTorahS], [#icons.faScrollTorahS],
    [faScrollS], [#icons.faScrollS],
    [faSdCardS], [#icons.faSdCardS],
    [faSectionS], [#icons.faSectionS],
    [faSeedlingS], [#icons.faSeedlingS],
    [faServerS], [#icons.faServerS],
)])

#pagebreak()

== Sh-Sq

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faShapesS], [#icons.faShapesS],
    [faShareFromSquareS], [#icons.faShareFromSquareS],
    [faShareNodesS], [#icons.faShareNodesS],
    [faShareS], [#icons.faShareS],
    [faSheetPlasticS], [#icons.faSheetPlasticS],
    [faShekelSignS], [#icons.faShekelSignS],
    [faShieldCatS], [#icons.faShieldCatS],
    [faShieldDogS], [#icons.faShieldDogS],
    [faShieldHalvedS], [#icons.faShieldHalvedS],
    [faShieldHeartS], [#icons.faShieldHeartS],
    [faShieldVirusS], [#icons.faShieldVirusS],
    [faShieldS], [#icons.faShieldS],
    [faShipS], [#icons.faShipS],
    [faShirtS], [#icons.faShirtS],
    [faShoePrintsS], [#icons.faShoePrintsS],
    [faShopLockS], [#icons.faShopLockS],
    [faShopSlashS], [#icons.faShopSlashS],
    [faShopS], [#icons.faShopS],
    [faShowerS], [#icons.faShowerS],
    [faShrimpS], [#icons.faShrimpS],
    [faShuffleS], [#icons.faShuffleS],
    [faShuttleSpaceS], [#icons.faShuttleSpaceS],
    [faSignHangingS], [#icons.faSignHangingS],
    [faSignalS], [#icons.faSignalS],
    [faSignatureS], [#icons.faSignatureS],
    [faSignsPostS], [#icons.faSignsPostS],
    [faSimCardS], [#icons.faSimCardS],
    [faSinkS], [#icons.faSinkS],
    [faSitemapS], [#icons.faSitemapS],
    [faSkullCrossbonesS], [#icons.faSkullCrossbonesS],
    [faSkullS], [#icons.faSkullS],
    [faSlashS], [#icons.faSlashS],
    [faSleighS], [#icons.faSleighS],
    [faSlidersS], [#icons.faSlidersS],
    [faSmogS], [#icons.faSmogS],
    [faSmokingS], [#icons.faSmokingS],
    [faSnowflakeS], [#icons.faSnowflakeS],
    [faSnowmanS], [#icons.faSnowmanS],
    [faSnowplowS], [#icons.faSnowplowS],
    [faSoapS], [#icons.faSoapS],
    [faSocksS], [#icons.faSocksS],
    [faSolarPanelS], [#icons.faSolarPanelS],
    [faSortDownS], [#icons.faSortDownS],
    [faSortUpS], [#icons.faSortUpS],
    [faSortS], [#icons.faSortS],
    [faSpaS], [#icons.faSpaS],
    [faSpaghettiMonsterFlyingS], [#icons.faSpaghettiMonsterFlyingS],
    [faSpellCheckS], [#icons.faSpellCheckS],
    [faSpiderS], [#icons.faSpiderS],
    [faSpinnerS], [#icons.faSpinnerS],
    [faSplotchS], [#icons.faSplotchS],
    [faSpoonS], [#icons.faSpoonS],
    [faSprayCanSparklesS], [#icons.faSprayCanSparklesS],
    [faSprayCanS], [#icons.faSprayCanS],
    [faSquareArrowUpRightS], [#icons.faSquareArrowUpRightS],
    [faSquareCaretDownS], [#icons.faSquareCaretDownS],
    [faSquareCaretLeftS], [#icons.faSquareCaretLeftS],
    [faSquareCaretRightS], [#icons.faSquareCaretRightS],
    [faSquareCaretUpS], [#icons.faSquareCaretUpS],
    [faSquareCheckS], [#icons.faSquareCheckS],
    [faSquareEnvelopeS], [#icons.faSquareEnvelopeS],
    [faSquareFullS], [#icons.faSquareFullS],
    [faSquareHS], [#icons.faSquareHS],
    [faSquareMinusS], [#icons.faSquareMinusS],
    [faSquareNfiS], [#icons.faSquareNfiS],
    [faSquareParkingS], [#icons.faSquareParkingS],
    [faSquarePenS], [#icons.faSquarePenS],
    [faSquarePersonConfinedS], [#icons.faSquarePersonConfinedS],
    [faSquarePhoneFlipS], [#icons.faSquarePhoneFlipS],
    [faSquarePhoneS], [#icons.faSquarePhoneS],
    [faSquarePlusS], [#icons.faSquarePlusS],
    [faSquarePollHorizontalS], [#icons.faSquarePollHorizontalS],
    [faSsquarePollVerticalS], [#icons.faSsquarePollVerticalS],
    [faSquareRootVariableS], [#icons.faSquareRootVariableS],
    [faSquareRssS], [#icons.faSquareRssS],
    [faSquareShareNodesS], [#icons.faSquareShareNodesS],
    [faSquareUpRightS], [#icons.faSquareUpRightS],
    [faSquareVirusS], [#icons.faSquareVirusS],
    [faSquareXmarkS], [#icons.faSquareXmarkS],
    [faSquareS], [#icons.faSquareS],
)])

#pagebreak()

== St-Sy

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faStaffSnakeS], [#icons.faStaffSnakeS],
    [faStairsS], [#icons.faStairsS],
    [faStampS], [#icons.faStampS],
    [faStaplerS], [#icons.faStaplerS],
    [faStarAndCrescentS], [#icons.faStarAndCrescentS],
    [faStarHalfStrokeS], [#icons.faStarHalfStrokeS],
    [faStarHalfS], [#icons.faStarHalfS],
    [faStarOfDavidS], [#icons.faStarOfDavidS],
    [faStarOfLifeS], [#icons.faStarOfLifeS],
    [faStarS], [#icons.faStarS],
    [faSterlingSignS], [#icons.faSterlingSignS],
    [faStethoscopeS], [#icons.faStethoscopeS],
    [faStopS], [#icons.faStopS],
    [faStopwatch20S], [#icons.faStopwatch20S],
    [faStopwatchS], [#icons.faStopwatchS],
    [faStoreSlashS], [#icons.faStoreSlashS],
    [faStoreS], [#icons.faStoreS],
    [faStreetViewS], [#icons.faStreetViewS],
    [faStrikethroughS], [#icons.faStrikethroughS],
    [faStroopwafelS], [#icons.faStroopwafelS],
    [faSubscriptS], [#icons.faSubscriptS],
    [faSuitcaseMedicalS], [#icons.faSuitcaseMedicalS],
    [faSuitcaseRollingS], [#icons.faSuitcaseRollingS],
    [faSuitcaseS], [#icons.faSuitcaseS],
    [faSunPlantWiltS], [#icons.faSunPlantWiltS],
    [faSunS], [#icons.faSunS],
    [faSuperscriptS], [#icons.faSuperscriptS],
    [faSwatchbookS], [#icons.faSwatchbookS],
    [faSynagogueS], [#icons.faSynagogueS],
    [faSyringeS], [#icons.faSyringeS],
)])

== T-Ti

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faTS], [#icons.faTS],
    [faTableCellsLargeS], [#icons.faTableCellsLargeS],
    [faTableCellsS], [#icons.faTableCellsS],
    [faTableColumnsS], [#icons.faTableColumnsS],
    [faTableListS], [#icons.faTableListS],
    [faTableTennisPaddleBallS], [#icons.faTableTennisPaddleBallS],
    [faTableS], [#icons.faTableS],
    [faTabletButtonS], [#icons.faTabletButtonS],
    [faTabletScreenButtonS], [#icons.faTabletScreenButtonS],
    [faTabletS], [#icons.faTabletS],
    [faTabletsS], [#icons.faTabletsS],
    [faTachographDigitalS], [#icons.faTachographDigitalS],
    [faTagS], [#icons.faTagS],
    [faTagsS], [#icons.faTagsS],
    [faTapeS], [#icons.faTapeS],
    [faTarpDropletS], [#icons.faTarpDropletS],
    [faTarpS], [#icons.faTarpS],
    [faTaxiS], [#icons.faTaxiS],
    [faTeethOpenS], [#icons.faTeethOpenS],
    [faTeethS], [#icons.faTeethS],
    [faTemperatureArrowDownS], [#icons.faTemperatureArrowDownS],
    [faTemperatureArrowUpS], [#icons.faTemperatureArrowUpS],
    [faTemperatureEmptyS], [#icons.faTemperatureEmptyS],
    [faTemperatureFullS], [#icons.faTemperatureFullS],
    [faTemperatureHalfS], [#icons.faTemperatureHalfS],
    [faTemperatureHighS], [#icons.faTemperatureHighS],
    [faTemperatureLowS], [#icons.faTemperatureLowS],
    [faTemperatureQuarterS], [#icons.faTemperatureQuarterS],
    [faTemperatureThreeQuartersS], [#icons.faTemperatureThreeQuartersS],
    [faTengeSignS], [#icons.faTengeSignS],
    [faTentArrowDownToLineS], [#icons.faTentArrowDownToLineS],
    [faTentArrowLeftRightS], [#icons.faTentArrowLeftRightS],
    [faTentArrowTurnLeftS], [#icons.faTentArrowTurnLeftS],
    [faTentArrowsDownS], [#icons.faTentArrowsDownS],
    [faTentS], [#icons.faTentS],
    [faTentsS], [#icons.faTentsS],
    [faTerminalS], [#icons.faTerminalS],
    [faTextHeightS], [#icons.faTextHeightS],
    [faTextSlashS], [#icons.faTextSlashS],
    [faTextWidthS], [#icons.faTextWidthS],
    [faThermometerS], [#icons.faThermometerS],
    [faThumbsDownS], [#icons.faThumbsDownS],
    [faThumbsUpS], [#icons.faThumbsUpS],
    [faThumbtackS], [#icons.faThumbtackS],
    [faTicketSimpleS], [#icons.faTicketSimpleS],
    [faTicketS], [#icons.faTicketS],
    [faTimelineS], [#icons.faTimelineS],
)])

#pagebreak()

== To

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faToggleOffS], [#icons.faToggleOffS],
    [faToggleOnS], [#icons.faToggleOnS],
    [faToiletPaperSlashS], [#icons.faToiletPaperSlashS],
    [faToiletPaperS], [#icons.faToiletPaperS],
    [faToiletPortableS], [#icons.faToiletPortableS],
    [faToiletS], [#icons.faToiletS],
    [faToiletsPortableS], [#icons.faToiletsPortableS],
    [faToolboxS], [#icons.faToolboxS],
    [faToothS], [#icons.faToothS],
    [faToriiGateS], [#icons.faToriiGateS],
    [faTornadoS], [#icons.faTornadoS],
    [faTowerBroadcastS], [#icons.faTowerBroadcastS],
    [faTowerCellS], [#icons.faTowerCellS],
    [faTowerObservationS], [#icons.faTowerObservationS],
    [faTractorS], [#icons.faTractorS],
    [faTrademarkS], [#icons.faTrademarkS],
    [faTrafficLightS], [#icons.faTrafficLightS],
    [faTrailerS], [#icons.faTrailerS],
    [faTrainSubwayS], [#icons.faTrainSubwayS],
    [faTrainTramS], [#icons.faTrainTramS],
    [faTrainS], [#icons.faTrainS],
    [faTransgenderS], [#icons.faTransgenderS],
    [faTrashArrowUpS], [#icons.faTrashArrowUpS],
    [faTrashCanArrowUpS], [#icons.faTrashCanArrowUpS],
    [faTrashCanS], [#icons.faTrashCanS],
    [faTrashS], [#icons.faTrashS],
    [faTreeCityS], [#icons.faTreeCityS],
    [faTreeS], [#icons.faTreeS],
    [faTriangleExclamationS], [#icons.faTriangleExclamationS],
    [faTrophyS], [#icons.faTrophyS],
    [faTrowelBricksS], [#icons.faTrowelBricksS],
    [faTrowelS], [#icons.faTrowelS],
    [faTruckArrowRightS], [#icons.faTruckArrowRightS],
    [faTruckDropletS], [#icons.faTruckDropletS],
    [faTruckFastS], [#icons.faTruckFastS],
    [faTruckFieldUnS], [#icons.faTruckFieldUnS],
    [faTruckFieldS], [#icons.faTruckFieldS],
    [faTruckFrontS], [#icons.faTruckFrontS],
    [faTruckMedicalS], [#icons.faTruckMedicalS],
    [faTruckMonsterS], [#icons.faTruckMonsterS],
    [faTruckMovingS], [#icons.faTruckMovingS],
    [faTruckPickupS], [#icons.faTruckPickupS],
    [faTruckPlaneS], [#icons.faTruckPlaneS],
    [faTruckRampBoxS], [#icons.faTruckRampBoxS],
    [faTruckS], [#icons.faTruckS],
    [faTtyS], [#icons.faTtyS],
    [faTurkishLiraSignS], [#icons.faTurkishLiraSignS],
    [faTurnDownS], [#icons.faTurnDownS],
    [faTurnUpS], [#icons.faTurnUpS],
    [faTvS], [#icons.faTvS],
)])

#pagebreak()

== U-V

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faUS], [#icons.faUS],
    [faUmbrellaBeachS], [#icons.faUmbrellaBeachS],
    [faUmbrellaS], [#icons.faUmbrellaS],
    [faUnderlineS], [#icons.faUnderlineS],
    [faUniversalAccessS], [#icons.faUniversalAccessS],
    [faUnlockKeyholeS], [#icons.faUnlockKeyholeS],
    [faUnlockS], [#icons.faUnlockS],
    [faUpDownLeftRightS], [#icons.faUpDownLeftRightS],
    [faUpDownS], [#icons.faUpDownS],
    [faUpLongS], [#icons.faUpLongS],
    [faUpRightAndDownLeftFromCenterS], [#icons.faUpRightAndDownLeftFromCenterS],
    [faUpRightFromSquareS], [#icons.faUpRightFromSquareS],
    [faUploadS], [#icons.faUploadS],
    [faUserAstronautS], [#icons.faUserAstronautS],
    [faUserCheckS], [#icons.faUserCheckS],
    [faUserClockS], [#icons.faUserClockS],
    [faUserDoctorS], [#icons.faUserDoctorS],
    [faUserGearS], [#icons.faUserGearS],
    [faUserGraduateS], [#icons.faUserGraduateS],
    [faUserGroupS], [#icons.faUserGroupS],
    [faUserInjuredS], [#icons.faUserInjuredS],
    [faUserLargeSlashS], [#icons.faUserLargeSlashS],
    [faUserLargeS], [#icons.faUserLargeS],
    [faUserLockS], [#icons.faUserLockS],
    [faUserMinusS], [#icons.faUserMinusS],
    [faUserNinjaS], [#icons.faUserNinjaS],
    [faUserNurseS], [#icons.faUserNurseS],
    [faUserPenS], [#icons.faUserPenS],
    [faUserPlusS], [#icons.faUserPlusS],
    [faUserSecretS], [#icons.faUserSecretS],
    [faUserShieldS], [#icons.faUserShieldS],
    [faUserSlashS], [#icons.faUserSlashS],
    [faUserTagS], [#icons.faUserTagS],
    [faUserTieS], [#icons.faUserTieS],
    [faUserXmarkS], [#icons.faUserXmarkS],
    [faUserS], [#icons.faUserS],
    [faUsersBetweenLinesS], [#icons.faUsersBetweenLinesS],
    [faUsersGearS], [#icons.faUsersGearS],
    [faUsersLineS], [#icons.faUsersLineS],
    [faUsersRaysS], [#icons.faUsersRaysS],
    [faUsersRectangleS], [#icons.faUsersRectangleS],
    [faUsersSlashS], [#icons.faUsersSlashS],
    [faUsersViewfinderS], [#icons.faUsersViewfinderS],
    [faUsersS], [#icons.faUsersS],
    [faUtensilsS], [#icons.faUtensilsS],
    [faVS], [#icons.faVS],
    [faVanShuttleS], [#icons.faVanShuttleS],
    [faVaultS], [#icons.faVaultS],
    [faVectorSquareS], [#icons.faVectorSquareS],
    [faVenusDoubleS], [#icons.faVenusDoubleS],
    [faVenusMarsS], [#icons.faVenusMarsS],
    [faVenusS], [#icons.faVenusS],
    [faVestPatchesS], [#icons.faVestPatchesS],
    [faVestS], [#icons.faVestS],
    [faVialCircleCheckS], [#icons.faVialCircleCheckS],
    [faVialVirusS], [#icons.faVialVirusS],
    [faVialS], [#icons.faVialS],
    [faVialsS], [#icons.faVialsS],
    [faVideoSlashS], [#icons.faVideoSlashS],
    [faVideoS], [#icons.faVideoS],
    [faViharaS], [#icons.faViharaS],
    [faVirusCovidSlashS], [#icons.faVirusCovidSlashS],
    [faVirusCovidS], [#icons.faVirusCovidS],
    [faVirusSlashS], [#icons.faVirusSlashS],
    [faVirusS], [#icons.faVirusS],
    [faVirusesS], [#icons.faVirusesS],
    [faVoicemailS], [#icons.faVoicemailS],
    [faVolcanoS], [#icons.faVolcanoS],
    [faVolleyballS], [#icons.faVolleyballS],
    [faVolumeHighS], [#icons.faVolumeHighS],
    [faVolumeLowS], [#icons.faVolumeLowS],
    [faVolumeOffS], [#icons.faVolumeOffS],
    [faVolumeXmarkS], [#icons.faVolumeXmarkS],
    [faVrCardboardS], [#icons.faVrCardboardS],
)])

#pagebreak()

== W-Z

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faWS], [#icons.faWS],
    [faWalkieTalkieS], [#icons.faWalkieTalkieS],
    [faWalletS], [#icons.faWalletS],
    [faWandMagicSparklesS], [#icons.faWandMagicSparklesS],
    [faWandMagicS], [#icons.faWandMagicS],
    [faWandSparklesS], [#icons.faWandSparklesS],
    [faWarehouseS], [#icons.faWarehouseS],
    [faWaterLadderS], [#icons.faWaterLadderS],
    [faWaterS], [#icons.faWaterS],
    [faWaveSquareS], [#icons.faWaveSquareS],
    [faWeightHangingS], [#icons.faWeightHangingS],
    [faWeightScaleS], [#icons.faWeightScaleS],
    [faWheatAwnCircleExclamationS], [#icons.faWheatAwnCircleExclamationS],
    [faWheatAwnS], [#icons.faWheatAwnS],
    [faWheelchairMoveS], [#icons.faWheelchairMoveS],
    [faWheelchairS], [#icons.faWheelchairS],
    [faWhiskeyGlassS], [#icons.faWhiskeyGlassS],
    [faWifiS], [#icons.faWifiS],
    [faWindS], [#icons.faWindS],
    [faWindowMaximizeS], [#icons.faWindowMaximizeS],
    [faWindowMinimizeS], [#icons.faWindowMinimizeS],
    [faWindowRestoreS], [#icons.faWindowRestoreS],
    [faWineBottleS], [#icons.faWineBottleS],
    [faWineGlassEmptyS], [#icons.faWineGlassEmptyS],
    [faWineGlassS], [#icons.faWineGlassS],
    [faWonSignS], [#icons.faWonSignS],
    [faWormS], [#icons.faWormS],
    [faWrenchS], [#icons.faWrenchS],
    [faXRayS], [#icons.faXRayS],
    [faXS], [#icons.faXS],
    [faXmarkS], [#icons.faXmarkS],
    [faXmarksLinesS], [#icons.faXmarksLinesS],
    [faYS], [#icons.faYS],
    [faYenSignS], [#icons.faYenSignS],
    [faYinYangS], [#icons.faYinYangS],
    [faZS], [#icons.faZS],
)])

== 0-9

#figure(
align(center)[#table(
    columns: 10,
    align: center,
    [fa0S], [#icons.fa0S],
    [fa1S], [#icons.fa1S],
    [fa2S], [#icons.fa2S],
    [fa3S], [#icons.fa3S],
    [fa4S], [#icons.fa4S],
    [fa5S], [#icons.fa5S],
    [fa6S], [#icons.fa6S],
    [fa7S], [#icons.fa7S],
    [fa8S], [#icons.fa8S],
    [fa9S], [#icons.fa9S],
)])
