#import "fontawesome.typ": *

#let title = "Typst-FontAwesome"

#set page(
    paper: "a4",
      header: [
        #set text(6pt)
      ],
    numbering: "1"
)
#set heading(
  level: 2,
  numbering: "1.",
)
#set par(
  first-line-indent: 2em,
  justify: true,
  leading: 1em,
  linebreaks: "optimized"
)
#set block(above: 1em, below: 1em)

#align(center, text(18pt)[
      *#title*
])

#outline(
   title: [],
   indent: auto
)

#pagebreak()

= Brands

== A-H

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faAdn], [#box(faAdn)],
    [faAdversal], [#box(faAdversal)],
    [faAirbnb], [#box(faAirbnb)],
    [faAlgolia], [#box(faAlgolia)],
    [faAlipay], [#box(faAlipay)],
    [faAmazon], [#box(faAmazon)],
    [faAmazonPay], [#box(faAmazonPay)],
    [faAmazonPayCC], [#box(faAmazonPayCC)],
    [faAndroid], [#box(faAndroid)],
    [faAngular], [#box(faAngular)],
    [faApple], [#box(faApple)],
    [faApplePay], [#box(faApplePay)],
    [faApplePayCC], [#box(faApplePayCC)],
    [faAppStore], [#box(faAppStore)],
    [faAppStoreIOS], [#box(faAppStoreIOS)],
    [faAtlassian], [#box(faAtlassian)],
    [faAudible], [#box(faAudible)],
    [faAws], [#box(faAws)],
    [faBehance], [#box(faBehance)],
    [faBehanceSquare], [#box(faBehanceSquare)],
    [faBilibili], [#box(faBilibili)],
    [faBitbucket], [#box(faBitbucket)],
    [faBitcoin], [#box(faBitcoin)],
    [faBlackberry], [#box(faBlackberry)],
    [faBluetooth], [#box(faBluetooth)],
    [faBluetoothB], [#box(faBluetoothB)],
    [faBootstrap], [#box(faBootstrap)],
    [faBuffer], [#box(faBuffer)],
    [faCentos], [#box(faCentos)],
    [faChrome], [#box(faChrome)],
    [faChromecast], [#box(faChromecast)],
    [faCloudflare], [#box(faCloudflare)],
    [faCss3], [#box(faCss3)],
    [faCss3Alt], [#box(faCss3Alt)],
    [faDev], [#box(faDev)],
    [faDHL], [#box(faDHL)],
    [faDiscord], [#box(faDiscord)],
    [faDiscordBots], [#box(faDiscordBots)],
    [faDiscourse], [#box(faDiscourse)],
    [faDocker], [#box(faDocker)],
    [faDropbox], [#box(faDropbox)],
    [faDrupal], [#box(faDrupal)],
    [faEarlybirds], [#box(faEarlybirds)],
    [faEbay], [#box(faEbay)],
    [faEdge], [#box(faEdge)],
    [faEdgeLegacy], [#box(faEdgeLegacy)],
    [faErlang], [#box(faErlang)],
    [faEthereum], [#box(faEthereum)],
    [faEvernote], [#box(faEvernote)],
    [faFacebook], [#box(faFacebook)],
    [faFacebookF], [#box(faFacebookF)],
    [faFacebookMessenger], [#box(faFacebookMessenger)],
    [faFacebookSquare], [#box(faFacebookSquare)],
    [faFedex], [#box(faFedex)],
    [faFedora], [#box(faFedora)],
    [faFigma], [#box(faFigma)],
    [faFirefox], [#box(faFirefox)],
    [faFirefoxBrowser], [#box(faFirefoxBrowser)],
    [faFlickr], [#box(faFlickr)],
    [faFontAwesome], [#box(faFontAwesome)],
    [faFontAwesomeSquare], [#box(faFontAwesomeSquare)],
    [faFontAwesomeSquareStroke], [#box(faFontAwesomeSquareStroke)],
    [faFreebsd], [#box(faFreebsd)],
    [faGetPocket], [#box(faGetPocket)],
    [faGit], [#box(faGit)],
    [faGitAlt], [#box(faGitAlt)],
    [faGithub], [#box(faGithub)],
    [faGithubAlt], [#box(faGithubAlt)],
    [faGithubSquare], [#box(faGithubSquare)],
    [faGitkraken], [#box(faGitkraken)],
    [faGitlab], [#box(faGitlab)],
    [faGitlabSquare], [#box(faGitlabSquare)],
    [faGitSquare], [#box(faGitSquare)],
    [faGitter], [#box(faGitter)],
    [faGolang], [#box(faGolang)],
    [faGoogle], [#box(faGoogle)],
    [faGoogleDrive], [#box(faGoogleDrive)],
    [faGooglePay], [#box(faGooglePay)],
    [faGooglePlay], [#box(faGooglePlay)],
    [faGooglePlus], [#box(faGooglePlus)],
    [faGooglePlusG], [#box(faGooglePlusG)],
    [faGooglePlusSquare], [#box(faGooglePlusSquare)],
    [faGoogleWallet], [#box(faGoogleWallet)],
    [faGrunt], [#box(faGrunt)],
    [faGulp], [#box(faGulp)],
    [faHive], [#box(faHive)],
    [faHtml5], [#box(faHtml5)],
)])

#pagebreak()

== I-Z

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faInstagram], [#box(faInstagram)],
    [faInstagramSquare], [#box(faInstagramSquare)],
    [faInternetExplorer], [#box(faInternetExplorer)],
    [faItunes], [#box(faItunes)],
    [faItunesNote], [#box(faItunesNote)],
    [faJava], [#box(faJava)],
    [faJenkins], [#box(faJenkins)],
    [faJira], [#box(faJira)],
    [faJoomla], [#box(faJoomla)],
    [faJS], [#box(faJS)],
    [faJSSquare], [#box(faJSSquare)],
    [faKaggle], [#box(faKaggle)],
    [faLaravel], [#box(faLaravel)],
    [faLastfm], [#box(faLastfm)],
    [faLastfmSquare], [#box(faLastfmSquare)],
    [faLeanpub], [#box(faLeanpub)],
    [faLess], [#box(faLess)],
    [faLine], [#box(faLine)],
    [faLinkedin], [#box(faLinkedin)],
    [faLinkedinIn], [#box(faLinkedinIn)],
    [faLinux], [#box(faLinux)],
    [faMarkdown], [#box(faMarkdown)],
    [faMastercardCC], [#box(faMastercardCC)],
    [faMastodon], [#box(faMastodon)],
    [faMdb], [#box(faMdb)],
    [faMedium], [#box(faMedium)],
    [faMendeley], [#box(faMendeley)],
    [faMeta], [#box(faMeta)],
    [faMicrosoft], [#box(faMicrosoft)],
    [faNode], [#box(faNode)],
    [faNodeJS], [#box(faNodeJS)],
    [faNpm], [#box(faNpm)],
    [faOpera], [#box(faOpera)],
    [faOsi], [#box(faOsi)],
    [faPatreon], [#box(faPatreon)],
    [faPaypal], [#box(faPaypal)],
    [faPaypalCC], [#box(faPaypalCC)],
    [faPhp], [#box(faPhp)],
    [faPinterest], [#box(faPinterest)],
    [faPinterestP], [#box(faPinterestP)],
    [faPinterestSquare], [#box(faPinterestSquare)],
    [faProductHunt], [#box(faProductHunt)],
    [faPython], [#box(faPython)],
    [faQq], [#box(faQq)],
    [faQuora], [#box(faQuora)],
    [faRaspberryPi], [#box(faRaspberryPi)],
    [faReact], [#box(faReact)],
    [faReadme], [#box(faReadme)],
    [faReddit], [#box(faReddit)],
    [faRedditAlien], [#box(faRedditAlien)],
    [faRedditSquare], [#box(faRedditSquare)],
    [faRedhat], [#box(faRedhat)],
    [faRenren], [#box(faRenren)],
    [faResearchgate], [#box(faResearchgate)],
    [faRProject], [#box(faRProject)],
    [faRust], [#box(faRust)],
    [faSafari], [#box(faSafari)],
    [faSalesforce], [#box(faSalesforce)],
    [faSass], [#box(faSass)],
    [faScribd], [#box(faScribd)],
    [faShopify], [#box(faShopify)],
    [faSketch], [#box(faSketch)],
    [faSkype], [#box(faSkype)],
    [faSlack], [#box(faSlack)],
    [faSnapchat], [#box(faSnapchat)],
    [faSnapchatSquare], [#box(faSnapchatSquare)],
    [faSpotify], [#box(faSpotify)],
    [faSteamSquare], [#box(faSteamSquare)],
    [faStripeCC], [#box(faStripeCC)],
    [faSuse], [#box(faSuse)],
    [faSwift], [#box(faSwift)],
    [faSymfony], [#box(faSymfony)],
    [faTelegram], [#box(faTelegram)],
    [faTencentWeibo], [#box(faTencentWeibo)],
    [faTiktok], [#box(faTiktok)],
    [faTrello], [#box(faTrello)],
    [faTumblr], [#box(faTumblr)],
    [faTumblrSquare], [#box(faTumblrSquare)],
    [faTwitch], [#box(faTwitch)],
    [faTwitter], [#box(faTwitter)],
    [faTwitterSquare], [#box(faTwitterSquare)],
    [faUber], [#box(faUber)],
    [faUbuntu], [#box(faUbuntu)],
    [faUnity], [#box(faUnity)],
    [faUsb], [#box(faUsb)],
    [faViadeoSquare], [#box(faViadeoSquare)],
    [faViber], [#box(faViber)],
    [faVimeo], [#box(faVimeo)],
    [faVimeoSquare], [#box(faVimeoSquare)],
    [faVimeoV], [#box(faVimeoV)],
    [faVisa], [#box(faVisa)],
    [faVk], [#box(faVk)],
    [faVuejs], [#box(faVuejs)],
    [faWeibo], [#box(faWeibo)],
    [faWeixin], [#box(faWeixin)],
    [faWhatsapp], [#box(faWhatsapp)],
    [faWhatsappSquare], [#box(faWhatsappSquare)],
    [faWikipedia], [#box(faWikipedia)],
    [faWindows], [#box(faWindows)],
    [faWordpress], [#box(faWordpress)],
    [faWordpressSimple], [#box(faWordpressSimple)],
    [faXbox], [#box(faXbox)],
    [faYahoo], [#box(faYahoo)],
    [faYandex], [#box(faYandex)],
    [faYarn], [#box(faYarn)],
    [faYCombinator], [#box(faYCombinator)],
    [faYoutube], [#box(faYoutube)],
    [faYoutubeSquare], [#box(faYoutubeSquare)],
    [faZhihu], [#box(faZhihu)]
)])

#pagebreak()

= Regular

== A-E

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faAddressBook], [#box(faAddressBook)],
    [faAddressCard], [#box(faAddressCard)],
    [faBellSlash], [#box(faBellSlash)],
    [faBell], [#box(faBell)],
    [faBookmark], [#box(faBookmark)],
    [faBuilding], [#box(faBuilding)],
    [faCalendarCheck], [#box(faCalendarCheck)],
    [faCalendarDays], [#box(faCalendarDays)],
    [faCalendarMinus], [#box(faCalendarMinus)],
    [faCalendarPlus], [#box(faCalendarPlus)],
    [faCalendarXmark], [#box(faCalendarXmark)],
    [faCalendar], [#box(faCalendar)],
    [faChartBar], [#box(faChartBar)],
    [faChessBishop], [#box(faChessBishop)],
    [faChessKing], [#box(faChessKing)],
    [faChessKnight], [#box(faChessKnight)],
    [faChessPawn], [#box(faChessPawn)],
    [faChessQueen], [#box(faChessQueen)],
    [faChessRook], [#box(faChessRook)],
    [faCircleCheck], [#box(faCircleCheck)],
    [faCircleDot], [#box(faCircleDot)],
    [faCircleDown], [#box(faCircleDown)],
    [faCircleLeft], [#box(faCircleLeft)],
    [faCirclePause], [#box(faCirclePause)],
    [faCirclePlay], [#box(faCirclePlay)],
    [faCircleQuestion], [#box(faCircleQuestion)],
    [faCircleRight], [#box(faCircleRight)],
    [faCircleStop], [#box(faCircleStop)],
    [faCircleUp], [#box(faCircleUp)],
    [faCircleUser], [#box(faCircleUser)],
    [faCircleXmark], [#box(faCircleXmark)],
    [faCircle], [#box(faCircle)],
    [faClipboard], [#box(faClipboard)],
    [faClock], [#box(faClock)],
    [faClone], [#box(faClone)],
    [faClosedCaptioning], [#box(faClosedCaptioning)],
    [faCommentDots], [#box(faCommentDots)],
    [faComment], [#box(faComment)],
    [faComments], [#box(faComments)],
    [faCompass], [#box(faCompass)],
    [faCopy], [#box(faCopy)],
    [faCopyright], [#box(faCopyright)],
    [faCreditCard], [#box(faCreditCard)],
    [faEnvelopeOpen], [#box(faEnvelopeOpen)],
    [faEnvelope], [#box(faEnvelope)],
    [faEyeSlash], [#box(faEyeSlash)],
    [faEye], [#box(faEye)],
)])

#pagebreak()

== F

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFaceAngry], [#box(faFaceAngry)],
    [faFaceDizzy], [#box(faFaceDizzy)],
    [faFaceFlushed], [#box(faFaceFlushed)],
    [faFaceFrownOpen], [#box(faFaceFrownOpen)],
    [faFaceFrown], [#box(faFaceFrown)],
    [faFaceGrimace], [#box(faFaceGrimace)],
    [faFaceGrinBeamSweat], [#box(faFaceGrinBeamSweat)],
    [faFaceGrinBeam], [#box(faFaceGrinBeam)],
    [faFaceGrinHearts], [#box(faFaceGrinHearts)],
    [faFaceGrinSquintTears], [#box(faFaceGrinSquintTears)],
    [faFaceGrinSquint], [#box(faFaceGrinSquint)],
    [faFaceGrinStars], [#box(faFaceGrinStars)],
    [faFaceGrinTears], [#box(faFaceGrinTears)],
    [faFaceGrinTongueSquint], [#box(faFaceGrinTongueSquint)],
    [faFaceGrinTongueWink], [#box(faFaceGrinTongueWink)],
    [faFaceGrinTongue], [#box(faFaceGrinTongue)],
    [faFaceGrinWide], [#box(faFaceGrinWide)],
    [faFaceGrinWink], [#box(faFaceGrinWink)],
    [faFaceGrin], [#box(faFaceGrin)],
    [faFaceKissBeam], [#box(faFaceKissBeam)],
    [faFaceKissWinkHeart], [#box(faFaceKissWinkHeart)],
    [faFaceKiss], [#box(faFaceKiss)],
    [faFaceLaughBeam], [#box(faFaceLaughBeam)],
    [faFaceLaughSquint], [#box(faFaceLaughSquint)],
    [faFaceLaughWink], [#box(faFaceLaughWink)],
    [faFaceLaugh], [#box(faFaceLaugh)],
    [faFaceMehBlank], [#box(faFaceMehBlank)],
    [faFaceMeh], [#box(faFaceMeh)],
    [faFaceRollingEyes], [#box(faFaceRollingEyes)],
    [faFaceSadCry], [#box(faFaceSadCry)],
    [faFaceSadTear], [#box(faFaceSadTear)],
    [faFaceSmileBeam], [#box(faFaceSmileBeam)],
    [faFaceSmileWink], [#box(faFaceSmileWink)],
    [faFaceSmile], [#box(faFaceSmile)],
    [faFaceSurprise], [#box(faFaceSurprise)],
    [faFaceTired], [#box(faFaceTired)],
    [faFileAudio], [#box(faFileAudio)],
    [faFileCode], [#box(faFileCode)],
    [faFileExcel], [#box(faFileExcel)],
    [faFileImage], [#box(faFileImage)],
    [faFileLines], [#box(faFileLines)],
    [faFilePdf], [#box(faFilePdf)],
    [faFilePowerpoint], [#box(faFilePowerpoint)],
    [faFileVideo], [#box(faFileVideo)],
    [faFileWord], [#box(faFileWord)],
    [faFileZipper], [#box(faFileZipper)],
    [faFile], [#box(faFile)],
    [faFlag], [#box(faFlag)],
    [faFloppyDisk], [#box(faFloppyDisk)],
    [faFolderClosed], [#box(faFolderClosed)],
    [faFolderOpen], [#box(faFolderOpen)],
    [faFolder], [#box(faFolder)],
    [faFontAwesome], [#box(faFontAwesome)],
    [faFutbol], [#box(faFutbol)],
)])

#pagebreak()

== G-W

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faGem], [#box(faGem)],
    [faHandBackFist], [#box(faHandBackFist)],
    [faHandLizard], [#box(faHandLizard)],
    [faHandPeace], [#box(faHandPeace)],
    [faHandPointDown], [#box(faHandPointDown)],
    [faHandPointLeft], [#box(faHandPointLeft)],
    [faHandPointRight], [#box(faHandPointRight)],
    [faHandPointUp], [#box(faHandPointUp)],
    [faHandPointer], [#box(faHandPointer)],
    [faHandScissors], [#box(faHandScissors)],
    [faHandSpock], [#box(faHandSpock)],
    [faHand], [#box(faHand)],
    [faHandshake], [#box(faHandshake)],
    [faHardDrive], [#box(faHardDrive)],
    [faHeart], [#box(faHeart)],
    [faHospital], [#box(faHospital)],
    [faHourglassHalf], [#box(faHourglassHalf)],
    [faHourglass], [#box(faHourglass)],
    [faIdBadge], [#box(faIdBadge)],
    [faIdCard], [#box(faIdCard)],
    [faImage], [#box(faImage)],
    [faImages], [#box(faImages)],
    [faKeyboard], [#box(faKeyboard)],
    [faLemon], [#box(faLemon)],
    [faLifeRing], [#box(faLifeRing)],
    [faLightbulb], [#box(faLightbulb)],
    [faMap], [#box(faMap)],
    [faMessage], [#box(faMessage)],
    [faMoneyBill1], [#box(faMoneyBill1)],
    [faMoon], [#box(faMoon)],
    [faNewspaper], [#box(faNewspaper)],
    [faNoteSticky], [#box(faNoteSticky)],
    [faObjectGroup], [#box(faObjectGroup)],
    [faObjectUngroup], [#box(faObjectUngroup)],
    [faPaperPlane], [#box(faPaperPlane)],
    [faPaste], [#box(faPaste)],
    [faPenToSquare], [#box(faPenToSquare)],
    [faRectangleList], [#box(faRectangleList)],
    [faRectangleXmark], [#box(faRectangleXmark)],
    [faRegistered], [#box(faRegistered)],
    [faShareFromSquare], [#box(faShareFromSquare)],
    [faSnowflake], [#box(faSnowflake)],
    [faSquareCaretDown], [#box(faSquareCaretDown)],
    [faSquareCaretLeft], [#box(faSquareCaretLeft)],
    [faSquareCaretRight], [#box(faSquareCaretRight)],
    [faSquareCaretUp], [#box(faSquareCaretUp)],
    [faSquareCheck], [#box(faSquareCheck)],
    [faSquareFull], [#box(faSquareFull)],
    [faSquareMinus], [#box(faSquareMinus)],
    [faSquarePlus], [#box(faSquarePlus)],
    [faSquare], [#box(faSquare)],
    [faStarHalfStroke], [#box(faStarHalfStroke)],
    [faStarHalf], [#box(faStarHalf)],
    [faStar], [#box(faStar)],
    [faSun], [#box(faSun)],
    [faThumbsDown], [#box(faThumbsDown)],
    [faThumbsUp], [#box(faThumbsUp)],
    [faTrashCan], [#box(faTrashCan)],
    [faUser], [#box(faUser)],
    [faWindowMaximize], [#box(faWindowMaximize)],
    [faWindowMinimize], [#box(faWindowMinimize)],
    [faWindowRestore], [#box(faWindowRestore)],
)])

#pagebreak()

= Solid

== A

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faA], [#box(faA)],
    [faAddressBook], [#box(faAddressBook)],
    [faAddressCard], [#box(faAddressCard)],
    [faAlignCenter], [#box(faAlignCenter)],
    [faAlignJustify], [#box(faAlignJustify)],
    [faAlignLeft], [#box(faAlignLeft)],
    [faAlignRight], [#box(faAlignRight)],
    [faAnchorCircleCheck], [#box(faAnchorCircleCheck)],
    [faAnchorCircleExclamation], [#box(faAnchorCircleExclamation)],
    [faAnchorCircleXmark], [#box(faAnchorCircleXmark)],
    [faAnchorLock], [#box(faAnchorLock)],
    [faAnchor], [#box(faAnchor)],
    [faAngleDown], [#box(faAngleDown)],
    [faAngleLeft], [#box(faAngleLeft)],
    [faAngleRight], [#box(faAngleRight)],
    [faAngleUp], [#box(faAngleUp)],
    [faAnglesDown], [#box(faAnglesDown)],
    [faAnglesLeft], [#box(faAnglesLeft)],
    [faAnglesRight], [#box(faAnglesRight)],
    [faAnglesUp], [#box(faAnglesUp)],
    [faAnkh], [#box(faAnkh)],
    [faAppleWhole], [#box(faAppleWhole)],
    [faArchway], [#box(faArchway)],
    [faArrowDown19], [#box(faArrowDown19)],
    [faArrowDown91], [#box(faArrowDown91)],
    [faArrowDownAZ], [#box(faArrowDownAZ)],
    [faArrowDownLong], [#box(faArrowDownLong)],
    [faArrowDownShortWide], [#box(faArrowDownShortWide)],
    [faArrowDownUpAcrossLine], [#box(faArrowDownUpAcrossLine)],
    [faArrowDownUpLock], [#box(faArrowDownUpLock)],
    [faArrowDownWideShort], [#box(faArrowDownWideShort)],
    [faArrowDownZA], [#box(faArrowDownZA)],
    [faArrowDown], [#box(faArrowDown)],
    [faArrowLeftLong], [#box(faArrowLeftLong)],
    [faArrowLeft], [#box(faArrowLeft)],
    [faArrowPointer], [#box(faArrowPointer)],
    [faArrowRightArrowLeft], [#box(faArrowRightArrowLeft)],
    [faArrowRightFromBracket], [#box(faArrowRightFromBracket)],
    [faArrowRightLong], [#box(faArrowRightLong)],
    [faArrowRightToBracket], [#box(faArrowRightToBracket)],
    [faArrowRightToCity], [#box(faArrowRightToCity)],
    [faArrowRight], [#box(faArrowRight)],
    [faArrowRotateLeft], [#box(faArrowRotateLeft)],
    [faArrowRotateRight], [#box(faArrowRotateRight)],
    [faArrowTrendDown], [#box(faArrowTrendDown)],
    [faArrowTrendUp], [#box(faArrowTrendUp)],
    [faArrowTurnDown], [#box(faArrowTurnDown)],
    [faArrowTurnUp], [#box(faArrowTurnUp)],
    [faArrowUp19], [#box(faArrowUp19)],
    [faArrowUp91], [#box(faArrowUp91)],
    [faArrowUpAZ], [#box(faArrowUpAZ)],
    [faArrowUpFromBracket], [#box(faArrowUpFromBracket)],
    [faArrowUpFromGroundWater], [#box(faArrowUpFromGroundWater)],
    [faArrowUpFromWaterPump], [#box(faArrowUpFromWaterPump)],
    [faArrowUpLong], [#box(faArrowUpLong)],
    [faArrowUpRightDots], [#box(faArrowUpRightDots)],
    [faArrowUpRightFromSquare], [#box(faArrowUpRightFromSquare)],
    [faArrowUpShortWide], [#box(faArrowUpShortWide)],
    [faArrowUpWideShort], [#box(faArrowUpWideShort)],
    [faArrowUpZA], [#box(faArrowUpZA)],
    [faArrowUp], [#box(faArrowUp)],
    [faArrowsDownToLine], [#box(faArrowsDownToLine)],
    [faArrowsDownToPeople], [#box(faArrowsDownToPeople)],
    [faArrowsLeftRightToLine], [#box(faArrowsLeftRightToLine)],
    [faArrowsLeftRight], [#box(faArrowsLeftRight)],
    [faArrowsRotate], [#box(faArrowsRotate)],
    [faArrowsSpin], [#box(faArrowsSpin)],
    [faArrowsSplitUpAndLeft], [#box(faArrowsSplitUpAndLeft)],
    [faArrowsToCircle], [#box(faArrowsToCircle)],
    [faArrowsToDot], [#box(faArrowsToDot)],
    [faArrowsToEye], [#box(faArrowsToEye)],
    [faArrowsTurnRight], [#box(faArrowsTurnRight)],
    [faArrowsTurnToDots], [#box(faArrowsTurnToDots)],
    [faArrowsUpDownLeftRight], [#box(faArrowsUpDownLeftRight)],
    [faArrowsUpDown], [#box(faArrowsUpDown)],
    [faArrowsUpToLine], [#box(faArrowsUpToLine)],
    [faAsterisk], [#box(faAsterisk)],
    [faAt], [#box(faAt)],
    [faAtom], [#box(faAtom)],
    [faAudioDescription], [#box(faAudioDescription)],
    [faAustralSign], [#box(faAustralSign)],
    [faAward], [#box(faAward)],
)])

#pagebreak()

== B-Br

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faB], [#box(faB)],
    [faBabyCarriage], [#box(faBabyCarriage)],
    [faBaby], [#box(faBaby)],
    [faBackwardFast], [#box(faBackwardFast)],
    [faBackwardStep], [#box(faBackwardStep)],
    [faBackward], [#box(faBackward)],
    [faBacon], [#box(faBacon)],
    [faBacteria], [#box(faBacteria)],
    [faBacterium], [#box(faBacterium)],
    [faBagShopping], [#box(faBagShopping)],
    [faBahai], [#box(faBahai)],
    [faBahtSign], [#box(faBahtSign)],
    [faBanSmoking], [#box(faBanSmoking)],
    [faBan], [#box(faBan)],
    [faBandage], [#box(faBandage)],
    [faSbangladeshiTakaSign], [#box(faSbangladeshiTakaSign)],
    [faBarcode], [#box(faBarcode)],
    [faBarsProgress], [#box(faBarsProgress)],
    [faBarsStaggered], [#box(faBarsStaggered)],
    [faBars], [#box(faBars)],
    [faBaseballBatBall], [#box(faBaseballBatBall)],
    [faBaseball], [#box(faBaseball)],
    [faBasketShopping], [#box(faBasketShopping)],
    [faBasketball], [#box(faBasketball)],
    [faBath], [#box(faBath)],
    [faBatteryEmpty], [#box(faBatteryEmpty)],
    [faBatteryFull], [#box(faBatteryFull)],
    [faBatteryHalf], [#box(faBatteryHalf)],
    [faBatteryQuarter], [#box(faBatteryQuarter)],
    [faBatteryThreeQuarters], [#box(faBatteryThreeQuarters)],
    [faBedPulse], [#box(faBedPulse)],
    [faBed], [#box(faBed)],
    [faBeerMugEmpty], [#box(faBeerMugEmpty)],
    [faBellConcierge], [#box(faBellConcierge)],
    [faBellSlash], [#box(faBellSlash)],
    [faBell], [#box(faBell)],
    [faBezierCurve], [#box(faBezierCurve)],
    [faBicycle], [#box(faBicycle)],
    [faBinoculars], [#box(faBinoculars)],
    [faBiohazard], [#box(faBiohazard)],
    [faBitcoinSign], [#box(faBitcoinSign)],
    [faBlenderPhone], [#box(faBlenderPhone)],
    [faBlender], [#box(faBlender)],
    [faBlog], [#box(faBlog)],
    [faBold], [#box(faBold)],
    [faBoltLightning], [#box(faBoltLightning)],
    [faBolt], [#box(faBolt)],
    [faBomb], [#box(faBomb)],
    [faBone], [#box(faBone)],
    [faBong], [#box(faBong)],
    [faBookAtlas], [#box(faBookAtlas)],
    [faBookBible], [#box(faBookBible)],
    [faBookBookmark], [#box(faBookBookmark)],
    [faBookJournalWhills], [#box(faBookJournalWhills)],
    [faBookMedical], [#box(faBookMedical)],
    [faBookOpenReader], [#box(faBookOpenReader)],
    [faBookOpen], [#box(faBookOpen)],
    [faBookQuran], [#box(faBookQuran)],
    [faBookSkull], [#box(faBookSkull)],
    [faBookTanakh], [#box(faBookTanakh)],
    [faBook], [#box(faBook)],
    [faBookmark], [#box(faBookmark)],
    [faBorderAll], [#box(faBorderAll)],
    [faBorderNone], [#box(faBorderNone)],
    [faBorderTopLeft], [#box(faBorderTopLeft)],
    [faBoreHole], [#box(faBoreHole)],
    [faBottleDroplet], [#box(faBottleDroplet)],
    [faBottleWater], [#box(faBottleWater)],
    [faBowlFood], [#box(faBowlFood)],
    [faBowlRice], [#box(faBowlRice)],
    [faBowlingBall], [#box(faBowlingBall)],
    [faBoxArchive], [#box(faBoxArchive)],
    [faBoxOpen], [#box(faBoxOpen)],
    [faBoxTissue], [#box(faBoxTissue)],
    [faBox], [#box(faBox)],
    [faBoxesPacking], [#box(faBoxesPacking)],
    [faBoxesStacked], [#box(faBoxesStacked)],
    [faBraille], [#box(faBraille)],
    [faBrain], [#box(faBrain)],
    [faBrazilianRealSign], [#box(faBrazilianRealSign)],
    [faBreadSlice], [#box(faBreadSlice)],
    [faBridgeCircleCheck], [#box(faBridgeCircleCheck)],
    [faBridgeCircleExclamation], [#box(faBridgeCircleExclamation)],
    [faBridgeCircleXmark], [#box(faBridgeCircleXmark)],
    [faBridgeLock], [#box(faBridgeLock)],
    [faBridgeWater], [#box(faBridgeWater)],
    [faBridge], [#box(faBridge)],
    [faBriefcaseMedical], [#box(faBriefcaseMedical)],
    [faBriefcase], [#box(faBriefcase)],
    [faBroomBall], [#box(faBroomBall)],
    [faBroom], [#box(faBroom)],
    [faBrush], [#box(faBrush)],
)])

#pagebreak()

== Bu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faBucket], [#box(faBucket)],
    [faBugSlash], [#box(faBugSlash)],
    [faBug], [#box(faBug)],
    [faBugs], [#box(faBugs)],
    [faBuildingCircleArrowRight], [#box(faBuildingCircleArrowRight)],
    [faBuildingCircleCheck], [#box(faBuildingCircleCheck)],
    [faBuildingCircleExclamation], [#box(faBuildingCircleExclamation)],
    [faBuildingCircleXmark], [#box(faBuildingCircleXmark)],
    [faBuildingColumns], [#box(faBuildingColumns)],
    [faBuildingFlag], [#box(faBuildingFlag)],
    [faBuildingLock], [#box(faBuildingLock)],
    [faBuildingNgo], [#box(faBuildingNgo)],
    [faBuildingShield], [#box(faBuildingShield)],
    [faBuildingUn], [#box(faBuildingUn)],
    [faBuildingUser], [#box(faBuildingUser)],
    [faBuildingWheat], [#box(faBuildingWheat)],
    [faBuilding], [#box(faBuilding)],
    [faBullhorn], [#box(faBullhorn)],
    [faBullseye], [#box(faBullseye)],
    [faBurger], [#box(faBurger)],
    [faBurst], [#box(faBurst)],
    [faBusSimple], [#box(faBusSimple)],
    [faBus], [#box(faBus)],
    [faBusinessTime], [#box(faBusinessTime)],
)])

== C-Ce

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faC], [#box(faC)],
    [faCableCar], [#box(faCableCar)],
    [faCakeCandles], [#box(faCakeCandles)],
    [faCalculator], [#box(faCalculator)],
    [faCalendarCheck], [#box(faCalendarCheck)],
    [faCalendarDay], [#box(faCalendarDay)],
    [faCalendarDays], [#box(faCalendarDays)],
    [faCalendarMinus], [#box(faCalendarMinus)],
    [faCalendarPlus], [#box(faCalendarPlus)],
    [faCalendarWeek], [#box(faCalendarWeek)],
    [faCalendarXmark], [#box(faCalendarXmark)],
    [faCalendar], [#box(faCalendar)],
    [faCameraRetro], [#box(faCameraRetro)],
    [faCameraRotate], [#box(faCameraRotate)],
    [faCamera], [#box(faCamera)],
    [faCampground], [#box(faCampground)],
    [faCandyCane], [#box(faCandyCane)],
    [faCannabis], [#box(faCannabis)],
    [faCapsules], [#box(faCapsules)],
    [faCarBattery], [#box(faCarBattery)],
    [faCarBurst], [#box(faCarBurst)],
    [faCarOn], [#box(faCarOn)],
    [faCarRear], [#box(faCarRear)],
    [faCarSide], [#box(faCarSide)],
    [faCarTunnel], [#box(faCarTunnel)],
    [faCar], [#box(faCar)],
    [faCaravan], [#box(faCaravan)],
    [faCaretDown], [#box(faCaretDown)],
    [faCaretLeft], [#box(faCaretLeft)],
    [faCaretRight], [#box(faCaretRight)],
    [faCaretUp], [#box(faCaretUp)],
    [faCarrot], [#box(faCarrot)],
    [faCartArrowDown], [#box(faCartArrowDown)],
    [faCartFlatbedSuitcase], [#box(faCartFlatbedSuitcase)],
    [faCartFlatbed], [#box(faCartFlatbed)],
    [faCartPlus], [#box(faCartPlus)],
    [faCartShopping], [#box(faCartShopping)],
    [faCashRegister], [#box(faCashRegister)],
    [faCat], [#box(faCat)],
    [faCediSign], [#box(faCediSign)],
    [faCentSign], [#box(faCentSign)],
    [faCertificate], [#box(faCertificate)],
)])

#pagebreak()

== Ch-Cl

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faChair], [#box(faChair)],
    [faChalkboardUser], [#box(faChalkboardUser)],
    [faChalkboard], [#box(faChalkboard)],
    [faChampagneGlasses], [#box(faChampagneGlasses)],
    [faChargingStation], [#box(faChargingStation)],
    [faChartArea], [#box(faChartArea)],
    [faChartBar], [#box(faChartBar)],
    [faChartColumn], [#box(faChartColumn)],
    [faChartGantt], [#box(faChartGantt)],
    [faChartLine], [#box(faChartLine)],
    [faChartPie], [#box(faChartPie)],
    [faChartSimple], [#box(faChartSimple)],
    [faCheckDouble], [#box(faCheckDouble)],
    [faCheckToSlot], [#box(faCheckToSlot)],
    [faCheck], [#box(faCheck)],
    [faCheese], [#box(faCheese)],
    [faChessBishop], [#box(faChessBishop)],
    [faChessBoard], [#box(faChessBoard)],
    [faChessKing], [#box(faChessKing)],
    [faChessKnight], [#box(faChessKnight)],
    [faChessPawn], [#box(faChessPawn)],
    [faChessQueen], [#box(faChessQueen)],
    [faChessRook], [#box(faChessRook)],
    [faChess], [#box(faChess)],
    [faChevronDown], [#box(faChevronDown)],
    [faChevronLeft], [#box(faChevronLeft)],
    [faChevronRight], [#box(faChevronRight)],
    [faChevronUp], [#box(faChevronUp)],
    [faChildCombatant], [#box(faChildCombatant)],
    [faChildDress], [#box(faChildDress)],
    [faChildReaching], [#box(faChildReaching)],
    [faChild], [#box(faChild)],
    [faChildren], [#box(faChildren)],
    [faChurch], [#box(faChurch)],
    [faCircleArrowDown], [#box(faCircleArrowDown)],
    [faCircleArrowLeft], [#box(faCircleArrowLeft)],
    [faCircleArrowRight], [#box(faCircleArrowRight)],
    [faCircleArrowUp], [#box(faCircleArrowUp)],
    [faCircleCheck], [#box(faCircleCheck)],
    [faCircleChevronDown], [#box(faCircleChevronDown)],
    [faCircleChevronLeft], [#box(faCircleChevronLeft)],
    [faCircleChevronRight], [#box(faCircleChevronRight)],
    [faCircleChevronUp], [#box(faCircleChevronUp)],
    [faCircleDollarToSlot], [#box(faCircleDollarToSlot)],
    [faCircleDot], [#box(faCircleDot)],
    [faCircleDown], [#box(faCircleDown)],
    [faCircleExclamation], [#box(faCircleExclamation)],
    [faCircleH], [#box(faCircleH)],
    [faCircleHalfStroke], [#box(faCircleHalfStroke)],
    [faCircleInfo], [#box(faCircleInfo)],
    [faCircleLeft], [#box(faCircleLeft)],
    [faCircleMinus], [#box(faCircleMinus)],
    [faCircleNodes], [#box(faCircleNodes)],
    [faCircleNotch], [#box(faCircleNotch)],
    [faCirclePause], [#box(faCirclePause)],
    [faCirclePlay], [#box(faCirclePlay)],
    [faCirclePlus], [#box(faCirclePlus)],
    [faCircleQuestion], [#box(faCircleQuestion)],
    [faCircleRadiation], [#box(faCircleRadiation)],
    [faCircleRight], [#box(faCircleRight)],
    [faCircleStop], [#box(faCircleStop)],
    [faCircleUp], [#box(faCircleUp)],
    [faCircleUser], [#box(faCircleUser)],
    [faCircleXmark], [#box(faCircleXmark)],
    [faCircle], [#box(faCircle)],
    [faCity], [#box(faCity)],
    [faClapperboard], [#box(faClapperboard)],
    [faClipboardCheck], [#box(faClipboardCheck)],
    [faClipboardList], [#box(faClipboardList)],
    [faClipboardQuestion], [#box(faClipboardQuestion)],
    [faClipboardUser], [#box(faClipboardUser)],
    [faClipboard], [#box(faClipboard)],
    [faClockRotateLeft], [#box(faClockRotateLeft)],
    [faClock], [#box(faClock)],
    [faClone], [#box(faClone)],
    [faClosedCaptioning], [#box(faClosedCaptioning)],
    [faCloudArrowDown], [#box(faCloudArrowDown)],
    [faCloudArrowUp], [#box(faCloudArrowUp)],
    [faCloudBolt], [#box(faCloudBolt)],
    [faCloudMeatball], [#box(faCloudMeatball)],
    [faCloudMoonRain], [#box(faCloudMoonRain)],
    [faCloudMoon], [#box(faCloudMoon)],
    [faCloudRain], [#box(faCloudRain)],
    [faCloudShowersHeavy], [#box(faCloudShowersHeavy)],
    [faCloudShowersWater], [#box(faCloudShowersWater)],
    [faCloudSunRain], [#box(faCloudSunRain)],
    [faCloudSun], [#box(faCloudSun)],
    [faCloud], [#box(faCloud)],
    [faClover], [#box(faClover)],
)])

#pagebreak()

== Co-Cu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faCodeBranch], [#box(faCodeBranch)],
    [faCodeCommit], [#box(faCodeCommit)],
    [faCodeCompare], [#box(faCodeCompare)],
    [faCodeFork], [#box(faCodeFork)],
    [faCodeMerge], [#box(faCodeMerge)],
    [faCodePullRequest], [#box(faCodePullRequest)],
    [faCode], [#box(faCode)],
    [faCoins], [#box(faCoins)],
    [faColonSign], [#box(faColonSign)],
    [faCommentDollar], [#box(faCommentDollar)],
    [faCommentDots], [#box(faCommentDots)],
    [faCommentMedical], [#box(faCommentMedical)],
    [faCommentSlash], [#box(faCommentSlash)],
    [faCommentSms], [#box(faCommentSms)],
    [faComment], [#box(faComment)],
    [faCommentsDollar], [#box(faCommentsDollar)],
    [faComments], [#box(faComments)],
    [faCompactDisc], [#box(faCompactDisc)],
    [faCompassDrafting], [#box(faCompassDrafting)],
    [faCompass], [#box(faCompass)],
    [faCompress], [#box(faCompress)],
    [faComputerMouse], [#box(faComputerMouse)],
    [faComputer], [#box(faComputer)],
    [faCookieBite], [#box(faCookieBite)],
    [faCookie], [#box(faCookie)],
    [faCopy], [#box(faCopy)],
    [faCopyright], [#box(faCopyright)],
    [faCouch], [#box(faCouch)],
    [faCow], [#box(faCow)],
    [faCreditCard], [#box(faCreditCard)],
    [faCropSimple], [#box(faCropSimple)],
    [faCrop], [#box(faCrop)],
    [faCross], [#box(faCross)],
    [faCrosshairs], [#box(faCrosshairs)],
    [faCrow], [#box(faCrow)],
    [faCrown], [#box(faCrown)],
    [faCrutch], [#box(faCrutch)],
    [faCruzeiroSign], [#box(faCruzeiroSign)],
    [faCube], [#box(faCube)],
    [faCubesStacked], [#box(faCubesStacked)],
    [faCubes], [#box(faCubes)],
)])

#pagebreak()

== D-E

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faD], [#box(faD)],
    [faDatabase], [#box(faDatabase)],
    [faDeleteLeft], [#box(faDeleteLeft)],
    [faDemocrat], [#box(faDemocrat)],
    [faDesktop], [#box(faDesktop)],
    [faDharmachakra], [#box(faDharmachakra)],
    [faDiagramNext], [#box(faDiagramNext)],
    [faDiagramPredecessor], [#box(faDiagramPredecessor)],
    [faDiagramProject], [#box(faDiagramProject)],
    [faDiagramSuccessor], [#box(faDiagramSuccessor)],
    [faDiamondTurnRight], [#box(faDiamondTurnRight)],
    [faDiamond], [#box(faDiamond)],
    [faDiceD6], [#box(faDiceD6)],
    [faDiceD20], [#box(faDiceD20)],
    [faDiceFive], [#box(faDiceFive)],
    [faDiceFour], [#box(faDiceFour)],
    [faDiceOne], [#box(faDiceOne)],
    [faDiceSix], [#box(faDiceSix)],
    [faDiceThree], [#box(faDiceThree)],
    [faDiceTwo], [#box(faDiceTwo)],
    [faDice], [#box(faDice)],
    [faDisease], [#box(faDisease)],
    [faDisplay], [#box(faDisplay)],
    [faDivide], [#box(faDivide)],
    [faDna], [#box(faDna)],
    [faDog], [#box(faDog)],
    [faDollarSign], [#box(faDollarSign)],
    [faDolly], [#box(faDolly)],
    [faDongSign], [#box(faDongSign)],
    [faDoorClosed], [#box(faDoorClosed)],
    [faDoorOpen], [#box(faDoorOpen)],
    [faDove], [#box(faDove)],
    [faDownLeftAndUpRightToCenter], [#box(faDownLeftAndUpRightToCenter)],
    [faDownLong], [#box(faDownLong)],
    [faDownload], [#box(faDownload)],
    [faDragon], [#box(faDragon)],
    [faDrawPolygon], [#box(faDrawPolygon)],
    [faDropletSlash], [#box(faDropletSlash)],
    [faDroplet], [#box(faDroplet)],
    [faDrumSteelpan], [#box(faDrumSteelpan)],
    [faDrum], [#box(faDrum)],
    [faDrumstickBite], [#box(faDrumstickBite)],
    [faDumbbell], [#box(faDumbbell)],
    [faDumpsterFire], [#box(faDumpsterFire)],
    [faDumpster], [#box(faDumpster)],
    [faDungeon], [#box(faDungeon)],
    [faE], [#box(faE)],
    [faEarDeaf], [#box(faEarDeaf)],
    [faEarListen], [#box(faEarListen)],
    [faEarthAfrica], [#box(faEarthAfrica)],
    [faEarthAmericas], [#box(faEarthAmericas)],
    [faEarthAsia], [#box(faEarthAsia)],
    [faEarthEurope], [#box(faEarthEurope)],
    [faEarthOceania], [#box(faEarthOceania)],
    [faEgg], [#box(faEgg)],
    [faEject], [#box(faEject)],
    [faElevator], [#box(faElevator)],
    [faEllipsisVertical], [#box(faEllipsisVertical)],
    [faEllipsis], [#box(faEllipsis)],
    [faEnvelopeCircleCheck], [#box(faEnvelopeCircleCheck)],
    [faEnvelopeOpenText], [#box(faEnvelopeOpenText)],
    [faEnvelopeOpen], [#box(faEnvelopeOpen)],
    [faEnvelope], [#box(faEnvelope)],
    [faEnvelopesBulk], [#box(faEnvelopesBulk)],
    [faEquals], [#box(faEquals)],
    [faEraser], [#box(faEraser)],
    [faEthernet], [#box(faEthernet)],
    [faEuroSign], [#box(faEuroSign)],
    [faExclamation], [#box(faExclamation)],
    [faExpand], [#box(faExpand)],
    [faExplosion], [#box(faExplosion)],
    [faEyeDropper], [#box(faEyeDropper)],
    [faEyeLowVision], [#box(faEyeLowVision)],
    [faEyeSlash], [#box(faEyeSlash)],
    [faEye], [#box(faEye)],
)])

#pagebreak()

== F-Fl

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faF], [#box(faF)],
    [faFaceAngry], [#box(faFaceAngry)],
    [faFaceDizzy], [#box(faFaceDizzy)],
    [faFaceFlushed], [#box(faFaceFlushed)],
    [faFaceFrownOpen], [#box(faFaceFrownOpen)],
    [faFaceFrown], [#box(faFaceFrown)],
    [faFaceGrimace], [#box(faFaceGrimace)],
    [faFaceGrinBeamSweat], [#box(faFaceGrinBeamSweat)],
    [faFaceGrinBeam], [#box(faFaceGrinBeam)],
    [faFaceGrinHearts], [#box(faFaceGrinHearts)],
    [faFaceGrinSquintTears], [#box(faFaceGrinSquintTears)],
    [faFaceGrinSquint], [#box(faFaceGrinSquint)],
    [faFaceGrinStars], [#box(faFaceGrinStars)],
    [faFaceGrinTears], [#box(faFaceGrinTears)],
    [faFaceGrinTongueSquint], [#box(faFaceGrinTongueSquint)],
    [faFaceGrinTongueWink], [#box(faFaceGrinTongueWink)],
    [faFaceGrinTongue], [#box(faFaceGrinTongue)],
    [faFaceGrinWide], [#box(faFaceGrinWide)],
    [faFaceGrinWink], [#box(faFaceGrinWink)],
    [faFaceGrin], [#box(faFaceGrin)],
    [faFaceKissBeam], [#box(faFaceKissBeam)],
    [faFaceKissWinkHeart], [#box(faFaceKissWinkHeart)],
    [faFaceKiss], [#box(faFaceKiss)],
    [faFaceLaughBeam], [#box(faFaceLaughBeam)],
    [faFaceLaughSquint], [#box(faFaceLaughSquint)],
    [faFaceLaughWink], [#box(faFaceLaughWink)],
    [faFaceLaugh], [#box(faFaceLaugh)],
    [faFaceMehBlank], [#box(faFaceMehBlank)],
    [faFaceMeh], [#box(faFaceMeh)],
    [faFaceRollingEyes], [#box(faFaceRollingEyes)],
    [faFaceSadCry], [#box(faFaceSadCry)],
    [faFaceSadTear], [#box(faFaceSadTear)],
    [faFaceSmileBeam], [#box(faFaceSmileBeam)],
    [faFaceSmileWink], [#box(faFaceSmileWink)],
    [faFaceSmile], [#box(faFaceSmile)],
    [faFaceSurprise], [#box(faFaceSurprise)],
    [faFaceTired], [#box(faFaceTired)],
    [faFan], [#box(faFan)],
    [faFaucetDrip], [#box(faFaucetDrip)],
    [faFaucet], [#box(faFaucet)],
    [faFax], [#box(faFax)],
    [faFeatherPointed], [#box(faFeatherPointed)],
    [faFeather], [#box(faFeather)],
    [faFerry], [#box(faFerry)],
    [faFileArrowDown], [#box(faFileArrowDown)],
    [faFileArrowUp], [#box(faFileArrowUp)],
    [faFileAudio], [#box(faFileAudio)],
    [faFileCircleCheck], [#box(faFileCircleCheck)],
    [faFileCircleExclamation], [#box(faFileCircleExclamation)],
    [faFileCircleMinus], [#box(faFileCircleMinus)],
    [faFileCirclePlus], [#box(faFileCirclePlus)],
    [faFileCircleQuestion], [#box(faFileCircleQuestion)],
    [faFileCircleXmark], [#box(faFileCircleXmark)],
    [faFileCode], [#box(faFileCode)],
    [faFileContract], [#box(faFileContract)],
    [faFileCsv], [#box(faFileCsv)],
    [faFileExcel], [#box(faFileExcel)],
    [faFileExport], [#box(faFileExport)],
    [faFileImage], [#box(faFileImage)],
    [faFileImport], [#box(faFileImport)],
    [faFileInvoiceDollar], [#box(faFileInvoiceDollar)],
    [faFileInvoice], [#box(faFileInvoice)],
    [faFileLines], [#box(faFileLines)],
    [faFileMedical], [#box(faFileMedical)],
    [faFilePdf], [#box(faFilePdf)],
    [faFilePen], [#box(faFilePen)],
    [faFilePowerpoint], [#box(faFilePowerpoint)],
    [faFilePrescription], [#box(faFilePrescription)],
    [faFileShield], [#box(faFileShield)],
    [faFileSignature], [#box(faFileSignature)],
    [faFileVideo], [#box(faFileVideo)],
    [faFileWaveform], [#box(faFileWaveform)],
    [faFileWord], [#box(faFileWord)],
    [faFileZipper], [#box(faFileZipper)],
    [faFile], [#box(faFile)],
    [faFillDrip], [#box(faFillDrip)],
    [faFill], [#box(faFill)],
    [faFilm], [#box(faFilm)],
    [faFilterCircleDollar], [#box(faFilterCircleDollar)],
    [faFilterCircleXmark], [#box(faFilterCircleXmark)],
    [faFilter], [#box(faFilter)],
    [faFingerprint], [#box(faFingerprint)],
    [faFireBurner], [#box(faFireBurner)],
    [faFireExtinguisher], [#box(faFireExtinguisher)],
    [faFireFlameCurved], [#box(faFireFlameCurved)],
    [faFireFlameSimple], [#box(faFireFlameSimple)],
    [faFire], [#box(faFire)],
    [faFishFins], [#box(faFishFins)],
    [faFish], [#box(faFish)],
    [faFlagCheckered], [#box(faFlagCheckered)],
    [faFlagUsa], [#box(faFlagUsa)],
    [faFlag], [#box(faFlag)],
    [faFlaskVial], [#box(faFlaskVial)],
    [faFlask], [#box(faFlask)],
    [faFloppyDisk], [#box(faFloppyDisk)],
    [faFlorinSign], [#box(faFlorinSign)],
)])

#pagebreak()

== Fo-Fu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFolderClosed], [#box(faFolderClosed)],
    [faFolderMinus], [#box(faFolderMinus)],
    [faFolderOpen], [#box(faFolderOpen)],
    [faFolderPlus], [#box(faFolderPlus)],
    [faFolderTree], [#box(faFolderTree)],
    [faFolder], [#box(faFolder)],
    [faFontAwesome], [#box(faFontAwesome)],
    [faFont], [#box(faFont)],
    [faFootball], [#box(faFootball)],
    [faForwardFast], [#box(faForwardFast)],
    [faForwardStep], [#box(faForwardStep)],
    [faForward], [#box(faForward)],
    [faFrancSign], [#box(faFrancSign)],
    [faFrog], [#box(faFrog)],
    [faFutbol], [#box(faFutbol)],
)])

== G

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faG], [#box(faG)],
    [faGamepad], [#box(faGamepad)],
    [faGasPump], [#box(faGasPump)],
    [faGaugeHigh], [#box(faGaugeHigh)],
    [faGaugeSimpleHigh], [#box(faGaugeSimpleHigh)],
    [faGaugeSimple], [#box(faGaugeSimple)],
    [faGauge], [#box(faGauge)],
    [faGavel], [#box(faGavel)],
    [faGear], [#box(faGear)],
    [faGears], [#box(faGears)],
    [faGem], [#box(faGem)],
    [faGenderless], [#box(faGenderless)],
    [faGhost], [#box(faGhost)],
    [faGift], [#box(faGift)],
    [faGifts], [#box(faGifts)],
    [faGlassWaterDroplet], [#box(faGlassWaterDroplet)],
    [faGlassWater], [#box(faGlassWater)],
    [faGlasses], [#box(faGlasses)],
    [faGlobe], [#box(faGlobe)],
    [faGolfBallTee], [#box(faGolfBallTee)],
    [faGopuram], [#box(faGopuram)],
    [faGraduationCap], [#box(faGraduationCap)],
    [faGreaterThanEqual], [#box(faGreaterThanEqual)],
    [faGreaterThan], [#box(faGreaterThan)],
    [faGripLinesVertical], [#box(faGripLinesVertical)],
    [faGripLines], [#box(faGripLines)],
    [faGripVertical], [#box(faGripVertical)],
    [faGrip], [#box(faGrip)],
    [faGroupArrowsRotate], [#box(faGroupArrowsRotate)],
    [faGuaraniSign], [#box(faGuaraniSign)],
    [faGuitar], [#box(faGuitar)],
    [faGun], [#box(faGun)],
)])

#pagebreak()

== H-Hi

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faH], [#box(faH)],
    [faHammer], [#box(faHammer)],
    [faHamsa], [#box(faHamsa)],
    [faHandBackFist], [#box(faHandBackFist)],
    [faHandDots], [#box(faHandDots)],
    [faHandFist], [#box(faHandFist)],
    [faHandHoldingDollar], [#box(faHandHoldingDollar)],
    [faHandHoldingDroplet], [#box(faHandHoldingDroplet)],
    [faHandHoldingHand], [#box(faHandHoldingHand)],
    [faHandHoldingHeart], [#box(faHandHoldingHeart)],
    [faHandHoldingMedical], [#box(faHandHoldingMedical)],
    [faHandHolding], [#box(faHandHolding)],
    [faHandLizard], [#box(faHandLizard)],
    [faHandMiddleFinger], [#box(faHandMiddleFinger)],
    [faHandPeace], [#box(faHandPeace)],
    [faHandPointDown], [#box(faHandPointDown)],
    [faHandPointLeft], [#box(faHandPointLeft)],
    [faHandPointRight], [#box(faHandPointRight)],
    [faHandPointUp], [#box(faHandPointUp)],
    [faHandPointer], [#box(faHandPointer)],
    [faHandScissors], [#box(faHandScissors)],
    [faHandSparkles], [#box(faHandSparkles)],
    [faHandSpock], [#box(faHandSpock)],
    [faHand], [#box(faHand)],
    [faHandcuffs], [#box(faHandcuffs)],
    [faHandsAslInterpreting], [#box(faHandsAslInterpreting)],
    [faHandsBound], [#box(faHandsBound)],
    [faHandsBubbles], [#box(faHandsBubbles)],
    [faHandsClapping], [#box(faHandsClapping)],
    [faHandsHoldingChild], [#box(faHandsHoldingChild)],
    [faHandsHoldingCircle], [#box(faHandsHoldingCircle)],
    [faHandsHolding], [#box(faHandsHolding)],
    [faHandsPraying], [#box(faHandsPraying)],
    [faHands], [#box(faHands)],
    [faHandshakeAngle], [#box(faHandshakeAngle)],
    [faHandshakeSimpleSlash], [#box(faHandshakeSimpleSlash)],
    [faHandshakeSimple], [#box(faHandshakeSimple)],
    [faHandshakeSlash], [#box(faHandshakeSlash)],
    [faHandshake], [#box(faHandshake)],
    [faHanukiah], [#box(faHanukiah)],
    [faHardDrive], [#box(faHardDrive)],
    [faHashtag], [#box(faHashtag)],
    [faHatCowboySide], [#box(faHatCowboySide)],
    [faHatCowboy], [#box(faHatCowboy)],
    [faHatWizard], [#box(faHatWizard)],
    [faHeadSideCoughSlash], [#box(faHeadSideCoughSlash)],
    [faHeadSideCough], [#box(faHeadSideCough)],
    [faHeadSideMask], [#box(faHeadSideMask)],
    [faHeadSideVirus], [#box(faHeadSideVirus)],
    [faHeading], [#box(faHeading)],
    [faHeadphonesSimple], [#box(faHeadphonesSimple)],
    [faHeadphones], [#box(faHeadphones)],
    [faHeadset], [#box(faHeadset)],
    [faHeartCircleBolt], [#box(faHeartCircleBolt)],
    [faHeartCircleCheck], [#box(faHeartCircleCheck)],
    [faHeartCircleExclamation], [#box(faHeartCircleExclamation)],
    [faHeartCircleMinus], [#box(faHeartCircleMinus)],
    [faHeartCirclePlus], [#box(faHeartCirclePlus)],
    [faHeartCircleXmark], [#box(faHeartCircleXmark)],
    [faHeartCrack], [#box(faHeartCrack)],
    [faHeartPulse], [#box(faHeartPulse)],
    [faHeart], [#box(faHeart)],
    [faHelicopterSymbol], [#box(faHelicopterSymbol)],
    [faHelicopter], [#box(faHelicopter)],
    [faHelmetSafety], [#box(faHelmetSafety)],
    [faHelmetUn], [#box(faHelmetUn)],
    [faHighlighter], [#box(faHighlighter)],
    [faHillAvalanche], [#box(faHillAvalanche)],
    [faHillRockslide], [#box(faHillRockslide)],
    [faHippo], [#box(faHippo)],
)])

#pagebreak()

== Ho

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faHockeyPuck], [#box(faHockeyPuck)],
    [faHollyBerry], [#box(faHollyBerry)],
    [faHorseHead], [#box(faHorseHead)],
    [faHorse], [#box(faHorse)],
    [faHospitalUser], [#box(faHospitalUser)],
    [faHospital], [#box(faHospital)],
    [faHotTubPerson], [#box(faHotTubPerson)],
    [faHotdog], [#box(faHotdog)],
    [faHotel], [#box(faHotel)],
    [faHourglassEnd], [#box(faHourglassEnd)],
    [faHourglassHalf], [#box(faHourglassHalf)],
    [faHourglassStart], [#box(faHourglassStart)],
    [faHourglass], [#box(faHourglass)],
    [faHouseChimneyCrack], [#box(faHouseChimneyCrack)],
    [faHouseChimneyMedical], [#box(faHouseChimneyMedical)],
    [faHouseChimneyUser], [#box(faHouseChimneyUser)],
    [faHouseChimneyWindow], [#box(faHouseChimneyWindow)],
    [faHouseChimney], [#box(faHouseChimney)],
    [faHouseCircleCheck], [#box(faHouseCircleCheck)],
    [faHouseCircleExclamation], [#box(faHouseCircleExclamation)],
    [faHouseCircleXmark], [#box(faHouseCircleXmark)],
    [faHouseCrack], [#box(faHouseCrack)],
    [faHouseFire], [#box(faHouseFire)],
    [faHouseFlag], [#box(faHouseFlag)],
    [faHouseFloodWaterCircleArrowRight], [#box(faHouseFloodWaterCircleArrowRight)],
    [faHouseFloodWater], [#box(faHouseFloodWater)],
    [faHouseLaptop], [#box(faHouseLaptop)],
    [faHouseLock], [#box(faHouseLock)],
    [faHouseMedicalCircleCheck], [#box(faHouseMedicalCircleCheck)],
    [faHouseMedicalCircleExclamation], [#box(faHouseMedicalCircleExclamation)],
    [faHouseMedicalCircleXmark], [#box(faHouseMedicalCircleXmark)],
    [faHouseMedicalFlag], [#box(faHouseMedicalFlag)],
    [faHouseMedical], [#box(faHouseMedical)],
    [faHouseSignal], [#box(faHouseSignal)],
    [faHouseTsunami], [#box(faHouseTsunami)],
    [faHouseUser], [#box(faHouseUser)],
    [faHouse], [#box(faHouse)],
    [faHryvniaSign], [#box(faHryvniaSign)],
    [faHurricane], [#box(faHurricane)],
    [faICursor], [#box(faICursor)],
)])

== I-J

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faI], [#box(faI)],
    [faIceCream], [#box(faIceCream)],
    [faIcicles], [#box(faIcicles)],
    [faIcons], [#box(faIcons)],
    [faIdBadge], [#box(faIdBadge)],
    [faIdCardClip], [#box(faIdCardClip)],
    [faIdCard], [#box(faIdCard)],
    [faIgloo], [#box(faIgloo)],
    [faImagePortrait], [#box(faImagePortrait)],
    [faImage], [#box(faImage)],
    [faImages], [#box(faImages)],
    [faInbox], [#box(faInbox)],
    [faIndent], [#box(faIndent)],
    [faIndianRupeeSign], [#box(faIndianRupeeSign)],
    [faIndustry], [#box(faIndustry)],
    [faInfinity], [#box(faInfinity)],
    [faInfo], [#box(faInfo)],
    [faItalic], [#box(faItalic)],
    [faJ], [#box(faJ)],
    [faJarWheat], [#box(faJarWheat)],
    [faJar], [#box(faJar)],
    [faJedi], [#box(faJedi)],
    [faJetFighterUp], [#box(faJetFighterUp)],
    [faJetFighter], [#box(faJetFighter)],
    [faJoint], [#box(faJoint)],
    [faJugDetergent], [#box(faJugDetergent)],
    [faK], [#box(faK)],
    [faKaaba], [#box(faKaaba)],
    [faKey], [#box(faKey)],
    [faKeyboard], [#box(faKeyboard)],
    [faKhanda], [#box(faKhanda)],
    [faKipSign], [#box(faKipSign)],
    [faKitMedical], [#box(faKitMedical)],
    [faKitchenSet], [#box(faKitchenSet)],
    [faKiwiBird], [#box(faKiwiBird)],
)])

#pagebreak()

== L

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faL], [#box(faL)],
    [faLandMineOn], [#box(faLandMineOn)],
    [faLandmarkDome], [#box(faLandmarkDome)],
    [faLandmarkFlag], [#box(faLandmarkFlag)],
    [faLandmark], [#box(faLandmark)],
    [faLanguage], [#box(faLanguage)],
    [faLaptopCode], [#box(faLaptopCode)],
    [faLaptopFile], [#box(faLaptopFile)],
    [faLaptopMedical], [#box(faLaptopMedical)],
    [faLaptop], [#box(faLaptop)],
    [faLariSign], [#box(faLariSign)],
    [faLayerGroup], [#box(faLayerGroup)],
    [faLeaf], [#box(faLeaf)],
    [faLeftLong], [#box(faLeftLong)],
    [faLeftRight], [#box(faLeftRight)],
    [faLemon], [#box(faLemon)],
    [faLessThanEqual], [#box(faLessThanEqual)],
    [faLessThan], [#box(faLessThan)],
    [faLifeRing], [#box(faLifeRing)],
    [faLightbulb], [#box(faLightbulb)],
    [faLinesLeaning], [#box(faLinesLeaning)],
    [faLinkSlash], [#box(faLinkSlash)],
    [faLink], [#box(faLink)],
    [faLiraSign], [#box(faLiraSign)],
    [faListCheck], [#box(faListCheck)],
    [faListOl], [#box(faListOl)],
    [faListUl], [#box(faListUl)],
    [faList], [#box(faList)],
    [faLitecoinSign], [#box(faLitecoinSign)],
    [faLocationArrow], [#box(faLocationArrow)],
    [faLocationCrosshairs], [#box(faLocationCrosshairs)],
    [faLocationDot], [#box(faLocationDot)],
    [faLocationPinLock], [#box(faLocationPinLock)],
    [faLocationPin], [#box(faLocationPin)],
    [faLockOpen], [#box(faLockOpen)],
    [faLock], [#box(faLock)],
    [faLocust], [#box(faLocust)],
    [faLungsVirus], [#box(faLungsVirus)],
    [faLungs], [#box(faLungs)],
)])

== M-Mi

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faM], [#box(faM)],
    [faMagnet], [#box(faMagnet)],
    [faMagnifyingGlassArrowRight], [#box(faMagnifyingGlassArrowRight)],
    [faMagnifyingGlassChart], [#box(faMagnifyingGlassChart)],
    [faMagnifyingGlassDollar], [#box(faMagnifyingGlassDollar)],
    [faMagnifyingGlassLocation], [#box(faMagnifyingGlassLocation)],
    [faMagnifyingGlassMinus], [#box(faMagnifyingGlassMinus)],
    [faMagnifyingGlassPlus], [#box(faMagnifyingGlassPlus)],
    [faMagnifyingGlass], [#box(faMagnifyingGlass)],
    [faManatSign], [#box(faManatSign)],
    [faMapLocationDot], [#box(faMapLocationDot)],
    [faMapLocation], [#box(faMapLocation)],
    [faMapPin], [#box(faMapPin)],
    [faMap], [#box(faMap)],
    [faMarker], [#box(faMarker)],
    [faMarsAndVenusBurst], [#box(faMarsAndVenusBurst)],
    [faMarsAndVenus], [#box(faMarsAndVenus)],
    [faMarsDouble], [#box(faMarsDouble)],
    [faMarsStrokeRight], [#box(faMarsStrokeRight)],
    [faMarsStrokeUp], [#box(faMarsStrokeUp)],
    [faMarsStroke], [#box(faMarsStroke)],
    [faMars], [#box(faMars)],
    [faMartiniGlassCitrus], [#box(faMartiniGlassCitrus)],
    [faMartiniGlassEmpty], [#box(faMartiniGlassEmpty)],
    [faMartiniGlass], [#box(faMartiniGlass)],
    [faMaskFace], [#box(faMaskFace)],
    [faMaskVentilator], [#box(faMaskVentilator)],
    [faMask], [#box(faMask)],
    [faMasksTheater], [#box(faMasksTheater)],
    [faMattressPillow], [#box(faMattressPillow)],
    [faMaximize], [#box(faMaximize)],
    [faMedal], [#box(faMedal)],
    [faMemory], [#box(faMemory)],
    [faMenorah], [#box(faMenorah)],
    [faMercury], [#box(faMercury)],
    [faMessage], [#box(faMessage)],
    [faMeteor], [#box(faMeteor)],
    [faMicrochip], [#box(faMicrochip)],
    [faMicrophoneLinesSlash], [#box(faMicrophoneLinesSlash)],
    [faMicrophoneLines], [#box(faMicrophoneLines)],
    [faMicrophoneSlash], [#box(faMicrophoneSlash)],
    [faMicrophone], [#box(faMicrophone)],
    [faMicroscope], [#box(faMicroscope)],
    [faMillSign], [#box(faMillSign)],
    [faMinimize], [#box(faMinimize)],
    [faMinus], [#box(faMinus)],
    [faMitten], [#box(faMitten)],
)])

#pagebreak()

== Mo-Mu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faMobileButton], [#box(faMobileButton)],
    [faMobileRetro], [#box(faMobileRetro)],
    [faMobileScreenButton], [#box(faMobileScreenButton)],
    [faMobileScreen], [#box(faMobileScreen)],
    [faMobile], [#box(faMobile)],
    [faMoneyBill1Wave], [#box(faMoneyBill1Wave)],
    [faMoneyBill1], [#box(faMoneyBill1)],
    [faMoneyBillTransfer], [#box(faMoneyBillTransfer)],
    [faMoneyBillTrendUp], [#box(faMoneyBillTrendUp)],
    [faMoneyBillWave], [#box(faMoneyBillWave)],
    [faMoneyBillWheat], [#box(faMoneyBillWheat)],
    [faMoneyBill], [#box(faMoneyBill)],
    [faMoneyBills], [#box(faMoneyBills)],
    [faMoneyCheckDollar], [#box(faMoneyCheckDollar)],
    [faMoneyCheck], [#box(faMoneyCheck)],
    [faMonument], [#box(faMonument)],
    [faMoon], [#box(faMoon)],
    [faMortarPestle], [#box(faMortarPestle)],
    [faMosque], [#box(faMosque)],
    [faMosquitoNet], [#box(faMosquitoNet)],
    [faMosquito], [#box(faMosquito)],
    [faMotorcycle], [#box(faMotorcycle)],
    [faMound], [#box(faMound)],
    [faMountainCity], [#box(faMountainCity)],
    [faMountainSun], [#box(faMountainSun)],
    [faMountain], [#box(faMountain)],
    [faMugHot], [#box(faMugHot)],
    [faMugSaucer], [#box(faMugSaucer)],
    [faMusic], [#box(faMusic)],
)])

== N

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faN], [#box(faN)],
    [faNairaSign], [#box(faNairaSign)],
    [faNetworkWired], [#box(faNetworkWired)],
    [faNeuter], [#box(faNeuter)],
    [faNewspaper], [#box(faNewspaper)],
    [faNotEqual], [#box(faNotEqual)],
    [faNotdef], [#box(faNotdef)],
    [faNoteSticky], [#box(faNoteSticky)],
    [faNotesMedical], [#box(faNotesMedical)],
    [faO], [#box(faO)],
    [faObjectGroup], [#box(faObjectGroup)],
    [faObjectUngroup], [#box(faObjectUngroup)],
    [faOilCan], [#box(faOilCan)],
    [faOilWell], [#box(faOilWell)],
    [faOm], [#box(faOm)],
    [faOtter], [#box(faOtter)],
    [faOutdent], [#box(faOutdent)],
)])

== P-Pep

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faP], [#box(faP)],
    [faPager], [#box(faPager)],
    [faPaintRoller], [#box(faPaintRoller)],
    [faPaintbrush], [#box(faPaintbrush)],
    [faPalette], [#box(faPalette)],
    [faPallet], [#box(faPallet)],
    [faPanorama], [#box(faPanorama)],
    [faPaperPlane], [#box(faPaperPlane)],
    [faPaperclip], [#box(faPaperclip)],
    [faParachuteBox], [#box(faParachuteBox)],
    [faParagraph], [#box(faParagraph)],
    [faPassport], [#box(faPassport)],
    [faPaste], [#box(faPaste)],
    [faPause], [#box(faPause)],
    [faPaw], [#box(faPaw)],
    [faPeace], [#box(faPeace)],
    [faPenClip], [#box(faPenClip)],
    [faPenFancy], [#box(faPenFancy)],
    [faPenNib], [#box(faPenNib)],
    [faPenRuler], [#box(faPenRuler)],
    [faPenToSquare], [#box(faPenToSquare)],
    [faPen], [#box(faPen)],
    [faPencil], [#box(faPencil)],
    [faPeopleArrows], [#box(faPeopleArrows)],
    [faPeopleCarryBox], [#box(faPeopleCarryBox)],
    [faPeopleGroup], [#box(faPeopleGroup)],
    [faPeopleLine], [#box(faPeopleLine)],
    [faPeoplePulling], [#box(faPeoplePulling)],
    [faPeopleRobbery], [#box(faPeopleRobbery)],
    [faPeopleRoof], [#box(faPeopleRoof)],
    [faPepperHot], [#box(faPepperHot)],
)])

#pagebreak()

== Per-Pu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faPercent], [#box(faPercent)],
    [faPersonArrowDownToLine], [#box(faPersonArrowDownToLine)],
    [faPersonArrowUpFromLine], [#box(faPersonArrowUpFromLine)],
    [faPersonBiking], [#box(faPersonBiking)],
    [faPersonBooth], [#box(faPersonBooth)],
    [faPersonBreastfeeding], [#box(faPersonBreastfeeding)],
    [faPersonBurst], [#box(faPersonBurst)],
    [faPersonCane], [#box(faPersonCane)],
    [faPersonChalkboard], [#box(faPersonChalkboard)],
    [faPersonCircleCheck], [#box(faPersonCircleCheck)],
    [faPersonCircleExclamation], [#box(faPersonCircleExclamation)],
    [faPersonCircleMinus], [#box(faPersonCircleMinus)],
    [faPersonCirclePlus], [#box(faPersonCirclePlus)],
    [faPersonCircleQuestion], [#box(faPersonCircleQuestion)],
    [faPersonCircleXmark], [#box(faPersonCircleXmark)],
    [faPersonDigging], [#box(faPersonDigging)],
    [faPersonDotsFromLine], [#box(faPersonDotsFromLine)],
    [faPersonDressBurst], [#box(faPersonDressBurst)],
    [faPersonDress], [#box(faPersonDress)],
    [faPersonDrowning], [#box(faPersonDrowning)],
    [faPersonFallingBurst], [#box(faPersonFallingBurst)],
    [faPersonFalling], [#box(faPersonFalling)],
    [faPersonHalfDress], [#box(faPersonHalfDress)],
    [faPersonHarassing], [#box(faPersonHarassing)],
    [faPersonHiking], [#box(faPersonHiking)],
    [faPersonMilitaryPointing], [#box(faPersonMilitaryPointing)],
    [faPersonMilitaryRifle], [#box(faPersonMilitaryRifle)],
    [faPersonMilitaryToPerson], [#box(faPersonMilitaryToPerson)],
    [faPersonPraying], [#box(faPersonPraying)],
    [faPersonPregnant], [#box(faPersonPregnant)],
    [faPersonRays], [#box(faPersonRays)],
    [faPersonRifle], [#box(faPersonRifle)],
    [faPersonRunning], [#box(faPersonRunning)],
    [faPersonShelter], [#box(faPersonShelter)],
    [faPersonSkating], [#box(faPersonSkating)],
    [faPersonSkiingNordic], [#box(faPersonSkiingNordic)],
    [faPersonSkiing], [#box(faPersonSkiing)],
    [faPersonSnowboarding], [#box(faPersonSnowboarding)],
    [faPersonSwimming], [#box(faPersonSwimming)],
    [faPersonThroughWindow], [#box(faPersonThroughWindow)],
    [faPersonWalkingArrowLoopLeft], [#box(faPersonWalkingArrowLoopLeft)],
    [faPersonWalkingArrowRight], [#box(faPersonWalkingArrowRight)],
    [faPersonWalkingDashedLineArrowRight], [#box(faPersonWalkingDashedLineArrowRight)],
    [faPersonWalkingLuggage], [#box(faPersonWalkingLuggage)],
    [faPersonWalkingWithCane], [#box(faPersonWalkingWithCane)],
    [faPersonWalking], [#box(faPersonWalking)],
    [faPerson], [#box(faPerson)],
    [faPesetaSign], [#box(faPesetaSign)],
    [faPesoSign], [#box(faPesoSign)],
    [faPhoneFlip], [#box(faPhoneFlip)],
    [faPhoneSlash], [#box(faPhoneSlash)],
    [faPhoneVolume], [#box(faPhoneVolume)],
    [faPhone], [#box(faPhone)],
    [faPhotoFilm], [#box(faPhotoFilm)],
    [faPiggyBank], [#box(faPiggyBank)],
    [faPills], [#box(faPills)],
    [faPizzaSlice], [#box(faPizzaSlice)],
    [faPlaceOfWorship], [#box(faPlaceOfWorship)],
    [faPlaneArrival], [#box(faPlaneArrival)],
    [faPlaneCircleCheck], [#box(faPlaneCircleCheck)],
    [faPlaneCircleExclamation], [#box(faPlaneCircleExclamation)],
    [faPlaneCircleXmark], [#box(faPlaneCircleXmark)],
    [faPlaneDeparture], [#box(faPlaneDeparture)],
    [faPlaneLock], [#box(faPlaneLock)],
    [faPlaneSlash], [#box(faPlaneSlash)],
    [faPlaneUp], [#box(faPlaneUp)],
    [faPlane], [#box(faPlane)],
    [faPlantWilt], [#box(faPlantWilt)],
    [faPlateWheat], [#box(faPlateWheat)],
    [faPlay], [#box(faPlay)],
    [faPlugCircleBolt], [#box(faPlugCircleBolt)],
    [faPlugCircleCheck], [#box(faPlugCircleCheck)],
    [faPlugCircleExclamation], [#box(faPlugCircleExclamation)],
    [faPlugCircleMinus], [#box(faPlugCircleMinus)],
    [faPlugCirclePlus], [#box(faPlugCirclePlus)],
    [faPlugCircleXmark], [#box(faPlugCircleXmark)],
    [faPlug], [#box(faPlug)],
    [faPlusMinus], [#box(faPlusMinus)],
    [faPlus], [#box(faPlus)],
    [faPodcast], [#box(faPodcast)],
    [faPooStorm], [#box(faPooStorm)],
    [faPoo], [#box(faPoo)],
    [faPoop], [#box(faPoop)],
    [faPowerOff], [#box(faPowerOff)],
    [faPrescriptionBottleMedical], [#box(faPrescriptionBottleMedical)],
    [faPrescriptionBottle], [#box(faPrescriptionBottle)],
    [faPrescription], [#box(faPrescription)],
    [faPrint], [#box(faPrint)],
    [faPumpMedical], [#box(faPumpMedical)],
    [faPumpSoap], [#box(faPumpSoap)],
    [faPuzzlePiece], [#box(faPuzzlePiece)],
)])

== Q-R

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faQ], [#box(faQ)],
    [faQrcode], [#box(faQrcode)],
    [faQuestion], [#box(faQuestion)],
    [faQuoteLeft], [#box(faQuoteLeft)],
    [faQuoteRight], [#box(faQuoteRight)],
    [faR], [#box(faR)],
    [faRadiation], [#box(faRadiation)],
    [faRadio], [#box(faRadio)],
    [faRainbow], [#box(faRainbow)],
    [faRankingStar], [#box(faRankingStar)],
    [faReceipt], [#box(faReceipt)],
    [faRecordVinyl], [#box(faRecordVinyl)],
    [faRectangleAd], [#box(faRectangleAd)],
    [faRectangleList], [#box(faRectangleList)],
    [faRectangleXmark], [#box(faRectangleXmark)],
    [faRecycle], [#box(faRecycle)],
    [faRegistered], [#box(faRegistered)],
    [faRepeat], [#box(faRepeat)],
    [faReplyAll], [#box(faReplyAll)],
    [faReply], [#box(faReply)],
    [faRepublican], [#box(faRepublican)],
    [faRestroom], [#box(faRestroom)],
    [faRetweet], [#box(faRetweet)],
    [faRibbon], [#box(faRibbon)],
    [faRightFromBracket], [#box(faRightFromBracket)],
    [faRightLeft], [#box(faRightLeft)],
    [faRightLong], [#box(faRightLong)],
    [faRightToBracket], [#box(faRightToBracket)],
    [faRing], [#box(faRing)],
    [faRoadBarrier], [#box(faRoadBarrier)],
    [faRoadBridge], [#box(faRoadBridge)],
    [faRoadCircleCheck], [#box(faRoadCircleCheck)],
    [faRoadCircleExclamation], [#box(faRoadCircleExclamation)],
    [faRoadCircleXmark], [#box(faRoadCircleXmark)],
    [faRoadLock], [#box(faRoadLock)],
    [faRoadSpikes], [#box(faRoadSpikes)],
    [faRoad], [#box(faRoad)],
    [faRobot], [#box(faRobot)],
    [faRocket], [#box(faRocket)],
    [faRotateLeft], [#box(faRotateLeft)],
    [faRotateRight], [#box(faRotateRight)],
    [faRotate], [#box(faRotate)],
    [faRoute], [#box(faRoute)],
    [faRss], [#box(faRss)],
    [faRubleSign], [#box(faRubleSign)],
    [faRug], [#box(faRug)],
    [faRulerCombined], [#box(faRulerCombined)],
    [faRulerHorizontal], [#box(faRulerHorizontal)],
    [faRulerVertical], [#box(faRulerVertical)],
    [faRuler], [#box(faRuler)],
    [faRupeeSign], [#box(faRupeeSign)],
    [faRupiahSign], [#box(faRupiahSign)],
)])

== S-Se

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faS], [#box(faS)],
    [faSackDollar], [#box(faSackDollar)],
    [faSackXmark], [#box(faSackXmark)],
    [faSailboat], [#box(faSailboat)],
    [faSatelliteDish], [#box(faSatelliteDish)],
    [faSatellite], [#box(faSatellite)],
    [faScaleBalanced], [#box(faScaleBalanced)],
    [faScaleUnbalancedFlip], [#box(faScaleUnbalancedFlip)],
    [faScaleUnbalanced], [#box(faScaleUnbalanced)],
    [faSchoolCircleCheck], [#box(faSchoolCircleCheck)],
    [faSchoolCircleExclamation], [#box(faSchoolCircleExclamation)],
    [faSchoolCircleXmark], [#box(faSchoolCircleXmark)],
    [faSchoolFlag], [#box(faSchoolFlag)],
    [faSchoolLock], [#box(faSchoolLock)],
    [faSchool], [#box(faSchool)],
    [faScissors], [#box(faScissors)],
    [faScrewdriverWrench], [#box(faScrewdriverWrench)],
    [faScrewdriver], [#box(faScrewdriver)],
    [faScrollTorah], [#box(faScrollTorah)],
    [faScroll], [#box(faScroll)],
    [faSdCard], [#box(faSdCard)],
    [faSection], [#box(faSection)],
    [faSeedling], [#box(faSeedling)],
    [faServer], [#box(faServer)],
)])

#pagebreak()

== Sh-Sq

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faShapes], [#box(faShapes)],
    [faShareFromSquare], [#box(faShareFromSquare)],
    [faShareNodes], [#box(faShareNodes)],
    [faShare], [#box(faShare)],
    [faSheetPlastic], [#box(faSheetPlastic)],
    [faShekelSign], [#box(faShekelSign)],
    [faShieldCat], [#box(faShieldCat)],
    [faShieldDog], [#box(faShieldDog)],
    [faShieldHalved], [#box(faShieldHalved)],
    [faShieldHeart], [#box(faShieldHeart)],
    [faShieldVirus], [#box(faShieldVirus)],
    [faShield], [#box(faShield)],
    [faShip], [#box(faShip)],
    [faShirt], [#box(faShirt)],
    [faShoePrints], [#box(faShoePrints)],
    [faShopLock], [#box(faShopLock)],
    [faShopSlash], [#box(faShopSlash)],
    [faShop], [#box(faShop)],
    [faShower], [#box(faShower)],
    [faShrimp], [#box(faShrimp)],
    [faShuffle], [#box(faShuffle)],
    [faShuttleSpace], [#box(faShuttleSpace)],
    [faSignHanging], [#box(faSignHanging)],
    [faSignal], [#box(faSignal)],
    [faSignature], [#box(faSignature)],
    [faSignsPost], [#box(faSignsPost)],
    [faSimCard], [#box(faSimCard)],
    [faSink], [#box(faSink)],
    [faSitemap], [#box(faSitemap)],
    [faSkullCrossbones], [#box(faSkullCrossbones)],
    [faSkull], [#box(faSkull)],
    [faSlash], [#box(faSlash)],
    [faSleigh], [#box(faSleigh)],
    [faSliders], [#box(faSliders)],
    [faSmog], [#box(faSmog)],
    [faSmoking], [#box(faSmoking)],
    [faSnowflake], [#box(faSnowflake)],
    [faSnowman], [#box(faSnowman)],
    [faSnowplow], [#box(faSnowplow)],
    [faSoap], [#box(faSoap)],
    [faSocks], [#box(faSocks)],
    [faSolarPanel], [#box(faSolarPanel)],
    [faSortDown], [#box(faSortDown)],
    [faSortUp], [#box(faSortUp)],
    [faSort], [#box(faSort)],
    [faSpa], [#box(faSpa)],
    [faSpaghettiMonsterFlying], [#box(faSpaghettiMonsterFlying)],
    [faSpellCheck], [#box(faSpellCheck)],
    [faSpider], [#box(faSpider)],
    [faSpinner], [#box(faSpinner)],
    [faSplotch], [#box(faSplotch)],
    [faSpoon], [#box(faSpoon)],
    [faSprayCanSparkles], [#box(faSprayCanSparkles)],
    [faSprayCan], [#box(faSprayCan)],
    [faSquareArrowUpRight], [#box(faSquareArrowUpRight)],
    [faSquareCaretDown], [#box(faSquareCaretDown)],
    [faSquareCaretLeft], [#box(faSquareCaretLeft)],
    [faSquareCaretRight], [#box(faSquareCaretRight)],
    [faSquareCaretUp], [#box(faSquareCaretUp)],
    [faSquareCheck], [#box(faSquareCheck)],
    [faSquareEnvelope], [#box(faSquareEnvelope)],
    [faSquareFull], [#box(faSquareFull)],
    [faSquareH], [#box(faSquareH)],
    [faSquareMinus], [#box(faSquareMinus)],
    [faSquareNfi], [#box(faSquareNfi)],
    [faSquareParking], [#box(faSquareParking)],
    [faSquarePen], [#box(faSquarePen)],
    [faSquarePersonConfined], [#box(faSquarePersonConfined)],
    [faSquarePhoneFlip], [#box(faSquarePhoneFlip)],
    [faSquarePhone], [#box(faSquarePhone)],
    [faSquarePlus], [#box(faSquarePlus)],
    [faSquarePollHorizontal], [#box(faSquarePollHorizontal)],
    [faSsquarePollVertical], [#box(faSsquarePollVertical)],
    [faSquareRootVariable], [#box(faSquareRootVariable)],
    [faSquareRss], [#box(faSquareRss)],
    [faSquareShareNodes], [#box(faSquareShareNodes)],
    [faSquareUpRight], [#box(faSquareUpRight)],
    [faSquareVirus], [#box(faSquareVirus)],
    [faSquareXmark], [#box(faSquareXmark)],
    [faSquare], [#box(faSquare)],
)])

#pagebreak()

== St-Sy

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faStaffSnake], [#box(faStaffSnake)],
    [faStairs], [#box(faStairs)],
    [faStamp], [#box(faStamp)],
    [faStapler], [#box(faStapler)],
    [faStarAndCrescent], [#box(faStarAndCrescent)],
    [faStarHalfStroke], [#box(faStarHalfStroke)],
    [faStarHalf], [#box(faStarHalf)],
    [faStarOfDavid], [#box(faStarOfDavid)],
    [faStarOfLife], [#box(faStarOfLife)],
    [faStar], [#box(faStar)],
    [faSterlingSign], [#box(faSterlingSign)],
    [faStethoscope], [#box(faStethoscope)],
    [faStop], [#box(faStop)],
    [faStopwatch], [#box(faStopwatch)],
    [faStopwatch], [#box(faStopwatch)],
    [faStoreSlash], [#box(faStoreSlash)],
    [faStore], [#box(faStore)],
    [faStreetView], [#box(faStreetView)],
    [faStrikethrough], [#box(faStrikethrough)],
    [faStroopwafel], [#box(faStroopwafel)],
    [faSubscript], [#box(faSubscript)],
    [faSuitcaseMedical], [#box(faSuitcaseMedical)],
    [faSuitcaseRolling], [#box(faSuitcaseRolling)],
    [faSuitcase], [#box(faSuitcase)],
    [faSunPlantWilt], [#box(faSunPlantWilt)],
    [faSun], [#box(faSun)],
    [faSuperscript], [#box(faSuperscript)],
    [faSwatchbook], [#box(faSwatchbook)],
    [faSynagogue], [#box(faSynagogue)],
    [faSyringe], [#box(faSyringe)],
)])

== T-Ti

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faT], [#box(faT)],
    [faTableCellsLarge], [#box(faTableCellsLarge)],
    [faTableCells], [#box(faTableCells)],
    [faTableColumns], [#box(faTableColumns)],
    [faTableList], [#box(faTableList)],
    [faTableTennisPaddleBall], [#box(faTableTennisPaddleBall)],
    [faTable], [#box(faTable)],
    [faTabletButton], [#box(faTabletButton)],
    [faTabletScreenButton], [#box(faTabletScreenButton)],
    [faTablet], [#box(faTablet)],
    [faTablets], [#box(faTablets)],
    [faTachographDigital], [#box(faTachographDigital)],
    [faTag], [#box(faTag)],
    [faTags], [#box(faTags)],
    [faTape], [#box(faTape)],
    [faTarpDroplet], [#box(faTarpDroplet)],
    [faTarp], [#box(faTarp)],
    [faTaxi], [#box(faTaxi)],
    [faTeethOpen], [#box(faTeethOpen)],
    [faTeeth], [#box(faTeeth)],
    [faTemperatureArrowDown], [#box(faTemperatureArrowDown)],
    [faTemperatureArrowUp], [#box(faTemperatureArrowUp)],
    [faTemperatureEmpty], [#box(faTemperatureEmpty)],
    [faTemperatureFull], [#box(faTemperatureFull)],
    [faTemperatureHalf], [#box(faTemperatureHalf)],
    [faTemperatureHigh], [#box(faTemperatureHigh)],
    [faTemperatureLow], [#box(faTemperatureLow)],
    [faTemperatureQuarter], [#box(faTemperatureQuarter)],
    [faTemperatureThreeQuarters], [#box(faTemperatureThreeQuarters)],
    [faTengeSign], [#box(faTengeSign)],
    [faTentArrowDownToLine], [#box(faTentArrowDownToLine)],
    [faTentArrowLeftRight], [#box(faTentArrowLeftRight)],
    [faTentArrowTurnLeft], [#box(faTentArrowTurnLeft)],
    [faTentArrowsDown], [#box(faTentArrowsDown)],
    [faTent], [#box(faTent)],
    [faTents], [#box(faTents)],
    [faTerminal], [#box(faTerminal)],
    [faTextHeight], [#box(faTextHeight)],
    [faTextSlash], [#box(faTextSlash)],
    [faTextWidth], [#box(faTextWidth)],
    [faThermometer], [#box(faThermometer)],
    [faThumbsDown], [#box(faThumbsDown)],
    [faThumbsUp], [#box(faThumbsUp)],
    [faThumbtack], [#box(faThumbtack)],
    [faTicketSimple], [#box(faTicketSimple)],
    [faTicket], [#box(faTicket)],
    [faTimeline], [#box(faTimeline)],
)])

#pagebreak()

== To

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faToggleOff], [#box(faToggleOff)],
    [faToggleOn], [#box(faToggleOn)],
    [faToiletPaperSlash], [#box(faToiletPaperSlash)],
    [faToiletPaper], [#box(faToiletPaper)],
    [faToiletPortable], [#box(faToiletPortable)],
    [faToilet], [#box(faToilet)],
    [faToiletsPortable], [#box(faToiletsPortable)],
    [faToolbox], [#box(faToolbox)],
    [faTooth], [#box(faTooth)],
    [faToriiGate], [#box(faToriiGate)],
    [faTornado], [#box(faTornado)],
    [faTowerBroadcast], [#box(faTowerBroadcast)],
    [faTowerCell], [#box(faTowerCell)],
    [faTowerObservation], [#box(faTowerObservation)],
    [faTractor], [#box(faTractor)],
    [faTrademark], [#box(faTrademark)],
    [faTrafficLight], [#box(faTrafficLight)],
    [faTrailer], [#box(faTrailer)],
    [faTrainSubway], [#box(faTrainSubway)],
    [faTrainTram], [#box(faTrainTram)],
    [faTrain], [#box(faTrain)],
    [faTransgender], [#box(faTransgender)],
    [faTrashArrowUp], [#box(faTrashArrowUp)],
    [faTrashCanArrowUp], [#box(faTrashCanArrowUp)],
    [faTrashCan], [#box(faTrashCan)],
    [faTrash], [#box(faTrash)],
    [faTreeCity], [#box(faTreeCity)],
    [faTree], [#box(faTree)],
    [faTriangleExclamation], [#box(faTriangleExclamation)],
    [faTrophy], [#box(faTrophy)],
    [faTrowelBricks], [#box(faTrowelBricks)],
    [faTrowel], [#box(faTrowel)],
    [faTruckArrowRight], [#box(faTruckArrowRight)],
    [faTruckDroplet], [#box(faTruckDroplet)],
    [faTruckFast], [#box(faTruckFast)],
    [faTruckFieldUn], [#box(faTruckFieldUn)],
    [faTruckField], [#box(faTruckField)],
    [faTruckFront], [#box(faTruckFront)],
    [faTruckMedical], [#box(faTruckMedical)],
    [faTruckMonster], [#box(faTruckMonster)],
    [faTruckMoving], [#box(faTruckMoving)],
    [faTruckPickup], [#box(faTruckPickup)],
    [faTruckPlane], [#box(faTruckPlane)],
    [faTruckRampBox], [#box(faTruckRampBox)],
    [faTruck], [#box(faTruck)],
    [faTty], [#box(faTty)],
    [faTurkishLiraSign], [#box(faTurkishLiraSign)],
    [faTurnDown], [#box(faTurnDown)],
    [faTurnUp], [#box(faTurnUp)],
    [faTv], [#box(faTv)],
)])

#pagebreak()

== U-V

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faU], [#box(faU)],
    [faUmbrellaBeach], [#box(faUmbrellaBeach)],
    [faUmbrella], [#box(faUmbrella)],
    [faUnderline], [#box(faUnderline)],
    [faUniversalAccess], [#box(faUniversalAccess)],
    [faUnlockKeyhole], [#box(faUnlockKeyhole)],
    [faUnlock], [#box(faUnlock)],
    [faUpDownLeftRight], [#box(faUpDownLeftRight)],
    [faUpDown], [#box(faUpDown)],
    [faUpLong], [#box(faUpLong)],
    [faUpRightAndDownLeftFromCenter], [#box(faUpRightAndDownLeftFromCenter)],
    [faUpRightFromSquare], [#box(faUpRightFromSquare)],
    [faUpload], [#box(faUpload)],
    [faUserAstronaut], [#box(faUserAstronaut)],
    [faUserCheck], [#box(faUserCheck)],
    [faUserClock], [#box(faUserClock)],
    [faUserDoctor], [#box(faUserDoctor)],
    [faUserGear], [#box(faUserGear)],
    [faUserGraduate], [#box(faUserGraduate)],
    [faUserGroup], [#box(faUserGroup)],
    [faUserInjured], [#box(faUserInjured)],
    [faUserLargeSlash], [#box(faUserLargeSlash)],
    [faUserLarge], [#box(faUserLarge)],
    [faUserLock], [#box(faUserLock)],
    [faUserMinus], [#box(faUserMinus)],
    [faUserNinja], [#box(faUserNinja)],
    [faUserNurse], [#box(faUserNurse)],
    [faUserPen], [#box(faUserPen)],
    [faUserPlus], [#box(faUserPlus)],
    [faUserSecret], [#box(faUserSecret)],
    [faUserShield], [#box(faUserShield)],
    [faUserSlash], [#box(faUserSlash)],
    [faUserTag], [#box(faUserTag)],
    [faUserTie], [#box(faUserTie)],
    [faUserXmark], [#box(faUserXmark)],
    [faUser], [#box(faUser)],
    [faUsersBetweenLines], [#box(faUsersBetweenLines)],
    [faUsersGear], [#box(faUsersGear)],
    [faUsersLine], [#box(faUsersLine)],
    [faUsersRays], [#box(faUsersRays)],
    [faUsersRectangle], [#box(faUsersRectangle)],
    [faUsersSlash], [#box(faUsersSlash)],
    [faUsersViewfinder], [#box(faUsersViewfinder)],
    [faUsers], [#box(faUsers)],
    [faUtensils], [#box(faUtensils)],
    [faV], [#box(faV)],
    [faVanShuttle], [#box(faVanShuttle)],
    [faVault], [#box(faVault)],
    [faVectorSquare], [#box(faVectorSquare)],
    [faVenusDouble], [#box(faVenusDouble)],
    [faVenusMars], [#box(faVenusMars)],
    [faVenus], [#box(faVenus)],
    [faVestPatches], [#box(faVestPatches)],
    [faVest], [#box(faVest)],
    [faVialCircleCheck], [#box(faVialCircleCheck)],
    [faVialVirus], [#box(faVialVirus)],
    [faVial], [#box(faVial)],
    [faVials], [#box(faVials)],
    [faVideoSlash], [#box(faVideoSlash)],
    [faVideo], [#box(faVideo)],
    [faVihara], [#box(faVihara)],
    [faVirusCovidSlash], [#box(faVirusCovidSlash)],
    [faVirusCovid], [#box(faVirusCovid)],
    [faVirusSlash], [#box(faVirusSlash)],
    [faVirus], [#box(faVirus)],
    [faViruses], [#box(faViruses)],
    [faVoicemail], [#box(faVoicemail)],
    [faVolcano], [#box(faVolcano)],
    [faVolleyball], [#box(faVolleyball)],
    [faVolumeHigh], [#box(faVolumeHigh)],
    [faVolumeLow], [#box(faVolumeLow)],
    [faVolumeOff], [#box(faVolumeOff)],
    [faVolumeXmark], [#box(faVolumeXmark)],
    [faVrCardboard], [#box(faVrCardboard)],
)])

#pagebreak()

== W-Z

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faW], [#box(faW)],
    [faWalkieTalkie], [#box(faWalkieTalkie)],
    [faWallet], [#box(faWallet)],
    [faWandMagicSparkles], [#box(faWandMagicSparkles)],
    [faWandMagic], [#box(faWandMagic)],
    [faWandSparkles], [#box(faWandSparkles)],
    [faWarehouse], [#box(faWarehouse)],
    [faWaterLadder], [#box(faWaterLadder)],
    [faWater], [#box(faWater)],
    [faWaveSquare], [#box(faWaveSquare)],
    [faWeightHanging], [#box(faWeightHanging)],
    [faWeightScale], [#box(faWeightScale)],
    [faWheatAwnCircleExclamation], [#box(faWheatAwnCircleExclamation)],
    [faWheatAwn], [#box(faWheatAwn)],
    [faWheelchairMove], [#box(faWheelchairMove)],
    [faWheelchair], [#box(faWheelchair)],
    [faWhiskeyGlass], [#box(faWhiskeyGlass)],
    [faWifi], [#box(faWifi)],
    [faWind], [#box(faWind)],
    [faWindowMaximize], [#box(faWindowMaximize)],
    [faWindowMinimize], [#box(faWindowMinimize)],
    [faWindowRestore], [#box(faWindowRestore)],
    [faWineBottle], [#box(faWineBottle)],
    [faWineGlassEmpty], [#box(faWineGlassEmpty)],
    [faWineGlass], [#box(faWineGlass)],
    [faWonSign], [#box(faWonSign)],
    [faWorm], [#box(faWorm)],
    [faWrench], [#box(faWrench)],
    [faXRay], [#box(faXRay)],
    [faX], [#box(faX)],
    [faXmark], [#box(faXmark)],
    [faXmarksLines], [#box(faXmarksLines)],
    [faY], [#box(faY)],
    [faYenSign], [#box(faYenSign)],
    [faYinYang], [#box(faYinYang)],
    [faZ], [#box(faZ)],
)])

== 0-9

#figure(
align(center)[#table(
    columns: 10,
    align: center,
    [fa0], [#box(fa0)],
    [fa1], [#box(fa1)],
    [fa2], [#box(fa2)],
    [fa3], [#box(fa3)],
    [fa4], [#box(fa4)],
    [fa5], [#box(fa5)],
    [fa6], [#box(fa6)],
    [fa7], [#box(fa7)],
    [fa8], [#box(fa8)],
    [fa9], [#box(fa9)],
)])
