#import "fontawesome.typ": *

#let title = "Typst-FontAwesome"

#set page(
    paper: "a4",
      header: [
        #set text(6pt)
      ],
    numbering: "1"
)
#set heading(
  level: 2,
  numbering: "1.",
)
#set par(
  first-line-indent: 2em,
  justify: true,
  leading: 1em,
  linebreaks: "optimized"
)
#set block(above: 1em, below: 1em)

#align(center, text(18pt)[
      *#title*
])

#outline(
   title: [],
   indent: auto
)

#pagebreak()

= Brands

== A-H

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faAdn], [#icon(faAdn)],
    [faAdversal], [#icon(faAdversal)],
    [faAirbnb], [#icon(faAirbnb)],
    [faAlgolia], [#icon(faAlgolia)],
    [faAlipay], [#icon(faAlipay)],
    [faAmazon], [#icon(faAmazon)],
    [faAmazonPay], [#icon(faAmazonPay)],
    [faAmazonPayCc], [#icon(faAmazonPayCc)],
    [faAndroid], [#icon(faAndroid)],
    [faAngular], [#icon(faAngular)],
    [faApple], [#icon(faApple)],
    [faApplePay], [#icon(faApplePay)],
    [faApplePayCc], [#icon(faApplePayCc)],
    [faAppStore], [#icon(faAppStore)],
    [faAppStoreIos], [#icon(faAppStoreIos)],
    [faAtlassian], [#icon(faAtlassian)],
    [faAudible], [#icon(faAudible)],
    [faAws], [#icon(faAws)],
    [faBehance], [#icon(faBehance)],
    [faBehanceSquare], [#icon(faBehanceSquare)],
    [faBilibili], [#icon(faBilibili)],
    [faBitbucket], [#icon(faBitbucket)],
    [faBitcoin], [#icon(faBitcoin)],
    [faBlackberry], [#icon(faBlackberry)],
    [faBluetooth], [#icon(faBluetooth)],
    [faBluetoothB], [#icon(faBluetoothB)],
    [faBootstrap], [#icon(faBootstrap)],
    [faBuffer], [#icon(faBuffer)],
    [faCentos], [#icon(faCentos)],
    [faChrome], [#icon(faChrome)],
    [faChromecast], [#icon(faChromecast)],
    [faCloudflare], [#icon(faCloudflare)],
    [faCss3], [#icon(faCss3)],
    [faCss3Alt], [#icon(faCss3Alt)],
    [faDev], [#icon(faDev)],
    [faDHL], [#icon(faDHL)],
    [faDiscord], [#icon(faDiscord)],
    [faDiscordBots], [#icon(faDiscordBots)],
    [faDiscourse], [#icon(faDiscourse)],
    [faDocker], [#icon(faDocker)],
    [faDropbox], [#icon(faDropbox)],
    [faDrupal], [#icon(faDrupal)],
    [faEarlybirds], [#icon(faEarlybirds)],
    [faEbay], [#icon(faEbay)],
    [faEdge], [#icon(faEdge)],
    [faEdgeLegacy], [#icon(faEdgeLegacy)],
    [faErlang], [#icon(faErlang)],
    [faEthereum], [#icon(faEthereum)],
    [faEvernote], [#icon(faEvernote)],
    [faFacebook], [#icon(faFacebook)],
    [faFacebookF], [#icon(faFacebookF)],
    [faFacebookMessenger], [#icon(faFacebookMessenger)],
    [faFacebookSquare], [#icon(faFacebookSquare)],
    [faFedex], [#icon(faFedex)],
    [faFedora], [#icon(faFedora)],
    [faFigma], [#icon(faFigma)],
    [faFirefox], [#icon(faFirefox)],
    [faFirefoxBrowser], [#icon(faFirefoxBrowser)],
    [faFlickr], [#icon(faFlickr)],
    [faFontAwesome], [#icon(faFontAwesome)],
    [faFontAwesomeSquare], [#icon(faFontAwesomeSquare)],
    [faFontAwesomeSquareStroke], [#icon(faFontAwesomeSquareStroke)],
    [faFreebsd], [#icon(faFreebsd)],
    [faGetPocket], [#icon(faGetPocket)],
    [faGit], [#icon(faGit)],
    [faGitAlt], [#icon(faGitAlt)],
    [faGithub], [#icon(faGithub)],
    [faGithubAlt], [#icon(faGithubAlt)],
    [faGithubSquare], [#icon(faGithubSquare)],
    [faGitkraken], [#icon(faGitkraken)],
    [faGitlab], [#icon(faGitlab)],
    [faGitlabSquare], [#icon(faGitlabSquare)],
    [faGitSquare], [#icon(faGitSquare)],
    [faGitter], [#icon(faGitter)],
    [faGolang], [#icon(faGolang)],
    [faGoogle], [#icon(faGoogle)],
    [faGoogleDrive], [#icon(faGoogleDrive)],
    [faGooglePay], [#icon(faGooglePay)],
    [faGooglePlay], [#icon(faGooglePlay)],
    [faGooglePlus], [#icon(faGooglePlus)],
    [faGooglePlusG], [#icon(faGooglePlusG)],
    [faGooglePlusSquare], [#icon(faGooglePlusSquare)],
    [faGoogleWallet], [#icon(faGoogleWallet)],
    [faGrunt], [#icon(faGrunt)],
    [faGulp], [#icon(faGulp)],
    [faHive], [#icon(faHive)],
    [faHtml5], [#icon(faHtml5)],
)])

#pagebreak()

== I-Z

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faInstagram], [#icon(faInstagram)],
    [faInstagramSquare], [#icon(faInstagramSquare)],
    [faInternetExplorer], [#icon(faInternetExplorer)],
    [faItunes], [#icon(faItunes)],
    [faItunesNote], [#icon(faItunesNote)],
    [faJava], [#icon(faJava)],
    [faJenkins], [#icon(faJenkins)],
    [faJira], [#icon(faJira)],
    [faJoomla], [#icon(faJoomla)],
    [faJs], [#icon(faJs)],
    [faJsSquare], [#icon(faJsSquare)],
    [faKaggle], [#icon(faKaggle)],
    [faLaravel], [#icon(faLaravel)],
    [faLastfm], [#icon(faLastfm)],
    [faLastfmSquare], [#icon(faLastfmSquare)],
    [faLeanpub], [#icon(faLeanpub)],
    [faLess], [#icon(faLess)],
    [faLine], [#icon(faLine)],
    [faLinkedin], [#icon(faLinkedin)],
    [faLinkedinIn], [#icon(faLinkedinIn)],
    [faLinux], [#icon(faLinux)],
    [faMarkdown], [#icon(faMarkdown)],
    [faMastercardCc], [#icon(faMastercardCc)],
    [faMastodon], [#icon(faMastodon)],
    [faMdb], [#icon(faMdb)],
    [faMedium], [#icon(faMedium)],
    [faMendeley], [#icon(faMendeley)],
    [faMeta], [#icon(faMeta)],
    [faMicrosoft], [#icon(faMicrosoft)],
    [faNode], [#icon(faNode)],
    [faNodeJS], [#icon(faNodeJS)],
    [faNpm], [#icon(faNpm)],
    [faOpera], [#icon(faOpera)],
    [faOsi], [#icon(faOsi)],
    [faPatreon], [#icon(faPatreon)],
    [faPaypal], [#icon(faPaypal)],
    [faPaypalCc], [#icon(faPaypalCc)],
    [faPhp], [#icon(faPhp)],
    [faPinterest], [#icon(faPinterest)],
    [faPinterestP], [#icon(faPinterestP)],
    [faPinterestSquare], [#icon(faPinterestSquare)],
    [faProductHunt], [#icon(faProductHunt)],
    [faPython], [#icon(faPython)],
    [faQq], [#icon(faQq)],
    [faQuora], [#icon(faQuora)],
    [faRaspberryPi], [#icon(faRaspberryPi)],
    [faReact], [#icon(faReact)],
    [faReadme], [#icon(faReadme)],
    [faReddit], [#icon(faReddit)],
    [faRedditAlien], [#icon(faRedditAlien)],
    [faRedditSquare], [#icon(faRedditSquare)],
    [faRedhat], [#icon(faRedhat)],
    [faRenren], [#icon(faRenren)],
    [faResearchgate], [#icon(faResearchgate)],
    [faRProject], [#icon(faRProject)],
    [faRust], [#icon(faRust)],
    [faSafari], [#icon(faSafari)],
    [faSalesforce], [#icon(faSalesforce)],
    [faSass], [#icon(faSass)],
    [faScribd], [#icon(faScribd)],
    [faShopify], [#icon(faShopify)],
    [faSketch], [#icon(faSketch)],
    [faSkype], [#icon(faSkype)],
    [faSlack], [#icon(faSlack)],
    [faSnapchat], [#icon(faSnapchat)],
    [faSnapchatSquare], [#icon(faSnapchatSquare)],
    [faSpotify], [#icon(faSpotify)],
    [faSteamSquare], [#icon(faSteamSquare)],
    [faStripeCc], [#icon(faStripeCc)],
    [faSuse], [#icon(faSuse)],
    [faSwift], [#icon(faSwift)],
    [faSymfony], [#icon(faSymfony)],
    [faTelegram], [#icon(faTelegram)],
    [faTencentWeibo], [#icon(faTencentWeibo)],
    [faTiktok], [#icon(faTiktok)],
    [faTrello], [#icon(faTrello)],
    [faTumblr], [#icon(faTumblr)],
    [faTumblrSquare], [#icon(faTumblrSquare)],
    [faTwitch], [#icon(faTwitch)],
    [faTwitter], [#icon(faTwitter)],
    [faTwitterSquare], [#icon(faTwitterSquare)],
    [faUber], [#icon(faUber)],
    [faUbuntu], [#icon(faUbuntu)],
    [faUnity], [#icon(faUnity)],
    [faUsb], [#icon(faUsb)],
    [faViadeoSquare], [#icon(faViadeoSquare)],
    [faViber], [#icon(faViber)],
    [faVimeo], [#icon(faVimeo)],
    [faVimeoSquare], [#icon(faVimeoSquare)],
    [faVimeoV], [#icon(faVimeoV)],
    [faVisa], [#icon(faVisa)],
    [faVk], [#icon(faVk)],
    [faVuejs], [#icon(faVuejs)],
    [faWeibo], [#icon(faWeibo)],
    [faWeixin], [#icon(faWeixin)],
    [faWhatsapp], [#icon(faWhatsapp)],
    [faWhatsappSquare], [#icon(faWhatsappSquare)],
    [faWikipedia], [#icon(faWikipedia)],
    [faWindows], [#icon(faWindows)],
    [faWordpress], [#icon(faWordpress)],
    [faWordpressSimple], [#icon(faWordpressSimple)],
    [faXbox], [#icon(faXbox)],
    [faYahoo], [#icon(faYahoo)],
    [faYandex], [#icon(faYandex)],
    [faYarn], [#icon(faYarn)],
    [faYCombinator], [#icon(faYCombinator)],
    [faYoutube], [#icon(faYoutube)],
    [faYoutubeSquare], [#icon(faYoutubeSquare)],
    [faZhihu], [#icon(faZhihu)]
)])

#pagebreak()

= Regular

== A-E

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faAddressBook], [#icon(faAddressBook)],
    [faAddressCard], [#icon(faAddressCard)],
    [faBellSlash], [#icon(faBellSlash)],
    [faBell], [#icon(faBell)],
    [faBookmark], [#icon(faBookmark)],
    [faBuilding], [#icon(faBuilding)],
    [faCalendarCheck], [#icon(faCalendarCheck)],
    [faCalendarDays], [#icon(faCalendarDays)],
    [faCalendarMinus], [#icon(faCalendarMinus)],
    [faCalendarPlus], [#icon(faCalendarPlus)],
    [faCalendarXmark], [#icon(faCalendarXmark)],
    [faCalendar], [#icon(faCalendar)],
    [faChartBar], [#icon(faChartBar)],
    [faChessBishop], [#icon(faChessBishop)],
    [faChessKing], [#icon(faChessKing)],
    [faChessKnight], [#icon(faChessKnight)],
    [faChessPawn], [#icon(faChessPawn)],
    [faChessQueen], [#icon(faChessQueen)],
    [faChessRook], [#icon(faChessRook)],
    [faCircleCheck], [#icon(faCircleCheck)],
    [faCircleDot], [#icon(faCircleDot)],
    [faCircleDown], [#icon(faCircleDown)],
    [faCircleLeft], [#icon(faCircleLeft)],
    [faCirclePause], [#icon(faCirclePause)],
    [faCirclePlay], [#icon(faCirclePlay)],
    [faCircleQuestion], [#icon(faCircleQuestion)],
    [faCircleRight], [#icon(faCircleRight)],
    [faCircleStop], [#icon(faCircleStop)],
    [faCircleUp], [#icon(faCircleUp)],
    [faCircleUser], [#icon(faCircleUser)],
    [faCircleXmark], [#icon(faCircleXmark)],
    [faCircle], [#icon(faCircle)],
    [faClipboard], [#icon(faClipboard)],
    [faClock], [#icon(faClock)],
    [faClone], [#icon(faClone)],
    [faClosedCaptioning], [#icon(faClosedCaptioning)],
    [faCommentDots], [#icon(faCommentDots)],
    [faComment], [#icon(faComment)],
    [faComments], [#icon(faComments)],
    [faCompass], [#icon(faCompass)],
    [faCopy], [#icon(faCopy)],
    [faCopyright], [#icon(faCopyright)],
    [faCreditCard], [#icon(faCreditCard)],
    [faEnvelopeOpen], [#icon(faEnvelopeOpen)],
    [faEnvelope], [#icon(faEnvelope)],
    [faEyeSlash], [#icon(faEyeSlash)],
    [faEye], [#icon(faEye)],
)])

#pagebreak()

== F

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFaceAngry], [#icon(faFaceAngry)],
    [faFaceDizzy], [#icon(faFaceDizzy)],
    [faFaceFlushed], [#icon(faFaceFlushed)],
    [faFaceFrownOpen], [#icon(faFaceFrownOpen)],
    [faFaceFrown], [#icon(faFaceFrown)],
    [faFaceGrimace], [#icon(faFaceGrimace)],
    [faFaceGrinBeamSweat], [#icon(faFaceGrinBeamSweat)],
    [faFaceGrinBeam], [#icon(faFaceGrinBeam)],
    [faFaceGrinHearts], [#icon(faFaceGrinHearts)],
    [faFaceGrinSquintTears], [#icon(faFaceGrinSquintTears)],
    [faFaceGrinSquint], [#icon(faFaceGrinSquint)],
    [faFaceGrinStars], [#icon(faFaceGrinStars)],
    [faFaceGrinTears], [#icon(faFaceGrinTears)],
    [faFaceGrinTongueSquint], [#icon(faFaceGrinTongueSquint)],
    [faFaceGrinTongueWink], [#icon(faFaceGrinTongueWink)],
    [faFaceGrinTongue], [#icon(faFaceGrinTongue)],
    [faFaceGrinWide], [#icon(faFaceGrinWide)],
    [faFaceGrinWink], [#icon(faFaceGrinWink)],
    [faFaceGrin], [#icon(faFaceGrin)],
    [faFaceKissBeam], [#icon(faFaceKissBeam)],
    [faFaceKissWinkHeart], [#icon(faFaceKissWinkHeart)],
    [faFaceKiss], [#icon(faFaceKiss)],
    [faFaceLaughBeam], [#icon(faFaceLaughBeam)],
    [faFaceLaughSquint], [#icon(faFaceLaughSquint)],
    [faFaceLaughWink], [#icon(faFaceLaughWink)],
    [faFaceLaugh], [#icon(faFaceLaugh)],
    [faFaceMehBlank], [#icon(faFaceMehBlank)],
    [faFaceMeh], [#icon(faFaceMeh)],
    [faFaceRollingEyes], [#icon(faFaceRollingEyes)],
    [faFaceSadCry], [#icon(faFaceSadCry)],
    [faFaceSadTear], [#icon(faFaceSadTear)],
    [faFaceSmileBeam], [#icon(faFaceSmileBeam)],
    [faFaceSmileWink], [#icon(faFaceSmileWink)],
    [faFaceSmile], [#icon(faFaceSmile)],
    [faFaceSurprise], [#icon(faFaceSurprise)],
    [faFaceTired], [#icon(faFaceTired)],
    [faFileAudio], [#icon(faFileAudio)],
    [faFileCode], [#icon(faFileCode)],
    [faFileExcel], [#icon(faFileExcel)],
    [faFileImage], [#icon(faFileImage)],
    [faFileLines], [#icon(faFileLines)],
    [faFilePdf], [#icon(faFilePdf)],
    [faFilePowerpoint], [#icon(faFilePowerpoint)],
    [faFileVideo], [#icon(faFileVideo)],
    [faFileWord], [#icon(faFileWord)],
    [faFileZipper], [#icon(faFileZipper)],
    [faFile], [#icon(faFile)],
    [faFlag], [#icon(faFlag)],
    [faFloppyDisk], [#icon(faFloppyDisk)],
    [faFolderClosed], [#icon(faFolderClosed)],
    [faFolderOpen], [#icon(faFolderOpen)],
    [faFolder], [#icon(faFolder)],
    [faFontAwesome], [#icon(faFontAwesome)],
    [faFutbol], [#icon(faFutbol)],
)])

#pagebreak()

== G-W

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faGem], [#icon(faGem)],
    [faHandBackFist], [#icon(faHandBackFist)],
    [faHandLizard], [#icon(faHandLizard)],
    [faHandPeace], [#icon(faHandPeace)],
    [faHandPointDown], [#icon(faHandPointDown)],
    [faHandPointLeft], [#icon(faHandPointLeft)],
    [faHandPointRight], [#icon(faHandPointRight)],
    [faHandPointUp], [#icon(faHandPointUp)],
    [faHandPointer], [#icon(faHandPointer)],
    [faHandScissors], [#icon(faHandScissors)],
    [faHandSpock], [#icon(faHandSpock)],
    [faHand], [#icon(faHand)],
    [faHandshake], [#icon(faHandshake)],
    [faHardDrive], [#icon(faHardDrive)],
    [faHeart], [#icon(faHeart)],
    [faHospital], [#icon(faHospital)],
    [faHourglassHalf], [#icon(faHourglassHalf)],
    [faHourglass], [#icon(faHourglass)],
    [faIdBadge], [#icon(faIdBadge)],
    [faIdCard], [#icon(faIdCard)],
    [faImage], [#icon(faImage)],
    [faImages], [#icon(faImages)],
    [faKeyboard], [#icon(faKeyboard)],
    [faLemon], [#icon(faLemon)],
    [faLifeRing], [#icon(faLifeRing)],
    [faLightbulb], [#icon(faLightbulb)],
    [faMap], [#icon(faMap)],
    [faMessage], [#icon(faMessage)],
    [faMoneyBill1], [#icon(faMoneyBill1)],
    [faMoon], [#icon(faMoon)],
    [faNewspaper], [#icon(faNewspaper)],
    [faNoteSticky], [#icon(faNoteSticky)],
    [faObjectGroup], [#icon(faObjectGroup)],
    [faObjectUngroup], [#icon(faObjectUngroup)],
    [faPaperPlane], [#icon(faPaperPlane)],
    [faPaste], [#icon(faPaste)],
    [faPenToSquare], [#icon(faPenToSquare)],
    [faRectangleList], [#icon(faRectangleList)],
    [faRectangleXmark], [#icon(faRectangleXmark)],
    [faRegistered], [#icon(faRegistered)],
    [faShareFromSquare], [#icon(faShareFromSquare)],
    [faSnowflake], [#icon(faSnowflake)],
    [faSquareCaretDown], [#icon(faSquareCaretDown)],
    [faSquareCaretLeft], [#icon(faSquareCaretLeft)],
    [faSquareCaretRight], [#icon(faSquareCaretRight)],
    [faSquareCaretUp], [#icon(faSquareCaretUp)],
    [faSquareCheck], [#icon(faSquareCheck)],
    [faSquareFull], [#icon(faSquareFull)],
    [faSquareMinus], [#icon(faSquareMinus)],
    [faSquarePlus], [#icon(faSquarePlus)],
    [faSquare], [#icon(faSquare)],
    [faStarHalfStroke], [#icon(faStarHalfStroke)],
    [faStarHalf], [#icon(faStarHalf)],
    [faStar], [#icon(faStar)],
    [faSun], [#icon(faSun)],
    [faThumbsDown], [#icon(faThumbsDown)],
    [faThumbsUp], [#icon(faThumbsUp)],
    [faTrashCan], [#icon(faTrashCan)],
    [faUser], [#icon(faUser)],
    [faWindowMaximize], [#icon(faWindowMaximize)],
    [faWindowMinimize], [#icon(faWindowMinimize)],
    [faWindowRestore], [#icon(faWindowRestore)],
)])

#pagebreak()

= Solid

== A

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faAS], [#icon(faAS)],
    [faAddressBookS], [#icon(faAddressBookS)],
    [faAddressCardS], [#icon(faAddressCardS)],
    [faAlignCenterS], [#icon(faAlignCenterS)],
    [faAlignJustifyS], [#icon(faAlignJustifyS)],
    [faAlignLeftS], [#icon(faAlignLeftS)],
    [faAlignRightS], [#icon(faAlignRightS)],
    [faAnchorCircleCheckS], [#icon(faAnchorCircleCheckS)],
    [faAnchorCircleExclamationS], [#icon(faAnchorCircleExclamationS)],
    [faAnchorCircleXmarkS], [#icon(faAnchorCircleXmarkS)],
    [faAnchorLockS], [#icon(faAnchorLockS)],
    [faAnchorS], [#icon(faAnchorS)],
    [faAngleDownS], [#icon(faAngleDownS)],
    [faAngleLeftS], [#icon(faAngleLeftS)],
    [faAngleRightS], [#icon(faAngleRightS)],
    [faAngleUpS], [#icon(faAngleUpS)],
    [faAnglesDownS], [#icon(faAnglesDownS)],
    [faAnglesLeftS], [#icon(faAnglesLeftS)],
    [faAnglesRightS], [#icon(faAnglesRightS)],
    [faAnglesUpS], [#icon(faAnglesUpS)],
    [faAnkhS], [#icon(faAnkhS)],
    [faAppleWholeS], [#icon(faAppleWholeS)],
    [faArchwayS], [#icon(faArchwayS)],
    [faArrowDown19S], [#icon(faArrowDown19S)],
    [faArrowDown91S], [#icon(faArrowDown91S)],
    [faArrowDownAZS], [#icon(faArrowDownAZS)],
    [faArrowDownLongS], [#icon(faArrowDownLongS)],
    [faArrowDownShortWideS], [#icon(faArrowDownShortWideS)],
    [faArrowDownUpAcrossLineS], [#icon(faArrowDownUpAcrossLineS)],
    [faArrowDownUpLockS], [#icon(faArrowDownUpLockS)],
    [faArrowDownWideShortS], [#icon(faArrowDownWideShortS)],
    [faArrowDownZAS], [#icon(faArrowDownZAS)],
    [faArrowDownS], [#icon(faArrowDownS)],
    [faArrowLeftLongS], [#icon(faArrowLeftLongS)],
    [faArrowLeftS], [#icon(faArrowLeftS)],
    [faArrowPointerS], [#icon(faArrowPointerS)],
    [faArrowRightArrowLeftS], [#icon(faArrowRightArrowLeftS)],
    [faArrowRightFromBracketS], [#icon(faArrowRightFromBracketS)],
    [faArrowRightLongS], [#icon(faArrowRightLongS)],
    [faArrowRightToBracketS], [#icon(faArrowRightToBracketS)],
    [faArrowRightToCityS], [#icon(faArrowRightToCityS)],
    [faArrowRightS], [#icon(faArrowRightS)],
    [faArrowRotateLeftS], [#icon(faArrowRotateLeftS)],
    [faArrowRotateRightS], [#icon(faArrowRotateRightS)],
    [faArrowTrendDownS], [#icon(faArrowTrendDownS)],
    [faArrowTrendUpS], [#icon(faArrowTrendUpS)],
    [faArrowTurnDownS], [#icon(faArrowTurnDownS)],
    [faArrowTurnUpS], [#icon(faArrowTurnUpS)],
    [faArrowUp19S], [#icon(faArrowUp19S)],
    [faArrowUp91S], [#icon(faArrowUp91S)],
    [faArrowUpAZS], [#icon(faArrowUpAZS)],
    [faArrowUpFromBracketS], [#icon(faArrowUpFromBracketS)],
    [faArrowUpFromGroundWaterS], [#icon(faArrowUpFromGroundWaterS)],
    [faArrowUpFromWaterPumpS], [#icon(faArrowUpFromWaterPumpS)],
    [faArrowUpLongS], [#icon(faArrowUpLongS)],
    [faArrowUpRightDotsS], [#icon(faArrowUpRightDotsS)],
    [faArrowUpRightFromSquareS], [#icon(faArrowUpRightFromSquareS)],
    [faArrowUpShortWideS], [#icon(faArrowUpShortWideS)],
    [faArrowUpWideShortS], [#icon(faArrowUpWideShortS)],
    [faArrowUpZAS], [#icon(faArrowUpZAS)],
    [faArrowUpS], [#icon(faArrowUpS)],
    [faArrowsDownToLineS], [#icon(faArrowsDownToLineS)],
    [faArrowsDownToPeopleS], [#icon(faArrowsDownToPeopleS)],
    [faArrowsLeftRightToLineS], [#icon(faArrowsLeftRightToLineS)],
    [faArrowsLeftRightS], [#icon(faArrowsLeftRightS)],
    [faArrowsRotateS], [#icon(faArrowsRotateS)],
    [faArrowsSpinS], [#icon(faArrowsSpinS)],
    [faArrowsSplitUpAndLeftS], [#icon(faArrowsSplitUpAndLeftS)],
    [faArrowsToCircleS], [#icon(faArrowsToCircleS)],
    [faArrowsToDotS], [#icon(faArrowsToDotS)],
    [faArrowsToEyeS], [#icon(faArrowsToEyeS)],
    [faArrowsTurnRightS], [#icon(faArrowsTurnRightS)],
    [faArrowsTurnToDotsS], [#icon(faArrowsTurnToDotsS)],
    [faArrowsUpDownLeftRightS], [#icon(faArrowsUpDownLeftRightS)],
    [faArrowsUpDownS], [#icon(faArrowsUpDownS)],
    [faArrowsUpToLineS], [#icon(faArrowsUpToLineS)],
    [faAsteriskS], [#icon(faAsteriskS)],
    [faAtS], [#icon(faAtS)],
    [faAtomS], [#icon(faAtomS)],
    [faAudioDescriptionS], [#icon(faAudioDescriptionS)],
    [faAustralSignS], [#icon(faAustralSignS)],
    [faAwardS], [#icon(faAwardS)],
)])

#pagebreak()

== B-Br

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faBS], [#icon(faBS)],
    [faBabyCarriageS], [#icon(faBabyCarriageS)],
    [faBabyS], [#icon(faBabyS)],
    [faBackwardFastS], [#icon(faBackwardFastS)],
    [faBackwardStepS], [#icon(faBackwardStepS)],
    [faBackwardS], [#icon(faBackwardS)],
    [faBaconS], [#icon(faBaconS)],
    [faBacteriaS], [#icon(faBacteriaS)],
    [faBacteriumS], [#icon(faBacteriumS)],
    [faBagShoppingS], [#icon(faBagShoppingS)],
    [faBahaiS], [#icon(faBahaiS)],
    [faBahtSignS], [#icon(faBahtSignS)],
    [faBanSmokingS], [#icon(faBanSmokingS)],
    [faBanS], [#icon(faBanS)],
    [faBandageS], [#icon(faBandageS)],
    [faSbangladeshiTakaSignS], [#icon(faSbangladeshiTakaSignS)],
    [faBarcodeS], [#icon(faBarcodeS)],
    [faBarsProgressS], [#icon(faBarsProgressS)],
    [faBarsStaggeredS], [#icon(faBarsStaggeredS)],
    [faBarsS], [#icon(faBarsS)],
    [faBaseballBatBallS], [#icon(faBaseballBatBallS)],
    [faBaseballS], [#icon(faBaseballS)],
    [faBasketShoppingS], [#icon(faBasketShoppingS)],
    [faBasketballS], [#icon(faBasketballS)],
    [faBathS], [#icon(faBathS)],
    [faBatteryEmptyS], [#icon(faBatteryEmptyS)],
    [faBatteryFullS], [#icon(faBatteryFullS)],
    [faBatteryHalfS], [#icon(faBatteryHalfS)],
    [faBatteryQuarterS], [#icon(faBatteryQuarterS)],
    [faBatteryThreeQuartersS], [#icon(faBatteryThreeQuartersS)],
    [faBedPulseS], [#icon(faBedPulseS)],
    [faBedS], [#icon(faBedS)],
    [faBeerMugEmptyS], [#icon(faBeerMugEmptyS)],
    [faBellConciergeS], [#icon(faBellConciergeS)],
    [faBellSlashS], [#icon(faBellSlashS)],
    [faBellS], [#icon(faBellS)],
    [faBezierCurveS], [#icon(faBezierCurveS)],
    [faBicycleS], [#icon(faBicycleS)],
    [faBinocularsS], [#icon(faBinocularsS)],
    [faBiohazardS], [#icon(faBiohazardS)],
    [faBitcoinSignS], [#icon(faBitcoinSignS)],
    [faBlenderPhoneS], [#icon(faBlenderPhoneS)],
    [faBlenderS], [#icon(faBlenderS)],
    [faBlogS], [#icon(faBlogS)],
    [faBoldS], [#icon(faBoldS)],
    [faBoltLightningS], [#icon(faBoltLightningS)],
    [faBoltS], [#icon(faBoltS)],
    [faBombS], [#icon(faBombS)],
    [faBoneS], [#icon(faBoneS)],
    [faBongS], [#icon(faBongS)],
    [faBookAtlasS], [#icon(faBookAtlasS)],
    [faBookBibleS], [#icon(faBookBibleS)],
    [faBookBookmarkS], [#icon(faBookBookmarkS)],
    [faBookJournalWhillsS], [#icon(faBookJournalWhillsS)],
    [faBookMedicalS], [#icon(faBookMedicalS)],
    [faBookOpenReaderS], [#icon(faBookOpenReaderS)],
    [faBookOpenS], [#icon(faBookOpenS)],
    [faBookQuranS], [#icon(faBookQuranS)],
    [faBookSkullS], [#icon(faBookSkullS)],
    [faBookTanakhS], [#icon(faBookTanakhS)],
    [faBookS], [#icon(faBookS)],
    [faBookmarkS], [#icon(faBookmarkS)],
    [faBorderAllS], [#icon(faBorderAllS)],
    [faBorderNoneS], [#icon(faBorderNoneS)],
    [faBorderTopLeftS], [#icon(faBorderTopLeftS)],
    [faBoreHoleS], [#icon(faBoreHoleS)],
    [faBottleDropletS], [#icon(faBottleDropletS)],
    [faBottleWaterS], [#icon(faBottleWaterS)],
    [faBowlFoodS], [#icon(faBowlFoodS)],
    [faBowlRiceS], [#icon(faBowlRiceS)],
    [faBowlingBallS], [#icon(faBowlingBallS)],
    [faBoxArchiveS], [#icon(faBoxArchiveS)],
    [faBoxOpenS], [#icon(faBoxOpenS)],
    [faBoxTissueS], [#icon(faBoxTissueS)],
    [faBoxS], [#icon(faBoxS)],
    [faBoxesPackingS], [#icon(faBoxesPackingS)],
    [faBoxesStackedS], [#icon(faBoxesStackedS)],
    [faBrailleS], [#icon(faBrailleS)],
    [faBrainS], [#icon(faBrainS)],
    [faBrazilianRealSignS], [#icon(faBrazilianRealSignS)],
    [faBreadSliceS], [#icon(faBreadSliceS)],
    [faBridgeCircleCheckS], [#icon(faBridgeCircleCheckS)],
    [faBridgeCircleExclamationS], [#icon(faBridgeCircleExclamationS)],
    [faBridgeCircleXmarkS], [#icon(faBridgeCircleXmarkS)],
    [faBridgeLockS], [#icon(faBridgeLockS)],
    [faBridgeWaterS], [#icon(faBridgeWaterS)],
    [faBridgeS], [#icon(faBridgeS)],
    [faBriefcaseMedicalS], [#icon(faBriefcaseMedicalS)],
    [faBriefcaseS], [#icon(faBriefcaseS)],
    [faBroomBallS], [#icon(faBroomBallS)],
    [faBroomS], [#icon(faBroomS)],
    [faBrushS], [#icon(faBrushS)],
)])

#pagebreak()

== Bu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faBucketS], [#icon(faBucketS)],
    [faBugSlashS], [#icon(faBugSlashS)],
    [faBugS], [#icon(faBugS)],
    [faBugsS], [#icon(faBugsS)],
    [faBuildingCircleArrowRightS], [#icon(faBuildingCircleArrowRightS)],
    [faBuildingCircleCheckS], [#icon(faBuildingCircleCheckS)],
    [faBuildingCircleExclamationS], [#icon(faBuildingCircleExclamationS)],
    [faBuildingCircleXmarkS], [#icon(faBuildingCircleXmarkS)],
    [faBuildingColumnsS], [#icon(faBuildingColumnsS)],
    [faBuildingFlagS], [#icon(faBuildingFlagS)],
    [faBuildingLockS], [#icon(faBuildingLockS)],
    [faBuildingNgoS], [#icon(faBuildingNgoS)],
    [faBuildingShieldS], [#icon(faBuildingShieldS)],
    [faBuildingUnS], [#icon(faBuildingUnS)],
    [faBuildingUserS], [#icon(faBuildingUserS)],
    [faBuildingWheatS], [#icon(faBuildingWheatS)],
    [faBuildingS], [#icon(faBuildingS)],
    [faBullhornS], [#icon(faBullhornS)],
    [faBullseyeS], [#icon(faBullseyeS)],
    [faBurgerS], [#icon(faBurgerS)],
    [faBurstS], [#icon(faBurstS)],
    [faBusSimpleS], [#icon(faBusSimpleS)],
    [faBusS], [#icon(faBusS)],
    [faBusinessTimeS], [#icon(faBusinessTimeS)],
)])

== C-Ce

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faCS], [#icon(faCS)],
    [faCableCarS], [#icon(faCableCarS)],
    [faCakeCandlesS], [#icon(faCakeCandlesS)],
    [faCalculatorS], [#icon(faCalculatorS)],
    [faCalendarCheckS], [#icon(faCalendarCheckS)],
    [faCalendarDayS], [#icon(faCalendarDayS)],
    [faCalendarDaysS], [#icon(faCalendarDaysS)],
    [faCalendarMinusS], [#icon(faCalendarMinusS)],
    [faCalendarPlusS], [#icon(faCalendarPlusS)],
    [faCalendarWeekS], [#icon(faCalendarWeekS)],
    [faCalendarXmarkS], [#icon(faCalendarXmarkS)],
    [faCalendarS], [#icon(faCalendarS)],
    [faCameraRetroS], [#icon(faCameraRetroS)],
    [faCameraRotateS], [#icon(faCameraRotateS)],
    [faCameraS], [#icon(faCameraS)],
    [faCampgroundS], [#icon(faCampgroundS)],
    [faCandyCaneS], [#icon(faCandyCaneS)],
    [faCannabisS], [#icon(faCannabisS)],
    [faCapsulesS], [#icon(faCapsulesS)],
    [faCarBatteryS], [#icon(faCarBatteryS)],
    [faCarBurstS], [#icon(faCarBurstS)],
    [faCarOnS], [#icon(faCarOnS)],
    [faCarRearS], [#icon(faCarRearS)],
    [faCarSideS], [#icon(faCarSideS)],
    [faCarTunnelS], [#icon(faCarTunnelS)],
    [faCarS], [#icon(faCarS)],
    [faCaravanS], [#icon(faCaravanS)],
    [faCaretDownS], [#icon(faCaretDownS)],
    [faCaretLeftS], [#icon(faCaretLeftS)],
    [faCaretRightS], [#icon(faCaretRightS)],
    [faCaretUpS], [#icon(faCaretUpS)],
    [faCarrotS], [#icon(faCarrotS)],
    [faCartArrowDownS], [#icon(faCartArrowDownS)],
    [faCartFlatbedSuitcaseS], [#icon(faCartFlatbedSuitcaseS)],
    [faCartFlatbedS], [#icon(faCartFlatbedS)],
    [faCartPlusS], [#icon(faCartPlusS)],
    [faCartShoppingS], [#icon(faCartShoppingS)],
    [faCashRegisterS], [#icon(faCashRegisterS)],
    [faCatS], [#icon(faCatS)],
    [faCediSignS], [#icon(faCediSignS)],
    [faCentSignS], [#icon(faCentSignS)],
    [faCertificateS], [#icon(faCertificateS)],
)])

#pagebreak()

== Ch-Cl

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faChairS], [#icon(faChairS)],
    [faChalkboardUserS], [#icon(faChalkboardUserS)],
    [faChalkboardS], [#icon(faChalkboardS)],
    [faChampagneGlassesS], [#icon(faChampagneGlassesS)],
    [faChargingStationS], [#icon(faChargingStationS)],
    [faChartAreaS], [#icon(faChartAreaS)],
    [faChartBarS], [#icon(faChartBarS)],
    [faChartColumnS], [#icon(faChartColumnS)],
    [faChartGanttS], [#icon(faChartGanttS)],
    [faChartLineS], [#icon(faChartLineS)],
    [faChartPieS], [#icon(faChartPieS)],
    [faChartSimpleS], [#icon(faChartSimpleS)],
    [faCheckDoubleS], [#icon(faCheckDoubleS)],
    [faCheckToSlotS], [#icon(faCheckToSlotS)],
    [faCheckS], [#icon(faCheckS)],
    [faCheeseS], [#icon(faCheeseS)],
    [faChessBishopS], [#icon(faChessBishopS)],
    [faChessBoardS], [#icon(faChessBoardS)],
    [faChessKingS], [#icon(faChessKingS)],
    [faChessKnightS], [#icon(faChessKnightS)],
    [faChessPawnS], [#icon(faChessPawnS)],
    [faChessQueenS], [#icon(faChessQueenS)],
    [faChessRookS], [#icon(faChessRookS)],
    [faChessS], [#icon(faChessS)],
    [faChevronDownS], [#icon(faChevronDownS)],
    [faChevronLeftS], [#icon(faChevronLeftS)],
    [faChevronRightS], [#icon(faChevronRightS)],
    [faChevronUpS], [#icon(faChevronUpS)],
    [faChildCombatantS], [#icon(faChildCombatantS)],
    [faChildDressS], [#icon(faChildDressS)],
    [faChildReachingS], [#icon(faChildReachingS)],
    [faChildS], [#icon(faChildS)],
    [faChildrenS], [#icon(faChildrenS)],
    [faChurchS], [#icon(faChurchS)],
    [faCircleArrowDownS], [#icon(faCircleArrowDownS)],
    [faCircleArrowLeftS], [#icon(faCircleArrowLeftS)],
    [faCircleArrowRightS], [#icon(faCircleArrowRightS)],
    [faCircleArrowUpS], [#icon(faCircleArrowUpS)],
    [faCircleCheckS], [#icon(faCircleCheckS)],
    [faCircleChevronDownS], [#icon(faCircleChevronDownS)],
    [faCircleChevronLeftS], [#icon(faCircleChevronLeftS)],
    [faCircleChevronRightS], [#icon(faCircleChevronRightS)],
    [faCircleChevronUpS], [#icon(faCircleChevronUpS)],
    [faCircleDollarToSlotS], [#icon(faCircleDollarToSlotS)],
    [faCircleDotS], [#icon(faCircleDotS)],
    [faCircleDownS], [#icon(faCircleDownS)],
    [faCircleExclamationS], [#icon(faCircleExclamationS)],
    [faCircleHS], [#icon(faCircleHS)],
    [faCircleHalfStrokeS], [#icon(faCircleHalfStrokeS)],
    [faCircleInfoS], [#icon(faCircleInfoS)],
    [faCircleLeftS], [#icon(faCircleLeftS)],
    [faCircleMinusS], [#icon(faCircleMinusS)],
    [faCircleNodesS], [#icon(faCircleNodesS)],
    [faCircleNotchS], [#icon(faCircleNotchS)],
    [faCirclePauseS], [#icon(faCirclePauseS)],
    [faCirclePlayS], [#icon(faCirclePlayS)],
    [faCirclePlusS], [#icon(faCirclePlusS)],
    [faCircleQuestionS], [#icon(faCircleQuestionS)],
    [faCircleRadiationS], [#icon(faCircleRadiationS)],
    [faCircleRightS], [#icon(faCircleRightS)],
    [faCircleStopS], [#icon(faCircleStopS)],
    [faCircleUpS], [#icon(faCircleUpS)],
    [faCircleUserS], [#icon(faCircleUserS)],
    [faCircleXmarkS], [#icon(faCircleXmarkS)],
    [faCircleS], [#icon(faCircleS)],
    [faCityS], [#icon(faCityS)],
    [faClapperboardS], [#icon(faClapperboardS)],
    [faClipboardCheckS], [#icon(faClipboardCheckS)],
    [faClipboardListS], [#icon(faClipboardListS)],
    [faClipboardQuestionS], [#icon(faClipboardQuestionS)],
    [faClipboardUserS], [#icon(faClipboardUserS)],
    [faClipboardS], [#icon(faClipboardS)],
    [faClockRotateLeftS], [#icon(faClockRotateLeftS)],
    [faClockS], [#icon(faClockS)],
    [faCloneS], [#icon(faCloneS)],
    [faClosedCaptioningS], [#icon(faClosedCaptioningS)],
    [faCloudArrowDownS], [#icon(faCloudArrowDownS)],
    [faCloudArrowUpS], [#icon(faCloudArrowUpS)],
    [faCloudBoltS], [#icon(faCloudBoltS)],
    [faCloudMeatballS], [#icon(faCloudMeatballS)],
    [faCloudMoonRainS], [#icon(faCloudMoonRainS)],
    [faCloudMoonS], [#icon(faCloudMoonS)],
    [faCloudRainS], [#icon(faCloudRainS)],
    [faCloudShowersHeavyS], [#icon(faCloudShowersHeavyS)],
    [faCloudShowersWaterS], [#icon(faCloudShowersWaterS)],
    [faCloudSunRainS], [#icon(faCloudSunRainS)],
    [faCloudSunS], [#icon(faCloudSunS)],
    [faCloudS], [#icon(faCloudS)],
    [faCloverS], [#icon(faCloverS)],
)])

#pagebreak()

== Co-Cu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faCodeBranchS], [#icon(faCodeBranchS)],
    [faCodeCommitS], [#icon(faCodeCommitS)],
    [faCodeCompareS], [#icon(faCodeCompareS)],
    [faCodeForkS], [#icon(faCodeForkS)],
    [faCodeMergeS], [#icon(faCodeMergeS)],
    [faCodePullRequestS], [#icon(faCodePullRequestS)],
    [faCodeS], [#icon(faCodeS)],
    [faCoinsS], [#icon(faCoinsS)],
    [faColonSignS], [#icon(faColonSignS)],
    [faCommentDollarS], [#icon(faCommentDollarS)],
    [faCommentDotsS], [#icon(faCommentDotsS)],
    [faCommentMedicalS], [#icon(faCommentMedicalS)],
    [faCommentSlashS], [#icon(faCommentSlashS)],
    [faCommentSmsS], [#icon(faCommentSmsS)],
    [faCommentS], [#icon(faCommentS)],
    [faCommentsDollarS], [#icon(faCommentsDollarS)],
    [faCommentsS], [#icon(faCommentsS)],
    [faCompactDiscS], [#icon(faCompactDiscS)],
    [faCompassDraftingS], [#icon(faCompassDraftingS)],
    [faCompassS], [#icon(faCompassS)],
    [faCompressS], [#icon(faCompressS)],
    [faComputerMouseS], [#icon(faComputerMouseS)],
    [faComputerS], [#icon(faComputerS)],
    [faCookieBiteS], [#icon(faCookieBiteS)],
    [faCookieS], [#icon(faCookieS)],
    [faCopyS], [#icon(faCopyS)],
    [faCopyrightS], [#icon(faCopyrightS)],
    [faCouchS], [#icon(faCouchS)],
    [faCowS], [#icon(faCowS)],
    [faCreditCardS], [#icon(faCreditCardS)],
    [faCropSimpleS], [#icon(faCropSimpleS)],
    [faCropS], [#icon(faCropS)],
    [faCrossS], [#icon(faCrossS)],
    [faCrosshairsS], [#icon(faCrosshairsS)],
    [faCrowS], [#icon(faCrowS)],
    [faCrownS], [#icon(faCrownS)],
    [faCrutchS], [#icon(faCrutchS)],
    [faCruzeiroSignS], [#icon(faCruzeiroSignS)],
    [faCubeS], [#icon(faCubeS)],
    [faCubesStackedS], [#icon(faCubesStackedS)],
    [faCubesS], [#icon(faCubesS)],
)])

#pagebreak()

== D-E

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faDS], [#icon(faDS)],
    [faDatabaseS], [#icon(faDatabaseS)],
    [faDeleteLeftS], [#icon(faDeleteLeftS)],
    [faDemocratS], [#icon(faDemocratS)],
    [faDesktopS], [#icon(faDesktopS)],
    [faDharmachakraS], [#icon(faDharmachakraS)],
    [faDiagramNextS], [#icon(faDiagramNextS)],
    [faDiagramPredecessorS], [#icon(faDiagramPredecessorS)],
    [faDiagramProjectS], [#icon(faDiagramProjectS)],
    [faDiagramSuccessorS], [#icon(faDiagramSuccessorS)],
    [faDiamondTurnRightS], [#icon(faDiamondTurnRightS)],
    [faDiamondS], [#icon(faDiamondS)],
    [faDiceD6S], [#icon(faDiceD6S)],
    [faDiceD20S], [#icon(faDiceD20S)],
    [faDiceFiveS], [#icon(faDiceFiveS)],
    [faDiceFourS], [#icon(faDiceFourS)],
    [faDiceOneS], [#icon(faDiceOneS)],
    [faDiceSixS], [#icon(faDiceSixS)],
    [faDiceThreeS], [#icon(faDiceThreeS)],
    [faDiceTwoS], [#icon(faDiceTwoS)],
    [faDiceS], [#icon(faDiceS)],
    [faDiseaseS], [#icon(faDiseaseS)],
    [faDisplayS], [#icon(faDisplayS)],
    [faDivideS], [#icon(faDivideS)],
    [faDnaS], [#icon(faDnaS)],
    [faDogS], [#icon(faDogS)],
    [faDollarSignS], [#icon(faDollarSignS)],
    [faDollyS], [#icon(faDollyS)],
    [faDongSignS], [#icon(faDongSignS)],
    [faDoorClosedS], [#icon(faDoorClosedS)],
    [faDoorOpenS], [#icon(faDoorOpenS)],
    [faDoveS], [#icon(faDoveS)],
    [faDownLeftAndUpRightToCenterS], [#icon(faDownLeftAndUpRightToCenterS)],
    [faDownLongS], [#icon(faDownLongS)],
    [faDownloadS], [#icon(faDownloadS)],
    [faDragonS], [#icon(faDragonS)],
    [faDrawPolygonS], [#icon(faDrawPolygonS)],
    [faDropletSlashS], [#icon(faDropletSlashS)],
    [faDropletS], [#icon(faDropletS)],
    [faDrumSteelpanS], [#icon(faDrumSteelpanS)],
    [faDrumS], [#icon(faDrumS)],
    [faDrumstickBiteS], [#icon(faDrumstickBiteS)],
    [faDumbbellS], [#icon(faDumbbellS)],
    [faDumpsterFireS], [#icon(faDumpsterFireS)],
    [faDumpsterS], [#icon(faDumpsterS)],
    [faDungeonS], [#icon(faDungeonS)],
    [faES], [#icon(faES)],
    [faEarDeafS], [#icon(faEarDeafS)],
    [faEarListenS], [#icon(faEarListenS)],
    [faEarthAfricaS], [#icon(faEarthAfricaS)],
    [faEarthAmericasS], [#icon(faEarthAmericasS)],
    [faEarthAsiaS], [#icon(faEarthAsiaS)],
    [faEarthEuropeS], [#icon(faEarthEuropeS)],
    [faEarthOceaniaS], [#icon(faEarthOceaniaS)],
    [faEggS], [#icon(faEggS)],
    [faEjectS], [#icon(faEjectS)],
    [faElevatorS], [#icon(faElevatorS)],
    [faEllipsisVerticalS], [#icon(faEllipsisVerticalS)],
    [faEllipsisS], [#icon(faEllipsisS)],
    [faEnvelopeCircleCheckS], [#icon(faEnvelopeCircleCheckS)],
    [faEnvelopeOpenTextS], [#icon(faEnvelopeOpenTextS)],
    [faEnvelopeOpenS], [#icon(faEnvelopeOpenS)],
    [faEnvelopeS], [#icon(faEnvelopeS)],
    [faEnvelopesBulkS], [#icon(faEnvelopesBulkS)],
    [faEqualsS], [#icon(faEqualsS)],
    [faEraserS], [#icon(faEraserS)],
    [faEthernetS], [#icon(faEthernetS)],
    [faEuroSignS], [#icon(faEuroSignS)],
    [faExclamationS], [#icon(faExclamationS)],
    [faExpandS], [#icon(faExpandS)],
    [faExplosionS], [#icon(faExplosionS)],
    [faEyeDropperS], [#icon(faEyeDropperS)],
    [faEyeLowVisionS], [#icon(faEyeLowVisionS)],
    [faEyeSlashS], [#icon(faEyeSlashS)],
    [faEyeS], [#icon(faEyeS)],
)])

#pagebreak()

== F-Fl

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFS], [#icon(faFS)],
    [faFaceAngryS], [#icon(faFaceAngryS)],
    [faFaceDizzyS], [#icon(faFaceDizzyS)],
    [faFaceFlushedS], [#icon(faFaceFlushedS)],
    [faFaceFrownOpenS], [#icon(faFaceFrownOpenS)],
    [faFaceFrownS], [#icon(faFaceFrownS)],
    [faFaceGrimaceS], [#icon(faFaceGrimaceS)],
    [faFaceGrinBeamSweatS], [#icon(faFaceGrinBeamSweatS)],
    [faFaceGrinBeamS], [#icon(faFaceGrinBeamS)],
    [faFaceGrinHeartsS], [#icon(faFaceGrinHeartsS)],
    [faFaceGrinSquintTearsS], [#icon(faFaceGrinSquintTearsS)],
    [faFaceGrinSquintS], [#icon(faFaceGrinSquintS)],
    [faFaceGrinStarsS], [#icon(faFaceGrinStarsS)],
    [faFaceGrinTearsS], [#icon(faFaceGrinTearsS)],
    [faFaceGrinTongueSquintS], [#icon(faFaceGrinTongueSquintS)],
    [faFaceGrinTongueWinkS], [#icon(faFaceGrinTongueWinkS)],
    [faFaceGrinTongueS], [#icon(faFaceGrinTongueS)],
    [faFaceGrinWideS], [#icon(faFaceGrinWideS)],
    [faFaceGrinWinkS], [#icon(faFaceGrinWinkS)],
    [faFaceGrinS], [#icon(faFaceGrinS)],
    [faFaceKissBeamS], [#icon(faFaceKissBeamS)],
    [faFaceKissWinkHeartS], [#icon(faFaceKissWinkHeartS)],
    [faFaceKissS], [#icon(faFaceKissS)],
    [faFaceLaughBeamS], [#icon(faFaceLaughBeamS)],
    [faFaceLaughSquintS], [#icon(faFaceLaughSquintS)],
    [faFaceLaughWinkS], [#icon(faFaceLaughWinkS)],
    [faFaceLaughS], [#icon(faFaceLaughS)],
    [faFaceMehBlankS], [#icon(faFaceMehBlankS)],
    [faFaceMehS], [#icon(faFaceMehS)],
    [faFaceRollingEyesS], [#icon(faFaceRollingEyesS)],
    [faFaceSadCryS], [#icon(faFaceSadCryS)],
    [faFaceSadTearS], [#icon(faFaceSadTearS)],
    [faFaceSmileBeamS], [#icon(faFaceSmileBeamS)],
    [faFaceSmileWinkS], [#icon(faFaceSmileWinkS)],
    [faFaceSmileS], [#icon(faFaceSmileS)],
    [faFaceSurpriseS], [#icon(faFaceSurpriseS)],
    [faFaceTiredS], [#icon(faFaceTiredS)],
    [faFanS], [#icon(faFanS)],
    [faFaucetDripS], [#icon(faFaucetDripS)],
    [faFaucetS], [#icon(faFaucetS)],
    [faFaxS], [#icon(faFaxS)],
    [faFeatherPointedS], [#icon(faFeatherPointedS)],
    [faFeatherS], [#icon(faFeatherS)],
    [faFerryS], [#icon(faFerryS)],
    [faFileArrowDownS], [#icon(faFileArrowDownS)],
    [faFileArrowUpS], [#icon(faFileArrowUpS)],
    [faFileAudioS], [#icon(faFileAudioS)],
    [faFileCircleCheckS], [#icon(faFileCircleCheckS)],
    [faFileCircleExclamationS], [#icon(faFileCircleExclamationS)],
    [faFileCircleMinusS], [#icon(faFileCircleMinusS)],
    [faFileCirclePlusS], [#icon(faFileCirclePlusS)],
    [faFileCircleQuestionS], [#icon(faFileCircleQuestionS)],
    [faFileCircleXmarkS], [#icon(faFileCircleXmarkS)],
    [faFileCodeS], [#icon(faFileCodeS)],
    [faFileContractS], [#icon(faFileContractS)],
    [faFileCsvS], [#icon(faFileCsvS)],
    [faFileExcelS], [#icon(faFileExcelS)],
    [faFileExportS], [#icon(faFileExportS)],
    [faFileImageS], [#icon(faFileImageS)],
    [faFileImportS], [#icon(faFileImportS)],
    [faFileInvoiceDollarS], [#icon(faFileInvoiceDollarS)],
    [faFileInvoiceS], [#icon(faFileInvoiceS)],
    [faFileLinesS], [#icon(faFileLinesS)],
    [faFileMedicalS], [#icon(faFileMedicalS)],
    [faFilePdfS], [#icon(faFilePdfS)],
    [faFilePenS], [#icon(faFilePenS)],
    [faFilePowerpointS], [#icon(faFilePowerpointS)],
    [faFilePrescriptionS], [#icon(faFilePrescriptionS)],
    [faFileShieldS], [#icon(faFileShieldS)],
    [faFileSignatureS], [#icon(faFileSignatureS)],
    [faFileVideoS], [#icon(faFileVideoS)],
    [faFileWaveformS], [#icon(faFileWaveformS)],
    [faFileWordS], [#icon(faFileWordS)],
    [faFileZipperS], [#icon(faFileZipperS)],
    [faFileS], [#icon(faFileS)],
    [faFillDripS], [#icon(faFillDripS)],
    [faFillS], [#icon(faFillS)],
    [faFilmS], [#icon(faFilmS)],
    [faFilterCircleDollarS], [#icon(faFilterCircleDollarS)],
    [faFilterCircleXmarkS], [#icon(faFilterCircleXmarkS)],
    [faFilterS], [#icon(faFilterS)],
    [faFingerprintS], [#icon(faFingerprintS)],
    [faFireBurnerS], [#icon(faFireBurnerS)],
    [faFireExtinguisherS], [#icon(faFireExtinguisherS)],
    [faFireFlameCurvedS], [#icon(faFireFlameCurvedS)],
    [faFireFlameSimpleS], [#icon(faFireFlameSimpleS)],
    [faFireS], [#icon(faFireS)],
    [faFishFinsS], [#icon(faFishFinsS)],
    [faFishS], [#icon(faFishS)],
    [faFlagCheckeredS], [#icon(faFlagCheckeredS)],
    [faFlagUsaS], [#icon(faFlagUsaS)],
    [faFlagS], [#icon(faFlagS)],
    [faFlaskVialS], [#icon(faFlaskVialS)],
    [faFlaskS], [#icon(faFlaskS)],
    [faFloppyDiskS], [#icon(faFloppyDiskS)],
    [faFlorinSignS], [#icon(faFlorinSignS)],
)])

#pagebreak()

== Fo-Fu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faFolderClosedS], [#icon(faFolderClosedS)],
    [faFolderMinusS], [#icon(faFolderMinusS)],
    [faFolderOpenS], [#icon(faFolderOpenS)],
    [faFolderPlusS], [#icon(faFolderPlusS)],
    [faFolderTreeS], [#icon(faFolderTreeS)],
    [faFolderS], [#icon(faFolderS)],
    [faFontAwesomeS], [#icon(faFontAwesomeS)],
    [faFontS], [#icon(faFontS)],
    [faFootballS], [#icon(faFootballS)],
    [faForwardFastS], [#icon(faForwardFastS)],
    [faForwardStepS], [#icon(faForwardStepS)],
    [faForwardS], [#icon(faForwardS)],
    [faFrancSignS], [#icon(faFrancSignS)],
    [faFrogS], [#icon(faFrogS)],
    [faFutbolS], [#icon(faFutbolS)],
)])

== G

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faGS], [#icon(faGS)],
    [faGamepadS], [#icon(faGamepadS)],
    [faGasPumpS], [#icon(faGasPumpS)],
    [faGaugeHighS], [#icon(faGaugeHighS)],
    [faGaugeSimpleHighS], [#icon(faGaugeSimpleHighS)],
    [faGaugeSimpleS], [#icon(faGaugeSimpleS)],
    [faGaugeS], [#icon(faGaugeS)],
    [faGavelS], [#icon(faGavelS)],
    [faGearS], [#icon(faGearS)],
    [faGearsS], [#icon(faGearsS)],
    [faGemS], [#icon(faGemS)],
    [faGenderlessS], [#icon(faGenderlessS)],
    [faGhostS], [#icon(faGhostS)],
    [faGiftS], [#icon(faGiftS)],
    [faGiftsS], [#icon(faGiftsS)],
    [faGlassWaterDropletS], [#icon(faGlassWaterDropletS)],
    [faGlassWaterS], [#icon(faGlassWaterS)],
    [faGlassesS], [#icon(faGlassesS)],
    [faGlobeS], [#icon(faGlobeS)],
    [faGolfBallTeeS], [#icon(faGolfBallTeeS)],
    [faGopuramS], [#icon(faGopuramS)],
    [faGraduationCapS], [#icon(faGraduationCapS)],
    [faGreaterThanEqualS], [#icon(faGreaterThanEqualS)],
    [faGreaterThanS], [#icon(faGreaterThanS)],
    [faGripLinesVerticalS], [#icon(faGripLinesVerticalS)],
    [faGripLinesS], [#icon(faGripLinesS)],
    [faGripVerticalS], [#icon(faGripVerticalS)],
    [faGripS], [#icon(faGripS)],
    [faGroupArrowsRotateS], [#icon(faGroupArrowsRotateS)],
    [faGuaraniSignS], [#icon(faGuaraniSignS)],
    [faGuitarS], [#icon(faGuitarS)],
    [faGunS], [#icon(faGunS)],
)])

#pagebreak()

== H-Hi

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faHS], [#icon(faHS)],
    [faHammerS], [#icon(faHammerS)],
    [faHamsaS], [#icon(faHamsaS)],
    [faHandBackFistS], [#icon(faHandBackFistS)],
    [faHandDotsS], [#icon(faHandDotsS)],
    [faHandFistS], [#icon(faHandFistS)],
    [faHandHoldingDollarS], [#icon(faHandHoldingDollarS)],
    [faHandHoldingDropletS], [#icon(faHandHoldingDropletS)],
    [faHandHoldingHandS], [#icon(faHandHoldingHandS)],
    [faHandHoldingHeartS], [#icon(faHandHoldingHeartS)],
    [faHandHoldingMedicalS], [#icon(faHandHoldingMedicalS)],
    [faHandHoldingS], [#icon(faHandHoldingS)],
    [faHandLizardS], [#icon(faHandLizardS)],
    [faHandMiddleFingerS], [#icon(faHandMiddleFingerS)],
    [faHandPeaceS], [#icon(faHandPeaceS)],
    [faHandPointDownS], [#icon(faHandPointDownS)],
    [faHandPointLeftS], [#icon(faHandPointLeftS)],
    [faHandPointRightS], [#icon(faHandPointRightS)],
    [faHandPointUpS], [#icon(faHandPointUpS)],
    [faHandPointerS], [#icon(faHandPointerS)],
    [faHandScissorsS], [#icon(faHandScissorsS)],
    [faHandSparklesS], [#icon(faHandSparklesS)],
    [faHandSpockS], [#icon(faHandSpockS)],
    [faHandS], [#icon(faHandS)],
    [faHandcuffsS], [#icon(faHandcuffsS)],
    [faHandsAslInterpretingS], [#icon(faHandsAslInterpretingS)],
    [faHandsBoundS], [#icon(faHandsBoundS)],
    [faHandsBubblesS], [#icon(faHandsBubblesS)],
    [faHandsClappingS], [#icon(faHandsClappingS)],
    [faHandsHoldingChildS], [#icon(faHandsHoldingChildS)],
    [faHandsHoldingCircleS], [#icon(faHandsHoldingCircleS)],
    [faHandsHoldingS], [#icon(faHandsHoldingS)],
    [faHandsPrayingS], [#icon(faHandsPrayingS)],
    [faHandsS], [#icon(faHandsS)],
    [faHandshakeAngleS], [#icon(faHandshakeAngleS)],
    [faHandshakeSimpleSlashS], [#icon(faHandshakeSimpleSlashS)],
    [faHandshakeSimpleS], [#icon(faHandshakeSimpleS)],
    [faHandshakeSlashS], [#icon(faHandshakeSlashS)],
    [faHandshakeS], [#icon(faHandshakeS)],
    [faHanukiahS], [#icon(faHanukiahS)],
    [faHardDriveS], [#icon(faHardDriveS)],
    [faHashtagS], [#icon(faHashtagS)],
    [faHatCowboySideS], [#icon(faHatCowboySideS)],
    [faHatCowboyS], [#icon(faHatCowboyS)],
    [faHatWizardS], [#icon(faHatWizardS)],
    [faHeadSideCoughSlashS], [#icon(faHeadSideCoughSlashS)],
    [faHeadSideCoughS], [#icon(faHeadSideCoughS)],
    [faHeadSideMaskS], [#icon(faHeadSideMaskS)],
    [faHeadSideVirusS], [#icon(faHeadSideVirusS)],
    [faHeadingS], [#icon(faHeadingS)],
    [faHeadphonesSimpleS], [#icon(faHeadphonesSimpleS)],
    [faHeadphonesS], [#icon(faHeadphonesS)],
    [faHeadsetS], [#icon(faHeadsetS)],
    [faHeartCircleBoltS], [#icon(faHeartCircleBoltS)],
    [faHeartCircleCheckS], [#icon(faHeartCircleCheckS)],
    [faHeartCircleExclamationS], [#icon(faHeartCircleExclamationS)],
    [faHeartCircleMinusS], [#icon(faHeartCircleMinusS)],
    [faHeartCirclePlusS], [#icon(faHeartCirclePlusS)],
    [faHeartCircleXmarkS], [#icon(faHeartCircleXmarkS)],
    [faHeartCrackS], [#icon(faHeartCrackS)],
    [faHeartPulseS], [#icon(faHeartPulseS)],
    [faHeartS], [#icon(faHeartS)],
    [faHelicopterSymbolS], [#icon(faHelicopterSymbolS)],
    [faHelicopterS], [#icon(faHelicopterS)],
    [faHelmetSafetyS], [#icon(faHelmetSafetyS)],
    [faHelmetUnS], [#icon(faHelmetUnS)],
    [faHighlighterS], [#icon(faHighlighterS)],
    [faHillAvalancheS], [#icon(faHillAvalancheS)],
    [faHillRockslideS], [#icon(faHillRockslideS)],
    [faHippoS], [#icon(faHippoS)],
)])

#pagebreak()

== Ho

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faHockeyPuckS], [#icon(faHockeyPuckS)],
    [faHollyBerryS], [#icon(faHollyBerryS)],
    [faHorseHeadS], [#icon(faHorseHeadS)],
    [faHorseS], [#icon(faHorseS)],
    [faHospitalUserS], [#icon(faHospitalUserS)],
    [faHospitalS], [#icon(faHospitalS)],
    [faHotTubPersonS], [#icon(faHotTubPersonS)],
    [faHotdogS], [#icon(faHotdogS)],
    [faHotelS], [#icon(faHotelS)],
    [faHourglassEndS], [#icon(faHourglassEndS)],
    [faHourglassHalfS], [#icon(faHourglassHalfS)],
    [faHourglassStartS], [#icon(faHourglassStartS)],
    [faHourglassS], [#icon(faHourglassS)],
    [faHouseChimneyCrackS], [#icon(faHouseChimneyCrackS)],
    [faHouseChimneyMedicalS], [#icon(faHouseChimneyMedicalS)],
    [faHouseChimneyUserS], [#icon(faHouseChimneyUserS)],
    [faHouseChimneyWindowS], [#icon(faHouseChimneyWindowS)],
    [faHouseChimneyS], [#icon(faHouseChimneyS)],
    [faHouseCircleCheckS], [#icon(faHouseCircleCheckS)],
    [faHouseCircleExclamationS], [#icon(faHouseCircleExclamationS)],
    [faHouseCircleXmarkS], [#icon(faHouseCircleXmarkS)],
    [faHouseCrackS], [#icon(faHouseCrackS)],
    [faHouseFireS], [#icon(faHouseFireS)],
    [faHouseFlagS], [#icon(faHouseFlagS)],
    [faHouseFloodWaterCircleArrowRightS], [#icon(faHouseFloodWaterCircleArrowRightS)],
    [faHouseFloodWaterS], [#icon(faHouseFloodWaterS)],
    [faHouseLaptopS], [#icon(faHouseLaptopS)],
    [faHouseLockS], [#icon(faHouseLockS)],
    [faHouseMedicalCircleCheckS], [#icon(faHouseMedicalCircleCheckS)],
    [faHouseMedicalCircleExclamationS], [#icon(faHouseMedicalCircleExclamationS)],
    [faHouseMedicalCircleXmarkS], [#icon(faHouseMedicalCircleXmarkS)],
    [faHouseMedicalFlagS], [#icon(faHouseMedicalFlagS)],
    [faHouseMedicalS], [#icon(faHouseMedicalS)],
    [faHouseSignalS], [#icon(faHouseSignalS)],
    [faHouseTsunamiS], [#icon(faHouseTsunamiS)],
    [faHouseUserS], [#icon(faHouseUserS)],
    [faHouseS], [#icon(faHouseS)],
    [faHryvniaSignS], [#icon(faHryvniaSignS)],
    [faHurricaneS], [#icon(faHurricaneS)],
    [faICursorS], [#icon(faICursorS)],
)])

== I-J

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faIS], [#icon(faIS)],
    [faIceCreamS], [#icon(faIceCreamS)],
    [faIciclesS], [#icon(faIciclesS)],
    [faIconsS], [#icon(faIconsS)],
    [faIdBadgeS], [#icon(faIdBadgeS)],
    [faIdCardClipS], [#icon(faIdCardClipS)],
    [faIdCardS], [#icon(faIdCardS)],
    [faIglooS], [#icon(faIglooS)],
    [faImagePortraitS], [#icon(faImagePortraitS)],
    [faImageS], [#icon(faImageS)],
    [faImagesS], [#icon(faImagesS)],
    [faInboxS], [#icon(faInboxS)],
    [faIndentS], [#icon(faIndentS)],
    [faIndianRupeeSignS], [#icon(faIndianRupeeSignS)],
    [faIndustryS], [#icon(faIndustryS)],
    [faInfinityS], [#icon(faInfinityS)],
    [faInfoS], [#icon(faInfoS)],
    [faItalicS], [#icon(faItalicS)],
    [faJS], [#icon(faJS)],
    [faJarWheatS], [#icon(faJarWheatS)],
    [faJarS], [#icon(faJarS)],
    [faJediS], [#icon(faJediS)],
    [faJetFighterUpS], [#icon(faJetFighterUpS)],
    [faJetFighterS], [#icon(faJetFighterS)],
    [faJointS], [#icon(faJointS)],
    [faJugDetergentS], [#icon(faJugDetergentS)],
    [faKS], [#icon(faKS)],
    [faKaabaS], [#icon(faKaabaS)],
    [faKeyS], [#icon(faKeyS)],
    [faKeyboardS], [#icon(faKeyboardS)],
    [faKhandaS], [#icon(faKhandaS)],
    [faKipSignS], [#icon(faKipSignS)],
    [faKitMedicalS], [#icon(faKitMedicalS)],
    [faKitchenSetS], [#icon(faKitchenSetS)],
    [faKiwiBirdS], [#icon(faKiwiBirdS)],
)])

#pagebreak()

== L

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faLS], [#icon(faLS)],
    [faLandMineOnS], [#icon(faLandMineOnS)],
    [faLandmarkDomeS], [#icon(faLandmarkDomeS)],
    [faLandmarkFlagS], [#icon(faLandmarkFlagS)],
    [faLandmarkS], [#icon(faLandmarkS)],
    [faLanguageS], [#icon(faLanguageS)],
    [faLaptopCodeS], [#icon(faLaptopCodeS)],
    [faLaptopFileS], [#icon(faLaptopFileS)],
    [faLaptopMedicalS], [#icon(faLaptopMedicalS)],
    [faLaptopS], [#icon(faLaptopS)],
    [faLariSignS], [#icon(faLariSignS)],
    [faLayerGroupS], [#icon(faLayerGroupS)],
    [faLeafS], [#icon(faLeafS)],
    [faLeftLongS], [#icon(faLeftLongS)],
    [faLeftRightS], [#icon(faLeftRightS)],
    [faLemonS], [#icon(faLemonS)],
    [faLessThanEqualS], [#icon(faLessThanEqualS)],
    [faLessThanS], [#icon(faLessThanS)],
    [faLifeRingS], [#icon(faLifeRingS)],
    [faLightbulbS], [#icon(faLightbulbS)],
    [faLinesLeaningS], [#icon(faLinesLeaningS)],
    [faLinkSlashS], [#icon(faLinkSlashS)],
    [faLinkS], [#icon(faLinkS)],
    [faLiraSignS], [#icon(faLiraSignS)],
    [faListCheckS], [#icon(faListCheckS)],
    [faListOlS], [#icon(faListOlS)],
    [faListUlS], [#icon(faListUlS)],
    [faListS], [#icon(faListS)],
    [faLitecoinSignS], [#icon(faLitecoinSignS)],
    [faLocationArrowS], [#icon(faLocationArrowS)],
    [faLocationCrosshairsS], [#icon(faLocationCrosshairsS)],
    [faLocationDotS], [#icon(faLocationDotS)],
    [faLocationPinLockS], [#icon(faLocationPinLockS)],
    [faLocationPinS], [#icon(faLocationPinS)],
    [faLockOpenS], [#icon(faLockOpenS)],
    [faLockS], [#icon(faLockS)],
    [faLocustS], [#icon(faLocustS)],
    [faLungsVirusS], [#icon(faLungsVirusS)],
    [faLungsS], [#icon(faLungsS)],
)])

== M-Mi

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faMS], [#icon(faMS)],
    [faMagnetS], [#icon(faMagnetS)],
    [faMagnifyingGlassArrowRightS], [#icon(faMagnifyingGlassArrowRightS)],
    [faMagnifyingGlassChartS], [#icon(faMagnifyingGlassChartS)],
    [faMagnifyingGlassDollarS], [#icon(faMagnifyingGlassDollarS)],
    [faMagnifyingGlassLocationS], [#icon(faMagnifyingGlassLocationS)],
    [faMagnifyingGlassMinusS], [#icon(faMagnifyingGlassMinusS)],
    [faMagnifyingGlassPlusS], [#icon(faMagnifyingGlassPlusS)],
    [faMagnifyingGlassS], [#icon(faMagnifyingGlassS)],
    [faManatSignS], [#icon(faManatSignS)],
    [faMapLocationDotS], [#icon(faMapLocationDotS)],
    [faMapLocationS], [#icon(faMapLocationS)],
    [faMapPinS], [#icon(faMapPinS)],
    [faMapS], [#icon(faMapS)],
    [faMarkerS], [#icon(faMarkerS)],
    [faMarsAndVenusBurstS], [#icon(faMarsAndVenusBurstS)],
    [faMarsAndVenusS], [#icon(faMarsAndVenusS)],
    [faMarsDoubleS], [#icon(faMarsDoubleS)],
    [faMarsStrokeRightS], [#icon(faMarsStrokeRightS)],
    [faMarsStrokeUpS], [#icon(faMarsStrokeUpS)],
    [faMarsStrokeS], [#icon(faMarsStrokeS)],
    [faMarsS], [#icon(faMarsS)],
    [faMartiniGlassCitrusS], [#icon(faMartiniGlassCitrusS)],
    [faMartiniGlassEmptyS], [#icon(faMartiniGlassEmptyS)],
    [faMartiniGlassS], [#icon(faMartiniGlassS)],
    [faMaskFaceS], [#icon(faMaskFaceS)],
    [faMaskVentilatorS], [#icon(faMaskVentilatorS)],
    [faMaskS], [#icon(faMaskS)],
    [faMasksTheaterS], [#icon(faMasksTheaterS)],
    [faMattressPillowS], [#icon(faMattressPillowS)],
    [faMaximizeS], [#icon(faMaximizeS)],
    [faMedalS], [#icon(faMedalS)],
    [faMemoryS], [#icon(faMemoryS)],
    [faMenorahS], [#icon(faMenorahS)],
    [faMercuryS], [#icon(faMercuryS)],
    [faMessageS], [#icon(faMessageS)],
    [faMeteorS], [#icon(faMeteorS)],
    [faMicrochipS], [#icon(faMicrochipS)],
    [faMicrophoneLinesSlashS], [#icon(faMicrophoneLinesSlashS)],
    [faMicrophoneLinesS], [#icon(faMicrophoneLinesS)],
    [faMicrophoneSlashS], [#icon(faMicrophoneSlashS)],
    [faMicrophoneS], [#icon(faMicrophoneS)],
    [faMicroscopeS], [#icon(faMicroscopeS)],
    [faMillSignS], [#icon(faMillSignS)],
    [faMinimizeS], [#icon(faMinimizeS)],
    [faMinusS], [#icon(faMinusS)],
    [faMittenS], [#icon(faMittenS)],
)])

#pagebreak()

== Mo-Mu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faMobileButtonS], [#icon(faMobileButtonS)],
    [faMobileRetroS], [#icon(faMobileRetroS)],
    [faMobileScreenButtonS], [#icon(faMobileScreenButtonS)],
    [faMobileScreenS], [#icon(faMobileScreenS)],
    [faMobileS], [#icon(faMobileS)],
    [faMoneyBill1WaveS], [#icon(faMoneyBill1WaveS)],
    [faMoneyBill1S], [#icon(faMoneyBill1S)],
    [faMoneyBillTransferS], [#icon(faMoneyBillTransferS)],
    [faMoneyBillTrendUpS], [#icon(faMoneyBillTrendUpS)],
    [faMoneyBillWaveS], [#icon(faMoneyBillWaveS)],
    [faMoneyBillWheatS], [#icon(faMoneyBillWheatS)],
    [faMoneyBillS], [#icon(faMoneyBillS)],
    [faMoneyBillsS], [#icon(faMoneyBillsS)],
    [faMoneyCheckDollarS], [#icon(faMoneyCheckDollarS)],
    [faMoneyCheckS], [#icon(faMoneyCheckS)],
    [faMonumentS], [#icon(faMonumentS)],
    [faMoonS], [#icon(faMoonS)],
    [faMortarPestleS], [#icon(faMortarPestleS)],
    [faMosqueS], [#icon(faMosqueS)],
    [faMosquitoNetS], [#icon(faMosquitoNetS)],
    [faMosquitoS], [#icon(faMosquitoS)],
    [faMotorcycleS], [#icon(faMotorcycleS)],
    [faMoundS], [#icon(faMoundS)],
    [faMountainCityS], [#icon(faMountainCityS)],
    [faMountainSunS], [#icon(faMountainSunS)],
    [faMountainS], [#icon(faMountainS)],
    [faMugHotS], [#icon(faMugHotS)],
    [faMugSaucerS], [#icon(faMugSaucerS)],
    [faMusicS], [#icon(faMusicS)],
)])

== N

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [faNS], [#icon(faNS)],
    [faNairaSignS], [#icon(faNairaSignS)],
    [faNetworkWiredS], [#icon(faNetworkWiredS)],
    [faNeuterS], [#icon(faNeuterS)],
    [faNewspaperS], [#icon(faNewspaperS)],
    [faNotEqualS], [#icon(faNotEqualS)],
    [faNotdefS], [#icon(faNotdefS)],
    [faNoteStickyS], [#icon(faNoteStickyS)],
    [faNotesMedicalS], [#icon(faNotesMedicalS)],
    [faOS], [#icon(faOS)],
    [faObjectGroupS], [#icon(faObjectGroupS)],
    [faObjectUngroupS], [#icon(faObjectUngroupS)],
    [faOilCanS], [#icon(faOilCanS)],
    [faOilWellS], [#icon(faOilWellS)],
    [faOmS], [#icon(faOmS)],
    [faOtterS], [#icon(faOtterS)],
    [faOutdentS], [#icon(faOutdentS)],
)])

== P-Pep

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faPS], [#icon(faPS)],
    [faPagerS], [#icon(faPagerS)],
    [faPaintRollerS], [#icon(faPaintRollerS)],
    [faPaintbrushS], [#icon(faPaintbrushS)],
    [faPaletteS], [#icon(faPaletteS)],
    [faPalletS], [#icon(faPalletS)],
    [faPanoramaS], [#icon(faPanoramaS)],
    [faPaperPlaneS], [#icon(faPaperPlaneS)],
    [faPaperclipS], [#icon(faPaperclipS)],
    [faParachuteBoxS], [#icon(faParachuteBoxS)],
    [faParagraphS], [#icon(faParagraphS)],
    [faPassportS], [#icon(faPassportS)],
    [faPasteS], [#icon(faPasteS)],
    [faPauseS], [#icon(faPauseS)],
    [faPawS], [#icon(faPawS)],
    [faPeaceS], [#icon(faPeaceS)],
    [faPenClipS], [#icon(faPenClipS)],
    [faPenFancyS], [#icon(faPenFancyS)],
    [faPenNibS], [#icon(faPenNibS)],
    [faPenRulerS], [#icon(faPenRulerS)],
    [faPenToSquareS], [#icon(faPenToSquareS)],
    [faPenS], [#icon(faPenS)],
    [faPencilS], [#icon(faPencilS)],
    [faPeopleArrowsS], [#icon(faPeopleArrowsS)],
    [faPeopleCarryBoxS], [#icon(faPeopleCarryBoxS)],
    [faPeopleGroupS], [#icon(faPeopleGroupS)],
    [faPeopleLineS], [#icon(faPeopleLineS)],
    [faPeoplePullingS], [#icon(faPeoplePullingS)],
    [faPeopleRobberyS], [#icon(faPeopleRobberyS)],
    [faPeopleRoofS], [#icon(faPeopleRoofS)],
    [faPepperHotS], [#icon(faPepperHotS)],
)])

#pagebreak()

== Per-Pu

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faPercentS], [#icon(faPercentS)],
    [faPersonArrowDownToLineS], [#icon(faPersonArrowDownToLineS)],
    [faPersonArrowUpFromLineS], [#icon(faPersonArrowUpFromLineS)],
    [faPersonBikingS], [#icon(faPersonBikingS)],
    [faPersonBoothS], [#icon(faPersonBoothS)],
    [faPersonBreastfeedingS], [#icon(faPersonBreastfeedingS)],
    [faPersonBurstS], [#icon(faPersonBurstS)],
    [faPersonCaneS], [#icon(faPersonCaneS)],
    [faPersonChalkboardS], [#icon(faPersonChalkboardS)],
    [faPersonCircleCheckS], [#icon(faPersonCircleCheckS)],
    [faPersonCircleExclamationS], [#icon(faPersonCircleExclamationS)],
    [faPersonCircleMinusS], [#icon(faPersonCircleMinusS)],
    [faPersonCirclePlusS], [#icon(faPersonCirclePlusS)],
    [faPersonCircleQuestionS], [#icon(faPersonCircleQuestionS)],
    [faPersonCircleXmarkS], [#icon(faPersonCircleXmarkS)],
    [faPersonDiggingS], [#icon(faPersonDiggingS)],
    [faPersonDotsFromLineS], [#icon(faPersonDotsFromLineS)],
    [faPersonDressBurstS], [#icon(faPersonDressBurstS)],
    [faPersonDressS], [#icon(faPersonDressS)],
    [faPersonDrowningS], [#icon(faPersonDrowningS)],
    [faPersonFallingBurstS], [#icon(faPersonFallingBurstS)],
    [faPersonFallingS], [#icon(faPersonFallingS)],
    [faPersonHalfDressS], [#icon(faPersonHalfDressS)],
    [faPersonHarassingS], [#icon(faPersonHarassingS)],
    [faPersonHikingS], [#icon(faPersonHikingS)],
    [faPersonMilitaryPointingS], [#icon(faPersonMilitaryPointingS)],
    [faPersonMilitaryRifleS], [#icon(faPersonMilitaryRifleS)],
    [faPersonMilitaryToPersonS], [#icon(faPersonMilitaryToPersonS)],
    [faPersonPrayingS], [#icon(faPersonPrayingS)],
    [faPersonPregnantS], [#icon(faPersonPregnantS)],
    [faPersonRaysS], [#icon(faPersonRaysS)],
    [faPersonRifleS], [#icon(faPersonRifleS)],
    [faPersonRunningS], [#icon(faPersonRunningS)],
    [faPersonShelterS], [#icon(faPersonShelterS)],
    [faPersonSkatingS], [#icon(faPersonSkatingS)],
    [faPersonSkiingNordicS], [#icon(faPersonSkiingNordicS)],
    [faPersonSkiingS], [#icon(faPersonSkiingS)],
    [faPersonSnowboardingS], [#icon(faPersonSnowboardingS)],
    [faPersonSwimmingS], [#icon(faPersonSwimmingS)],
    [faPersonThroughWindowS], [#icon(faPersonThroughWindowS)],
    [faPersonWalkingArrowLoopLeftS], [#icon(faPersonWalkingArrowLoopLeftS)],
    [faPersonWalkingArrowRightS], [#icon(faPersonWalkingArrowRightS)],
    [faPersonWalkingDashedLineArrowRightS], [#icon(faPersonWalkingDashedLineArrowRightS)],
    [faPersonWalkingLuggageS], [#icon(faPersonWalkingLuggageS)],
    [faPersonWalkingWithCaneS], [#icon(faPersonWalkingWithCaneS)],
    [faPersonWalkingS], [#icon(faPersonWalkingS)],
    [faPersonS], [#icon(faPersonS)],
    [faPesetaSignS], [#icon(faPesetaSignS)],
    [faPesoSignS], [#icon(faPesoSignS)],
    [faPhoneFlipS], [#icon(faPhoneFlipS)],
    [faPhoneSlashS], [#icon(faPhoneSlashS)],
    [faPhoneVolumeS], [#icon(faPhoneVolumeS)],
    [faPhoneS], [#icon(faPhoneS)],
    [faPhotoFilmS], [#icon(faPhotoFilmS)],
    [faPiggyBankS], [#icon(faPiggyBankS)],
    [faPillsS], [#icon(faPillsS)],
    [faPizzaSliceS], [#icon(faPizzaSliceS)],
    [faPlaceOfWorshipS], [#icon(faPlaceOfWorshipS)],
    [faPlaneArrivalS], [#icon(faPlaneArrivalS)],
    [faPlaneCircleCheckS], [#icon(faPlaneCircleCheckS)],
    [faPlaneCircleExclamationS], [#icon(faPlaneCircleExclamationS)],
    [faPlaneCircleXmarkS], [#icon(faPlaneCircleXmarkS)],
    [faPlaneDepartureS], [#icon(faPlaneDepartureS)],
    [faPlaneLockS], [#icon(faPlaneLockS)],
    [faPlaneSlashS], [#icon(faPlaneSlashS)],
    [faPlaneUpS], [#icon(faPlaneUpS)],
    [faPlaneS], [#icon(faPlaneS)],
    [faPlantWiltS], [#icon(faPlantWiltS)],
    [faPlateWheatS], [#icon(faPlateWheatS)],
    [faPlayS], [#icon(faPlayS)],
    [faPlugCircleBoltS], [#icon(faPlugCircleBoltS)],
    [faPlugCircleCheckS], [#icon(faPlugCircleCheckS)],
    [faPlugCircleExclamationS], [#icon(faPlugCircleExclamationS)],
    [faPlugCircleMinusS], [#icon(faPlugCircleMinusS)],
    [faPlugCirclePlusS], [#icon(faPlugCirclePlusS)],
    [faPlugCircleXmarkS], [#icon(faPlugCircleXmarkS)],
    [faPlugS], [#icon(faPlugS)],
    [faPlusMinusS], [#icon(faPlusMinusS)],
    [faPlusS], [#icon(faPlusS)],
    [faPodcastS], [#icon(faPodcastS)],
    [faPooStormS], [#icon(faPooStormS)],
    [faPooS], [#icon(faPooS)],
    [faPoopS], [#icon(faPoopS)],
    [faPowerOffS], [#icon(faPowerOffS)],
    [faPrescriptionBottleMedicalS], [#icon(faPrescriptionBottleMedicalS)],
    [faPrescriptionBottleS], [#icon(faPrescriptionBottleS)],
    [faPrescriptionS], [#icon(faPrescriptionS)],
    [faPrintS], [#icon(faPrintS)],
    [faPumpMedicalS], [#icon(faPumpMedicalS)],
    [faPumpSoapS], [#icon(faPumpSoapS)],
    [faPuzzlePieceS], [#icon(faPuzzlePieceS)],
)])

== Q-R

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faQS], [#icon(faQS)],
    [faQrcodeS], [#icon(faQrcodeS)],
    [faQuestionS], [#icon(faQuestionS)],
    [faQuoteLeftS], [#icon(faQuoteLeftS)],
    [faQuoteRightS], [#icon(faQuoteRightS)],
    [faRS], [#icon(faRS)],
    [faRadiationS], [#icon(faRadiationS)],
    [faRadioS], [#icon(faRadioS)],
    [faRainbowS], [#icon(faRainbowS)],
    [faRankingStarS], [#icon(faRankingStarS)],
    [faReceiptS], [#icon(faReceiptS)],
    [faRecordVinylS], [#icon(faRecordVinylS)],
    [faRectangleAdS], [#icon(faRectangleAdS)],
    [faRectangleListS], [#icon(faRectangleListS)],
    [faRectangleXmarkS], [#icon(faRectangleXmarkS)],
    [faRecycleS], [#icon(faRecycleS)],
    [faRegisteredS], [#icon(faRegisteredS)],
    [faRepeatS], [#icon(faRepeatS)],
    [faReplyAllS], [#icon(faReplyAllS)],
    [faReplyS], [#icon(faReplyS)],
    [faRepublicanS], [#icon(faRepublicanS)],
    [faRestroomS], [#icon(faRestroomS)],
    [faRetweetS], [#icon(faRetweetS)],
    [faRibbonS], [#icon(faRibbonS)],
    [faRightFromBracketS], [#icon(faRightFromBracketS)],
    [faRightLeftS], [#icon(faRightLeftS)],
    [faRightLongS], [#icon(faRightLongS)],
    [faRightToBracketS], [#icon(faRightToBracketS)],
    [faRingS], [#icon(faRingS)],
    [faRoadBarrierS], [#icon(faRoadBarrierS)],
    [faRoadBridgeS], [#icon(faRoadBridgeS)],
    [faRoadCircleCheckS], [#icon(faRoadCircleCheckS)],
    [faRoadCircleExclamationS], [#icon(faRoadCircleExclamationS)],
    [faRoadCircleXmarkS], [#icon(faRoadCircleXmarkS)],
    [faRoadLockS], [#icon(faRoadLockS)],
    [faRoadSpikesS], [#icon(faRoadSpikesS)],
    [faRoadS], [#icon(faRoadS)],
    [faRobotS], [#icon(faRobotS)],
    [faRocketS], [#icon(faRocketS)],
    [faRotateLeftS], [#icon(faRotateLeftS)],
    [faRotateRightS], [#icon(faRotateRightS)],
    [faRotateS], [#icon(faRotateS)],
    [faRouteS], [#icon(faRouteS)],
    [faRssS], [#icon(faRssS)],
    [faRubleSignS], [#icon(faRubleSignS)],
    [faRugS], [#icon(faRugS)],
    [faRulerCombinedS], [#icon(faRulerCombinedS)],
    [faRulerHorizontalS], [#icon(faRulerHorizontalS)],
    [faRulerVerticalS], [#icon(faRulerVerticalS)],
    [faRulerS], [#icon(faRulerS)],
    [faRupeeSignS], [#icon(faRupeeSignS)],
    [faRupiahSignS], [#icon(faRupiahSignS)],
)])

== S-Se

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faSS], [#icon(faSS)],
    [faSackDollarS], [#icon(faSackDollarS)],
    [faSackXmarkS], [#icon(faSackXmarkS)],
    [faSailboatS], [#icon(faSailboatS)],
    [faSatelliteDishS], [#icon(faSatelliteDishS)],
    [faSatelliteS], [#icon(faSatelliteS)],
    [faScaleBalancedS], [#icon(faScaleBalancedS)],
    [faScaleUnbalancedFlipS], [#icon(faScaleUnbalancedFlipS)],
    [faScaleUnbalancedS], [#icon(faScaleUnbalancedS)],
    [faSchoolCircleCheckS], [#icon(faSchoolCircleCheckS)],
    [faSchoolCircleExclamationS], [#icon(faSchoolCircleExclamationS)],
    [faSchoolCircleXmarkS], [#icon(faSchoolCircleXmarkS)],
    [faSchoolFlagS], [#icon(faSchoolFlagS)],
    [faSchoolLockS], [#icon(faSchoolLockS)],
    [faSchoolS], [#icon(faSchoolS)],
    [faScissorsS], [#icon(faScissorsS)],
    [faScrewdriverWrenchS], [#icon(faScrewdriverWrenchS)],
    [faScrewdriverS], [#icon(faScrewdriverS)],
    [faScrollTorahS], [#icon(faScrollTorahS)],
    [faScrollS], [#icon(faScrollS)],
    [faSdCardS], [#icon(faSdCardS)],
    [faSectionS], [#icon(faSectionS)],
    [faSeedlingS], [#icon(faSeedlingS)],
    [faServerS], [#icon(faServerS)],
)])

#pagebreak()

== Sh-Sq

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faShapesS], [#icon(faShapesS)],
    [faShareFromSquareS], [#icon(faShareFromSquareS)],
    [faShareNodesS], [#icon(faShareNodesS)],
    [faShareS], [#icon(faShareS)],
    [faSheetPlasticS], [#icon(faSheetPlasticS)],
    [faShekelSignS], [#icon(faShekelSignS)],
    [faShieldCatS], [#icon(faShieldCatS)],
    [faShieldDogS], [#icon(faShieldDogS)],
    [faShieldHalvedS], [#icon(faShieldHalvedS)],
    [faShieldHeartS], [#icon(faShieldHeartS)],
    [faShieldVirusS], [#icon(faShieldVirusS)],
    [faShieldS], [#icon(faShieldS)],
    [faShipS], [#icon(faShipS)],
    [faShirtS], [#icon(faShirtS)],
    [faShoePrintsS], [#icon(faShoePrintsS)],
    [faShopLockS], [#icon(faShopLockS)],
    [faShopSlashS], [#icon(faShopSlashS)],
    [faShopS], [#icon(faShopS)],
    [faShowerS], [#icon(faShowerS)],
    [faShrimpS], [#icon(faShrimpS)],
    [faShuffleS], [#icon(faShuffleS)],
    [faShuttleSpaceS], [#icon(faShuttleSpaceS)],
    [faSignHangingS], [#icon(faSignHangingS)],
    [faSignalS], [#icon(faSignalS)],
    [faSignatureS], [#icon(faSignatureS)],
    [faSignsPostS], [#icon(faSignsPostS)],
    [faSimCardS], [#icon(faSimCardS)],
    [faSinkS], [#icon(faSinkS)],
    [faSitemapS], [#icon(faSitemapS)],
    [faSkullCrossbonesS], [#icon(faSkullCrossbonesS)],
    [faSkullS], [#icon(faSkullS)],
    [faSlashS], [#icon(faSlashS)],
    [faSleighS], [#icon(faSleighS)],
    [faSlidersS], [#icon(faSlidersS)],
    [faSmogS], [#icon(faSmogS)],
    [faSmokingS], [#icon(faSmokingS)],
    [faSnowflakeS], [#icon(faSnowflakeS)],
    [faSnowmanS], [#icon(faSnowmanS)],
    [faSnowplowS], [#icon(faSnowplowS)],
    [faSoapS], [#icon(faSoapS)],
    [faSocksS], [#icon(faSocksS)],
    [faSolarPanelS], [#icon(faSolarPanelS)],
    [faSortDownS], [#icon(faSortDownS)],
    [faSortUpS], [#icon(faSortUpS)],
    [faSortS], [#icon(faSortS)],
    [faSpaS], [#icon(faSpaS)],
    [faSpaghettiMonsterFlyingS], [#icon(faSpaghettiMonsterFlyingS)],
    [faSpellCheckS], [#icon(faSpellCheckS)],
    [faSpiderS], [#icon(faSpiderS)],
    [faSpinnerS], [#icon(faSpinnerS)],
    [faSplotchS], [#icon(faSplotchS)],
    [faSpoonS], [#icon(faSpoonS)],
    [faSprayCanSparklesS], [#icon(faSprayCanSparklesS)],
    [faSprayCanS], [#icon(faSprayCanS)],
    [faSquareArrowUpRightS], [#icon(faSquareArrowUpRightS)],
    [faSquareCaretDownS], [#icon(faSquareCaretDownS)],
    [faSquareCaretLeftS], [#icon(faSquareCaretLeftS)],
    [faSquareCaretRightS], [#icon(faSquareCaretRightS)],
    [faSquareCaretUpS], [#icon(faSquareCaretUpS)],
    [faSquareCheckS], [#icon(faSquareCheckS)],
    [faSquareEnvelopeS], [#icon(faSquareEnvelopeS)],
    [faSquareFullS], [#icon(faSquareFullS)],
    [faSquareHS], [#icon(faSquareHS)],
    [faSquareMinusS], [#icon(faSquareMinusS)],
    [faSquareNfiS], [#icon(faSquareNfiS)],
    [faSquareParkingS], [#icon(faSquareParkingS)],
    [faSquarePenS], [#icon(faSquarePenS)],
    [faSquarePersonConfinedS], [#icon(faSquarePersonConfinedS)],
    [faSquarePhoneFlipS], [#icon(faSquarePhoneFlipS)],
    [faSquarePhoneS], [#icon(faSquarePhoneS)],
    [faSquarePlusS], [#icon(faSquarePlusS)],
    [faSquarePollHorizontalS], [#icon(faSquarePollHorizontalS)],
    [faSsquarePollVerticalS], [#icon(faSsquarePollVerticalS)],
    [faSquareRootVariableS], [#icon(faSquareRootVariableS)],
    [faSquareRssS], [#icon(faSquareRssS)],
    [faSquareShareNodesS], [#icon(faSquareShareNodesS)],
    [faSquareUpRightS], [#icon(faSquareUpRightS)],
    [faSquareVirusS], [#icon(faSquareVirusS)],
    [faSquareXmarkS], [#icon(faSquareXmarkS)],
    [faSquareS], [#icon(faSquareS)],
)])

#pagebreak()

== St-Sy

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faStaffSnakeS], [#icon(faStaffSnakeS)],
    [faStairsS], [#icon(faStairsS)],
    [faStampS], [#icon(faStampS)],
    [faStaplerS], [#icon(faStaplerS)],
    [faStarAndCrescentS], [#icon(faStarAndCrescentS)],
    [faStarHalfStrokeS], [#icon(faStarHalfStrokeS)],
    [faStarHalfS], [#icon(faStarHalfS)],
    [faStarOfDavidS], [#icon(faStarOfDavidS)],
    [faStarOfLifeS], [#icon(faStarOfLifeS)],
    [faStarS], [#icon(faStarS)],
    [faSterlingSignS], [#icon(faSterlingSignS)],
    [faStethoscopeS], [#icon(faStethoscopeS)],
    [faStopS], [#icon(faStopS)],
    [faStopwatch20S], [#icon(faStopwatch20S)],
    [faStopwatchS], [#icon(faStopwatchS)],
    [faStoreSlashS], [#icon(faStoreSlashS)],
    [faStoreS], [#icon(faStoreS)],
    [faStreetViewS], [#icon(faStreetViewS)],
    [faStrikethroughS], [#icon(faStrikethroughS)],
    [faStroopwafelS], [#icon(faStroopwafelS)],
    [faSubscriptS], [#icon(faSubscriptS)],
    [faSuitcaseMedicalS], [#icon(faSuitcaseMedicalS)],
    [faSuitcaseRollingS], [#icon(faSuitcaseRollingS)],
    [faSuitcaseS], [#icon(faSuitcaseS)],
    [faSunPlantWiltS], [#icon(faSunPlantWiltS)],
    [faSunS], [#icon(faSunS)],
    [faSuperscriptS], [#icon(faSuperscriptS)],
    [faSwatchbookS], [#icon(faSwatchbookS)],
    [faSynagogueS], [#icon(faSynagogueS)],
    [faSyringeS], [#icon(faSyringeS)],
)])

== T-Ti

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faTS], [#icon(faTS)],
    [faTableCellsLargeS], [#icon(faTableCellsLargeS)],
    [faTableCellsS], [#icon(faTableCellsS)],
    [faTableColumnsS], [#icon(faTableColumnsS)],
    [faTableListS], [#icon(faTableListS)],
    [faTableTennisPaddleBallS], [#icon(faTableTennisPaddleBallS)],
    [faTableS], [#icon(faTableS)],
    [faTabletButtonS], [#icon(faTabletButtonS)],
    [faTabletScreenButtonS], [#icon(faTabletScreenButtonS)],
    [faTabletS], [#icon(faTabletS)],
    [faTabletsS], [#icon(faTabletsS)],
    [faTachographDigitalS], [#icon(faTachographDigitalS)],
    [faTagS], [#icon(faTagS)],
    [faTagsS], [#icon(faTagsS)],
    [faTapeS], [#icon(faTapeS)],
    [faTarpDropletS], [#icon(faTarpDropletS)],
    [faTarpS], [#icon(faTarpS)],
    [faTaxiS], [#icon(faTaxiS)],
    [faTeethOpenS], [#icon(faTeethOpenS)],
    [faTeethS], [#icon(faTeethS)],
    [faTemperatureArrowDownS], [#icon(faTemperatureArrowDownS)],
    [faTemperatureArrowUpS], [#icon(faTemperatureArrowUpS)],
    [faTemperatureEmptyS], [#icon(faTemperatureEmptyS)],
    [faTemperatureFullS], [#icon(faTemperatureFullS)],
    [faTemperatureHalfS], [#icon(faTemperatureHalfS)],
    [faTemperatureHighS], [#icon(faTemperatureHighS)],
    [faTemperatureLowS], [#icon(faTemperatureLowS)],
    [faTemperatureQuarterS], [#icon(faTemperatureQuarterS)],
    [faTemperatureThreeQuartersS], [#icon(faTemperatureThreeQuartersS)],
    [faTengeSignS], [#icon(faTengeSignS)],
    [faTentArrowDownToLineS], [#icon(faTentArrowDownToLineS)],
    [faTentArrowLeftRightS], [#icon(faTentArrowLeftRightS)],
    [faTentArrowTurnLeftS], [#icon(faTentArrowTurnLeftS)],
    [faTentArrowsDownS], [#icon(faTentArrowsDownS)],
    [faTentS], [#icon(faTentS)],
    [faTentsS], [#icon(faTentsS)],
    [faTerminalS], [#icon(faTerminalS)],
    [faTextHeightS], [#icon(faTextHeightS)],
    [faTextSlashS], [#icon(faTextSlashS)],
    [faTextWidthS], [#icon(faTextWidthS)],
    [faThermometerS], [#icon(faThermometerS)],
    [faThumbsDownS], [#icon(faThumbsDownS)],
    [faThumbsUpS], [#icon(faThumbsUpS)],
    [faThumbtackS], [#icon(faThumbtackS)],
    [faTicketSimpleS], [#icon(faTicketSimpleS)],
    [faTicketS], [#icon(faTicketS)],
    [faTimelineS], [#icon(faTimelineS)],
)])

#pagebreak()

== To

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faToggleOffS], [#icon(faToggleOffS)],
    [faToggleOnS], [#icon(faToggleOnS)],
    [faToiletPaperSlashS], [#icon(faToiletPaperSlashS)],
    [faToiletPaperS], [#icon(faToiletPaperS)],
    [faToiletPortableS], [#icon(faToiletPortableS)],
    [faToiletS], [#icon(faToiletS)],
    [faToiletsPortableS], [#icon(faToiletsPortableS)],
    [faToolboxS], [#icon(faToolboxS)],
    [faToothS], [#icon(faToothS)],
    [faToriiGateS], [#icon(faToriiGateS)],
    [faTornadoS], [#icon(faTornadoS)],
    [faTowerBroadcastS], [#icon(faTowerBroadcastS)],
    [faTowerCellS], [#icon(faTowerCellS)],
    [faTowerObservationS], [#icon(faTowerObservationS)],
    [faTractorS], [#icon(faTractorS)],
    [faTrademarkS], [#icon(faTrademarkS)],
    [faTrafficLightS], [#icon(faTrafficLightS)],
    [faTrailerS], [#icon(faTrailerS)],
    [faTrainSubwayS], [#icon(faTrainSubwayS)],
    [faTrainTramS], [#icon(faTrainTramS)],
    [faTrainS], [#icon(faTrainS)],
    [faTransgenderS], [#icon(faTransgenderS)],
    [faTrashArrowUpS], [#icon(faTrashArrowUpS)],
    [faTrashCanArrowUpS], [#icon(faTrashCanArrowUpS)],
    [faTrashCanS], [#icon(faTrashCanS)],
    [faTrashS], [#icon(faTrashS)],
    [faTreeCityS], [#icon(faTreeCityS)],
    [faTreeS], [#icon(faTreeS)],
    [faTriangleExclamationS], [#icon(faTriangleExclamationS)],
    [faTrophyS], [#icon(faTrophyS)],
    [faTrowelBricksS], [#icon(faTrowelBricksS)],
    [faTrowelS], [#icon(faTrowelS)],
    [faTruckArrowRightS], [#icon(faTruckArrowRightS)],
    [faTruckDropletS], [#icon(faTruckDropletS)],
    [faTruckFastS], [#icon(faTruckFastS)],
    [faTruckFieldUnS], [#icon(faTruckFieldUnS)],
    [faTruckFieldS], [#icon(faTruckFieldS)],
    [faTruckFrontS], [#icon(faTruckFrontS)],
    [faTruckMedicalS], [#icon(faTruckMedicalS)],
    [faTruckMonsterS], [#icon(faTruckMonsterS)],
    [faTruckMovingS], [#icon(faTruckMovingS)],
    [faTruckPickupS], [#icon(faTruckPickupS)],
    [faTruckPlaneS], [#icon(faTruckPlaneS)],
    [faTruckRampBoxS], [#icon(faTruckRampBoxS)],
    [faTruckS], [#icon(faTruckS)],
    [faTtyS], [#icon(faTtyS)],
    [faTurkishLiraSignS], [#icon(faTurkishLiraSignS)],
    [faTurnDownS], [#icon(faTurnDownS)],
    [faTurnUpS], [#icon(faTurnUpS)],
    [faTvS], [#icon(faTvS)],
)])

#pagebreak()

== U-V

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faUS], [#icon(faUS)],
    [faUmbrellaBeachS], [#icon(faUmbrellaBeachS)],
    [faUmbrellaS], [#icon(faUmbrellaS)],
    [faUnderlineS], [#icon(faUnderlineS)],
    [faUniversalAccessS], [#icon(faUniversalAccessS)],
    [faUnlockKeyholeS], [#icon(faUnlockKeyholeS)],
    [faUnlockS], [#icon(faUnlockS)],
    [faUpDownLeftRightS], [#icon(faUpDownLeftRightS)],
    [faUpDownS], [#icon(faUpDownS)],
    [faUpLongS], [#icon(faUpLongS)],
    [faUpRightAndDownLeftFromCenterS], [#icon(faUpRightAndDownLeftFromCenterS)],
    [faUpRightFromSquareS], [#icon(faUpRightFromSquareS)],
    [faUploadS], [#icon(faUploadS)],
    [faUserAstronautS], [#icon(faUserAstronautS)],
    [faUserCheckS], [#icon(faUserCheckS)],
    [faUserClockS], [#icon(faUserClockS)],
    [faUserDoctorS], [#icon(faUserDoctorS)],
    [faUserGearS], [#icon(faUserGearS)],
    [faUserGraduateS], [#icon(faUserGraduateS)],
    [faUserGroupS], [#icon(faUserGroupS)],
    [faUserInjuredS], [#icon(faUserInjuredS)],
    [faUserLargeSlashS], [#icon(faUserLargeSlashS)],
    [faUserLargeS], [#icon(faUserLargeS)],
    [faUserLockS], [#icon(faUserLockS)],
    [faUserMinusS], [#icon(faUserMinusS)],
    [faUserNinjaS], [#icon(faUserNinjaS)],
    [faUserNurseS], [#icon(faUserNurseS)],
    [faUserPenS], [#icon(faUserPenS)],
    [faUserPlusS], [#icon(faUserPlusS)],
    [faUserSecretS], [#icon(faUserSecretS)],
    [faUserShieldS], [#icon(faUserShieldS)],
    [faUserSlashS], [#icon(faUserSlashS)],
    [faUserTagS], [#icon(faUserTagS)],
    [faUserTieS], [#icon(faUserTieS)],
    [faUserXmarkS], [#icon(faUserXmarkS)],
    [faUserS], [#icon(faUserS)],
    [faUsersBetweenLinesS], [#icon(faUsersBetweenLinesS)],
    [faUsersGearS], [#icon(faUsersGearS)],
    [faUsersLineS], [#icon(faUsersLineS)],
    [faUsersRaysS], [#icon(faUsersRaysS)],
    [faUsersRectangleS], [#icon(faUsersRectangleS)],
    [faUsersSlashS], [#icon(faUsersSlashS)],
    [faUsersViewfinderS], [#icon(faUsersViewfinderS)],
    [faUsersS], [#icon(faUsersS)],
    [faUtensilsS], [#icon(faUtensilsS)],
    [faVS], [#icon(faVS)],
    [faVanShuttleS], [#icon(faVanShuttleS)],
    [faVaultS], [#icon(faVaultS)],
    [faVectorSquareS], [#icon(faVectorSquareS)],
    [faVenusDoubleS], [#icon(faVenusDoubleS)],
    [faVenusMarsS], [#icon(faVenusMarsS)],
    [faVenusS], [#icon(faVenusS)],
    [faVestPatchesS], [#icon(faVestPatchesS)],
    [faVestS], [#icon(faVestS)],
    [faVialCircleCheckS], [#icon(faVialCircleCheckS)],
    [faVialVirusS], [#icon(faVialVirusS)],
    [faVialS], [#icon(faVialS)],
    [faVialsS], [#icon(faVialsS)],
    [faVideoSlashS], [#icon(faVideoSlashS)],
    [faVideoS], [#icon(faVideoS)],
    [faViharaS], [#icon(faViharaS)],
    [faVirusCovidSlashS], [#icon(faVirusCovidSlashS)],
    [faVirusCovidS], [#icon(faVirusCovidS)],
    [faVirusSlashS], [#icon(faVirusSlashS)],
    [faVirusS], [#icon(faVirusS)],
    [faVirusesS], [#icon(faVirusesS)],
    [faVoicemailS], [#icon(faVoicemailS)],
    [faVolcanoS], [#icon(faVolcanoS)],
    [faVolleyballS], [#icon(faVolleyballS)],
    [faVolumeHighS], [#icon(faVolumeHighS)],
    [faVolumeLowS], [#icon(faVolumeLowS)],
    [faVolumeOffS], [#icon(faVolumeOffS)],
    [faVolumeXmarkS], [#icon(faVolumeXmarkS)],
    [faVrCardboardS], [#icon(faVrCardboardS)],
)])

#pagebreak()

== W-Z

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [faWS], [#icon(faWS)],
    [faWalkieTalkieS], [#icon(faWalkieTalkieS)],
    [faWalletS], [#icon(faWalletS)],
    [faWandMagicSparklesS], [#icon(faWandMagicSparklesS)],
    [faWandMagicS], [#icon(faWandMagicS)],
    [faWandSparklesS], [#icon(faWandSparklesS)],
    [faWarehouseS], [#icon(faWarehouseS)],
    [faWaterLadderS], [#icon(faWaterLadderS)],
    [faWaterS], [#icon(faWaterS)],
    [faWaveSquareS], [#icon(faWaveSquareS)],
    [faWeightHangingS], [#icon(faWeightHangingS)],
    [faWeightScaleS], [#icon(faWeightScaleS)],
    [faWheatAwnCircleExclamationS], [#icon(faWheatAwnCircleExclamationS)],
    [faWheatAwnS], [#icon(faWheatAwnS)],
    [faWheelchairMoveS], [#icon(faWheelchairMoveS)],
    [faWheelchairS], [#icon(faWheelchairS)],
    [faWhiskeyGlassS], [#icon(faWhiskeyGlassS)],
    [faWifiS], [#icon(faWifiS)],
    [faWindS], [#icon(faWindS)],
    [faWindowMaximizeS], [#icon(faWindowMaximizeS)],
    [faWindowMinimizeS], [#icon(faWindowMinimizeS)],
    [faWindowRestoreS], [#icon(faWindowRestoreS)],
    [faWineBottleS], [#icon(faWineBottleS)],
    [faWineGlassEmptyS], [#icon(faWineGlassEmptyS)],
    [faWineGlassS], [#icon(faWineGlassS)],
    [faWonSignS], [#icon(faWonSignS)],
    [faWormS], [#icon(faWormS)],
    [faWrenchS], [#icon(faWrenchS)],
    [faXRayS], [#icon(faXRayS)],
    [faXS], [#icon(faXS)],
    [faXmarkS], [#icon(faXmarkS)],
    [faXmarksLinesS], [#icon(faXmarksLinesS)],
    [faYS], [#icon(faYS)],
    [faYenSignS], [#icon(faYenSignS)],
    [faYinYangS], [#icon(faYinYangS)],
    [faZS], [#icon(faZS)],
)])

== 0-9

#figure(
align(center)[#table(
    columns: 10,
    align: center,
    [fa0S], [#icon(fa0S)],
    [fa1S], [#icon(fa1S)],
    [fa2S], [#icon(fa2S)],
    [fa3S], [#icon(fa3S)],
    [fa4S], [#icon(fa4S)],
    [fa5S], [#icon(fa5S)],
    [fa6S], [#icon(fa6S)],
    [fa7S], [#icon(fa7S)],
    [fa8S], [#icon(fa8S)],
    [fa9S], [#icon(fa9S)],
)])
